### ISSUE TITLE
it detect my AC on network but I can't control it 

### ISSUE THREAD

**Issue by sh0ckwavevr6** [georgezhao2010/midea_ac_lan#1]
Hi, Awesome project! The detection find my device but once it's done,  the temperature displayed stay at 20 and i can't control any function. So the AC is detected but don't communicate

I tried with different Token and Key without success but those works with another project (midea-ac-py)

the log file didn't shows error. I run Home Assistant 2021.8.8

**Comment by georgezhao2010** [comment]
> Hi, Awesome project! The detection find my device but once it's done, the temperature displayed stay at 20 and i can't control any function. So the AC is detected but don't communicate
> 
> I tried with different Token and Key without success but those works with another project (midea-ac-py)
> 
> the log file didn't shows error. I run Home Assistant 2021.8.8

Thanks for reporting, I'll have a look at that and see what I can do.
