### ISSUE TITLE
Recent update problem 

### ISSUE THREAD

**Issue by snug-inglenook** [georgezhao2010/midea_ac_lan#100]
Updated HA and Midea and now I get:
Unable to prepare setup for platform midea_ac_lan.fan: Platform not found (No module named 'custom_components.midea_ac_lan.midea.devices.fa').

Please help

**Comment by Opontios** [comment]
Confirming.
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 13:45:25 (3 occurrences)
Last logged: 13:55:05

Unable to prepare setup for platform midea_ac_lan.fan: Platform not found (No module named 'custom_components.midea_ac_lan.midea.devices.fa').

**Comment by georgezhao2010** [comment]
https://github.com/georgezhao2010/midea_ac_lan/issues/99
