### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by screem20056** [georgezhao2010/midea_ac_lan#102]
It works as previously with minor defects 
but it keep reporting now invalid config

Unable to prepare setup for platform midea_ac_lan.fan: Platform not found (No module named 'custom_components.midea_ac_lan.midea.devices.fa').

Regards

**Comment by boctok** [comment]
I have been getting the same error for a couple of weeks.

Logger: homeassistant.setup
Source: setup.py:320 
First occurred: 11:32:32 PM (1 occurrences) 
Last logged: 11:32:32 PM

Unable to prepare setup for platform midea_ac_lan.fan: Platform not found (No module named 'custom_components.midea_ac_lan.midea.devices.fa').

**Comment by georgezhao2010** [comment]
update to 0.3.13-Patch1

**Comment by screem20056** [comment]
Already updated but i redownloaded it and now works 
Thanks
