### ISSUE TITLE
Midea AC LAN: set_attribute

### ISSUE THREAD

**Issue by besiktas97** [georgezhao2010/midea_ac_lan#107]
Hello,

When I am trying to call a service like below:

service: midea_ac_lan.set_attribute
data:
  device_id: 807fa8fef382950de6040b02b33e8a56
  attribute: prompt_tone
  value: false

I am getting the next error and the automation isn't starting:

Failed to call service midea_ac_lan.set_attribute. expected int for dictionary value @ data['device_id']. Got None

**Comment by georgezhao2010** [comment]
> Hello,
> 
> When I am trying to call a service like below:
> 
> service: midea_ac_lan.set_attribute data: device_id: 807fa8fef382950de6040b02b33e8a56 attribute: prompt_tone value: false
> 
> I am getting the next error and the automation isn't starting:
> 
> Failed to call service midea_ac_lan.set_attribute. expected int for dictionary value @ data['device_id']. Got None

The device_id you are using is incorrect.

See the entity_id of climate entity to find it, as `climate.{device_id}_climate`.

**Comment by besiktas97** [comment]
I have also try it with how you are telling but getting the same error message:

service: midea_ac_lan.set_attribute
data:
  device_id: climate.18691697880319_climate
  attribute: prompt_tone
  value: false

**Comment by georgezhao2010** [comment]
> service: midea_ac_lan.set_attribute
> data:
> device_id: climate.18691697880319_climate
> attribute: prompt_tone
> value: false

```
service: midea_ac_lan.set_attribute
data:
    device_id: 18691697880319
    attribute: prompt_tone
    value: false
```

**Comment by besiktas97** [comment]
> 18691697880319

owh oeps. thats working. thanks :-)
