### ISSUE TITLE
Feature request: Frost Protection mode

### ISSUE THREAD

**Issue by slawekb** [georgezhao2010/midea_ac_lan#112]
Some Midea and compatible AC models support a frost protection mode (FP), that maintains a temperature of 8°C.
On the remote, it can be activated in HEAT mode, by setting the temperature to 17°C (lowest setting) and then pressing the down arrow again.
It is also supported in the MSmartHome app, so it should be possible.

**Comment by bdkacz** [comment]
+1 I have rotenso revio with this future and also will be nice to enable it via HA

**Comment by flyoffacliff** [comment]
+1
I have my garage unit in this mode all the time! Anyone know of a workaround for now? Or a different integration that supports this.
Happy to help in any way I can.

**Comment by tobisnet** [comment]
+1 from my side as well for this enhancement.
Have a Dimstal AC in the garage and use this mode most of the time.

**Comment by georgezhao2010** [comment]
Merging into #141
