### ISSUE TITLE
Provide a separate python library

### ISSUE THREAD

**Issue by TA2k** [georgezhao2010/midea_ac_lan#113]
It would be a huge contribution if you provide this as a separate python library and not all functionality deeply integrated into the HA component

**Comment by georgezhao2010** [comment]
In fact, the abstraction and core functionality of the Midea device are not integrated with homeassistant. The `custom_componnent/midea_ac_lan/midea` provides all the device functions and does not depend on homeassistant. The reason why it has not been made into a separate python library is that the project is in the mid-term development stage and its functions are still undergoing significant modifications.
