### ISSUE TITLE
华菱空调N8HE1，没有默认实体

### ISSUE THREAD

**Issue by WuMing-YQ** [georgezhao2010/midea_ac_lan#118]
两台华菱空调N8HE1是先添加进了美的美居，因此无法自动搜索发现，按IP添加后可以添加完成，但没有生成默认实体，因此就找不到怎么添加温度控制的方法了。

**Comment by georgezhao2010** [comment]
> 两台华菱空调N8HE1是先添加进了美的美居，因此无法自动搜索发现，按IP添加后可以添加完成，但没有生成默认实体，因此就找不到怎么添加温度控制的方法了。

我跟你打赌，你HA版本高于2022.5算我输，但你为啥不看着README中明明白白写着最低要求HA2022.5？

**Comment by WuMing-YQ** [comment]
确实，谢谢你的提醒。我的问题，因为刚刚上手HA，在群晖的Docker中选择了latest标签下载，这让我下意识的以为应该会是最近的新版本，就没有仔细核对，没想到回头检查才发现是2021.X。随即重新安装新版本HA后功能正常，十分好用。虽然自动搜索还是失败了（可能是在群晖的Docker中运行的问题？（设置了与群晖相同网络））但是已经使用IP地址添加了设备，无伤大雅，目的都达到了。再次感谢。
