### ISSUE TITLE
Sometimes integration stop working with all AC device

### ISSUE THREAD

**Issue by marcoahp** [georgezhao2010/midea_ac_lan#119]
Sometimes the integration stop working. The AC devices connects perfectly with midea app. The solution is to remove and add again the integration. Reload, and disabling and enabling don't fixes the problem.

**Comment by georgezhao2010** [comment]
> Sometimes the integration stop working. The AC devices connects perfectly with midea app. The solution is to remove and add again the integration. Reload, and disabling and enabling don't fixes the problem.

Turn the debug log on, and check if any helpful information in the logs.

**Comment by chunkystyles** [comment]
> Sometimes the integration stop working. The AC devices connects perfectly with midea app. The solution is to remove and add again the integration. Reload, and disabling and enabling don't fixes the problem.

I have had single units stop responding.  The component displays stale data and the unit does not respond to any commands from the component.  In that instance, I've found that restarting HA completely resolves it.  I just updated the component today and I was pretty well out of date.  I don't know if this is fixed in newer versions or not.

**Comment by marcoahp** [comment]
This is the log:
2022-10-19 11:00:18.073 DEBUG (AC Dormitorio) [custom_components.midea_ac_lan.midea.core.device] [4288095348XXXX] Connection error
2022-10-19 11:00:18.074 DEBUG (AC Dormitorio) [custom_components.midea_ac_lan.midea.core.device] [4288095348XXXX] Status update: {'available': False}
2022-10-19 11:00:23.188 DEBUG (AC Dormitorio) [custom_components.midea_ac_lan.midea.core.device] [4288095348XXXX] Connection error
2022-10-19 11:00:23.188 DEBUG (AC Dormitorio) [custom_components.midea_ac_lan.midea.core.device] [4288095348XXXX] Status update: {'available': False}

I remove the integration and add again and IT works.

**Comment by marcoahp** [comment]
Nobody have this problem? I have ro remove and add again the devices every one or two weeks. It happens when I reboot the internet router and ins some cases without rebooting the router.

**Comment by chunkystyles** [comment]
> Nobody have this problem? I have ro remove and add again the devices every one or two weeks. It happens when I reboot the internet router and ins some cases without rebooting the router.

Per [this other issue](https://github.com/georgezhao2010/midea_ac_lan/issues/132) the fix is to set static IP addresses for your units.  I've done this and haven't had the issue since then.

**Comment by marcoahp** [comment]
> > Nobody have this problem? I have ro remove and add again the devices every one or two weeks. It happens when I reboot the internet router and ins some cases without rebooting the router.
> 
> Per [this other issue](https://github.com/georgezhao2010/midea_ac_lan/issues/132) the fix is to set static IP addresses for your units. I've done this and haven't had the issue since then.

Yes, I've know that could be the problem. But my router do not allow to reserve ip upper than 192.168.1.200 and have assigned 201, and 202 to my conditioners, so I can reserve ip. Other integrations don't have this problem, so I imagine it can be fixed.

**Comment by SikaiGGMU** [comment]
I experienced the same issue. My workaround is reboot my router; or add the ac panel devices to the blacklist of the router, such that all panels get disconnected from the router, 10 seconds later remove ac panels from the blacklist, and the integration get back on track.

**Comment by SikaiGGMU** [comment]
Such workaround is still annoying, hope it can be fixed.

**Comment by MACscr** [comment]
Can you not even update the existing IP address in HA? I find it crazy that the configure options are so limited. Everything that was configured initially should be able to be updated in my opinion.

**Comment by SikaiGGMU** [comment]
> Can you not even update the existing IP address in HA? I find it crazy that the configure options are so limited. Everything that was configured initially should be able to be updated in my opinion.

Actually, you can, but you have to go through the config file in the homeassistant directory.
