### ISSUE TITLE
小天鹅洗衣机无法控制只能显示状态

### ISSUE THREAD

**Issue by 185086074** [georgezhao2010/midea_ac_lan#120]
![Screenshot_2022-10-13-18-54-00-684_com android browser](https://user-images.githubusercontent.com/34123511/195582748-88e31abf-d403-4b7f-bc6a-53f0519a8b37.jpg)
洗衣机型号为 小天鹅TB100FTEC 
点击开关按钮没有效果 手动开关洗衣机 ha上可以显示状态 但是控制不了 而且状态有时候会变为不可用状态 在不可用状态下手动开关洗衣机也可以立刻显示状态 删除重新添加也是一样的问题 只可以显示状态而没法控制

**Comment by georgezhao2010** [comment]
提供全程日志，可以发到我邮箱。
