### ISSUE TITLE
取暖器控制报错

### ISSUE THREAD

**Issue by mctary** [georgezhao2010/midea_ac_lan#121]
![微信图片_20221014131755](https://user-images.githubusercontent.com/39021125/195767895-3eec8ffc-4394-4a1f-8e0e-de8937944063.jpg)
接入美的HDY22TH踢脚线取暖器，控制时报错
调用服务 switch/turn_on 失败。'>' not supported between instances of 'NoneType' and 'int'

**Comment by georgezhao2010** [comment]
给我看日志

**Comment by mctary** [comment]
> 给我看日志

[home-assistant (1).log](https://github.com/georgezhao2010/midea_ac_lan/files/9793826/home-assistant.1.log)

**Comment by georgezhao2010** [comment]
> > 给我看日志
> 
> [home-assistant (1).log](https://github.com/georgezhao2010/midea_ac_lan/files/9793826/home-assistant.1.log)

你要是能打开midea_ac_lan的调试日志就更好了，目前看到的是你的设备子类型没有取到，但是具体取子设备类型的过程并没有看到。

**Comment by GavinXue** [comment]
遇到了同样的问题，尝试了很多次，但好像没有好的办法，我有两个取暖器，有时候一个能设置成功，有时候两个失败，有时候重启 Home Assistant 也会导致包同样的错误。看了一下 log 是一样的

**Comment by Foxyz28** [comment]
同样的问题，期待解决

**Comment by KaoluAngel** [comment]
> 看了下报错日志，在 fb/message.py 文件下判断时，用 None 做了判断。于是我在 MessageSet 的构造函数里面直接在 sub_type 为 None 的时候，付了一个值1，可以解决这个问题，但没搞清楚就不太好。不知道是不是 取暖器没有 sub_type 这个东西？ 我是直接在这里加的，希望对找问题有帮助 @georgezhao2010
> 
> ```python
> class MessageSet(MessageFBBase):
>     def __init__(self, device_protocol_version, sub_type):
>         super().__init__(
>             device_protocol_version=device_protocol_version,
>             message_type=MessageType.set,
>             body_type=0x00)
>         # 下面是修改的赋值
>         self.sub_type = sub_type if sub_type != None else 1
>         self.power = None
>         self.mode = None
>         self.heating_level = None
>         self.target_temperature = None
>         self.child_lock = None
> ```

@GavinXue 万分感谢 我的问题解决了

**Comment by georgezhao2010** [comment]
尝试 #269 中的临时解决方案，应该可以临时解决，问题会在下一个版本中更新。
