### ISSUE TITLE
Can not set Heat target temperature to 16C

### ISSUE THREAD

**Issue by misipakko** [georgezhao2010/midea_ac_lan#124]
Unit Midea Oasis+ Nordic.(MSOPBU-12HRFN8-QRE3GW)
I am not able to set heat 16C from HA
If i set target temperature to 16C with remote controller the
HA thermostat displays 16C as target for  for a while, then turns to 17.
AC indoor unit display stays at 16.

**Comment by georgezhao2010** [comment]
Most air conditioners do not support setting the temperature at 16 C but at 17 C, if allowed to set 16 C, these air conditioners will display incorrect temperature.

For compatibility, this integration only allows setting to 17 C
