### ISSUE TITLE
Energy consumption for Midea HBT-A100

### ISSUE THREAD

**Issue by ASIS911** [georgezhao2010/midea_ac_lan#126]
Hello, was wondering if energy consumption can be monitored for Heat Pump Midea HBT-A100 (Device type C3).
I can see energy consumption stats in MSmartHome application, so was thinking that there probably is a way to also get the energy consumption locally.

**Comment by Unwies** [comment]
Many thanks for this great implementation. Nice to see my C3 heatpump now in HA. Would be great to the power measurement too… and be able to add it in energy dashboard. Thx

**Comment by georgezhao2010** [comment]
Fixed in https://github.com/georgezhao2010/midea_ac_lan/commit/9ee1974657db27874c16c4318f250673cc41456e
