### ISSUE TITLE
EVA II PRO Dehumidifier - no tank status

### ISSUE THREAD

**Issue by relaystar** [georgezhao2010/midea_ac_lan#130]
the EVA II PRO WiFi 20L Dehumidifier works with this integration, except that no status of the tank (ie full, not full) is returned.  

The tank status is not available as an attribute on the main (humidifier.<id>_humidifier) entity, nor is it available as a configurable extra entity.  (the only sensor listed there is "current humidity".

**Comment by James3UK** [comment]
This is also missing on the Inventor EVA ION PRO Wi-Fi 20L Dehumidifier ‎EP-WiFi20LBS,
I was also wondering if there were any other sensors like temperature, compressor status, defrost status that could be added.

**Comment by jdvmanen** [comment]
Good afternoon,

Same here for the Midea DF-20DEN7-WF dehumidifier. All functions work (sensors and controls) but the tank indicator (most important to me 😊) isn't.

**Comment by ynsgnr** [comment]
Same for me as well!

**Comment by jonferreira** [comment]
Having the same issue, Tank isn't an option available. Anything we can do to help diagnose this?

**Comment by jdvmanen** [comment]
I've updated the code and added a pull request (#165) to make it available for download. When that is approved by the maintainer of this repository it should work.

**Comment by jdvmanen** [comment]
@georgezhao2010 , can you approve pull request #165 please?

**Comment by davidski** [comment]
It would be really helpful to get the full tank sensor information as well. This is implemented at https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan/blob/0ab6d55dd167b97c88ad90c327e20df310b62eeb/custom_components/midea_dehumidifier_lan/sensor.py#L72-L87

**Comment by James3UK** [comment]
The last commit from @georgezhao2010 is December 2022 so it doesn't look like he's working on this any more.

**Comment by James3UK** [comment]
> I've updated the code and added a pull request (#165) to make it available for download. When that is approved by the maintainer of this repository it should work.

Worked for me thanks, I manually edited the file via the file editor and restarted and was then able to tick the "Tank Status" option for the device to get it to create the entity.

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)

**Comment by davidski** [comment]
Have others applied this update yet? I pulled in the new version and enabled the sensor. My sensor (Midea 50 pt cube dehumidifier) is now showing in "Problem" state while the Midea Air app is showing the tank is not full. I'd expect this to show not in problem state. Even better would be to get the percentage that the Midea Air app is able to poll. 😄
