### ISSUE TITLE
Unavailable every few days(overflowerror: int too big)

### ISSUE THREAD

**Issue by manymuch** [georgezhao2010/midea_ac_lan#132]
First of all, thanks the author for the great job!

I two devices:  AC and heater. Both of them became unavailable every few days. Simply restart the integration fix the issues.
Here is what I found in log that may be relavent:

```
This error originated from a custom integration.

Logger: custom_components.midea_ac_lan.midea.core.device
Source: custom_components/midea_ac_lan/midea/core/device.py:132
Integration: Midea AC LAN (documentation, issues)
First occurred: October 20, 2022, 01:36:31 (31499 occurrences)
Last logged: 11:41:44

[162727724421764] Unknown error OverflowError('int too big to convert')
[192414535960943] Unknown error OverflowError('int too big to convert')
```

**Comment by msmarks** [comment]
+1 #127

**Comment by quyifei** [comment]
I have the same problem.  I have 2 Midea A/C. HA was installed on one orangepi. The A/C closer to the A/C is OK, but the other one became unavailable every night.

**Comment by quyifei** [comment]
It turned out that the IP address of A/C changed that caused the connection problem. Any way to work it out?

**Comment by msmarks** [comment]
@quyifei set static address for A/C in the router

**Comment by quyifei** [comment]
> @quyifei set static address for A/C in the router

@msmarks  Yes it works. Thank you!
