### ISSUE TITLE
Two questions about adding devices

### ISSUE THREAD

**Issue by flyoffacliff** [georgezhao2010/midea_ac_lan#134]
1.	I have 8 devices but the “auto” option only let me add one at a time so now I had to go through the setup wizard 8 times. Now I have 8 instances of the integration installed and only one device on each one. Is there a better way to do this?

2.	Where do the numbers come from in the default entity ID, such as “climate.141xxx000xxx345_climate” (x represents redacted numbers)? It seems some of them are sequential in the order I set up the devices with Midea cloud for the first time. Is it some kind of permanent software registration number? The units that I registered later in the day are also sequential but have a different starting number.
 
Thank you

**Comment by georgezhao2010** [comment]
141xxx000xxx345 is the device id that Midea has fixedly recorded inside your appliance and will not change, so I use it to mark the entity of the device.

For question 1, I don't think there is any need to make any changes.
