### ISSUE TITLE
Can you help to join the new air conditioning launched by midea Hualing? 

### ISSUE THREAD

**Issue by kanissssss** [georgezhao2010/midea_ac_lan#139]
你能帮忙加入midea Hualing推出的新空调吗？目前，您可以使用midea ac lan搜索空调，但无法成功添加。具体型号是WAHIN 50HL1，谢谢，期待您的回复！Can you help to join the new air conditioning launched by midea Hualing? At present, you can use midea ac lan to search for air conditioning, but it cannot be added successfully. The specific model is WAHIN 50HL1, thank you, looking forward to your reply!

**Comment by kanissssss** [comment]
model: KFR-50G/N8HL1
time:2022.10.21

**Comment by kanissssss** [comment]
<img width="983" alt="截屏2022-11-09 15 24 50" src="https://user-images.githubusercontent.com/90088715/200765591-874fee1e-3313-4e17-8859-b92a6cc9198d.png">
<img width="411" alt="截屏2022-11-09 15 25 03" src="https://user-images.githubusercontent.com/90088715/200765604-3ace09b0-4c2d-4767-8511-4b2c69354181.png">

**Comment by kanissssss** [comment]
还有人维护么？

**Comment by kanissssss** [comment]
？

**Comment by georgezhao2010** [comment]
你的问题最终解决了没有？

**Comment by kanissssss** [comment]
没，博主貌似还没能处理这个问题发自我的 iPhone在 2023年8月20日，01:18，George Zhao ***@***.***> 写道：﻿
你的问题最终解决了没有？

**Comment by georgezhao2010** [comment]
> 没，博主貌似还没能处理这个问题发自我的 iPhone在 2023年8月20日，01:18，George Zhao ***@***.***> 写道：﻿ 你的问题最终解决了没有？ —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

换最新版本的也不行吗？

要不你打开midea_ac_lan的调试模式，然后把添加过程记录下来，然后把日志贴出来，看看是怎么造成的。

**Comment by georgezhao2010** [comment]
长时间没回应就算饿了
