### ISSUE TITLE
ECO and Boost mode presets not working

### ISSUE THREAD

**Issue by paradox37** [georgezhao2010/midea_ac_lan#142]
Hello,

It seems that ECO and Boost mode are not working for me. AC will beep, but after a second, preset will return to none since it failed to activate it. My AC is Vivax, but that is just rebranded Midea AC. Toggling display also does not work.

With this integration Boost works, but also not ECO. https://github.com/mac-zhou/midea-ac-py

**Comment by flyoffacliff** [comment]
Same issue here. My newer air handlers do it fine, but most are a slightly older model from like two or three years ago, and they beep and immediately revert back.

**Comment by cash18** [comment]
Same here. I really want to set this presets but actually i can't do it. I have a Clivet Spera EVO 2.0 Box (rebranded by Midea).

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.18](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.18)
