### ISSUE TITLE
Not detecting or able to set MODE for Carrier

### ISSUE THREAD

**Issue by federicokeen** [georgezhao2010/midea_ac_lan#143]
Hello, I've recently installed from HACS and it managed to configure my 2 Carrier aircons. Main temperature control / Power / Swing / Fan Speed works, but setting the mode doesn't (and for some reason it keeps the mode as Dry). 

Is there any information I can provide? I'm on 0.3.15

**Comment by georgezhao2010** [comment]
Enable the debug log for midea_ac_lan, change the mode on app, then send the logs to me.

**Comment by georgezhao2010** [comment]
No response for a long time, closed for a while.
