### ISSUE TITLE
Fahrenheit as opposed to Celsius.....

### ISSUE THREAD

**Issue by SkinnyT81** [georgezhao2010/midea_ac_lan#145]
Is there a way to have the choice to select between displaying the temp on the unit in Fahrenheit as opposed to Celsius?  Digging through some of the code, I've see the TEMPERATURE_CELSIUS and also the HIGH/LOW setpoints are set in Celsius.   Do I just need to change that all manually and with each update or is there a way to do this way some type of selection?

**Comment by flyoffacliff** [comment]
Same question here, I got my sensors to report in Fahrenheit but I had to use custom template code and use virtual sensors basically. The “climate” object does seem to report in Fahrenheit though if that's how I have the global setting for home assistant set. The rounding is a little buggy though sometimes.

**Comment by flyoffacliff** [comment]
Looking through the code, device.py and mesage.py have items for frost protect, but it's not fully implemented for some reason.

**Comment by flyoffacliff** [comment]
__init.py__ imports TEMP_FAHRENHEIT and climate.py imports TEMP_CELSIUS from HA. It doesn't make any sense.

**Comment by flyoffacliff** [comment]
I give up for now. I couldn't figure it out. Even selecting "63" in HA makes the units go to 62.

**Comment by Medic97** [comment]
I assume no one came up with a fix for this?

**Comment by tfolsomnh** [comment]
Any traction on this issue?  This is the best Midea AC integration I have tried thus far.  Excellent control of the primary AC functions.  It's just a shame that the sensors (outside & inside) seem to be stuck in Celsius.  I did look at the code, but its unclear why I can't change the units in the entity details section.

**Comment by patman-cp** [comment]
Similar here, if I change HA to use Fahrenheit, it just goes back to Celsius.

And then the Celsius has a precision with no decimal points, so manually converting it to Fahrenheit only gives me values in 1.8F increments.

**Comment by georgezhao2010** [comment]
Try to fix this in [v0.3.19](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.19).

You can upgrade and see.

**Comment by Medic97** [comment]
Upgraded and tried the latest version. It's showing an F but numbers are still in Celsius. 
<img width="314" alt="Screenshot 2023-09-03 at 3 41 57 PM" src="https://github.com/georgezhao2010/midea_ac_lan/assets/23649478/24f4a229-72b8-433d-bd00-8b02162a0c20">
<img width="313" alt="Screenshot 2023-09-03 at 3 42 01 PM" src="https://github.com/georgezhao2010/midea_ac_lan/assets/23649478/224aa8df-9aec-48e2-9800-00bc1ccc7110">

**Comment by SkinnyT81** [comment]
Mine is showing the same as above.   Previously it was staying set on Fahrenheit, but now is showing the temp in Celsius with an F afterwards.

**Comment by patman-cp** [comment]
Yeah this is worse than it was before for me - I used to be able to see the correct temperature in the Thermostat Card, but now it only shows celsius but says F, and I still can't change the temperature unit of measurement on the page for the sensor (not sure what that page is called).

Is there a way in HACS to switch back to 0.3.18?
