### ISSUE TITLE
Water Heater (E2) - unable to set temp

### ISSUE THREAD

**Issue by Extreme79** [georgezhao2010/midea_ac_lan#147]
Hi.
I installed a comfee water heater, that is fully functional by the app. 
Calling the water_heater.turn_on and off work as expected, changing the appliance state (but no other way to turn it on). 
But seems no way to change temperature: thermostat require climate entity, simple-thermostat accept water_heater domain if forced into it but no control on temperature (probably calling climate set temp and not water_heater domain), manually calling water_heater.set_temperature service also no affect device temperature (service call ok). 
Also open control entity from Device page and trying to change temperature, has no effect (if I change temp on the msmart app, it change on the device entity) 
😭

Home Assistant 2022.11.3
Supervisor 2022.10.2
Frontend 20221108.0 - latest
(all run over an rpi4 in docker)

**Comment by georgezhao2010** [comment]
Please try the temporary solution in #267 and see if it solves your problem.
