### ISSUE TITLE
colmo 中央空调可以识别出来, 但所有操作无效

### ISSUE THREAD

**Issue by jay1943000** [georgezhao2010/midea_ac_lan#148]
![微信图片_20221120014546](https://user-images.githubusercontent.com/1289508/202864400-aedac8b5-d568-49bd-bf6f-9587f999ad83.png)

**Comment by Jonny007x** [comment]
我的美的中央空调也一样,开发者好像润了,已经好久没有更新了

**Comment by dwxiayi** [comment]
> 我的美的中央空调也一样,开发者好像润了,已经好久没有更新了

你这个发言真是令人心寒，你赞助项目了嘛人家就要随叫随到。

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.18](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.18)

**Comment by jay1943000** [comment]
太优秀了,确实可以了,谢谢owner
