### ISSUE TITLE
Changing setpoint changes units to C

### ISSUE THREAD

**Issue by uSlackr** [georgezhao2010/midea_ac_lan#15]
I have three midea ACs and use this integration to monitor and control them.  Any time I change the setpoint temp, the units switch from F to Celsius.  Is there something I need to configure to prevent this?

**Comment by georgezhao2010** [comment]
> I have three midea ACs and use this integration to monitor and control them. Any time I change the setpoint temp, the units switch from F to Celsius. Is there something I need to configure to prevent this?

You mean the temp value is correct and just the units is incorrect?

**Comment by uSlackr** [comment]
Correct

**Comment by uSlackr** [comment]
Let me clarify - the display on the AC changes to C.

**Comment by georgezhao2010** [comment]
> Let me clarify - the display on the AC changes to C.

Displayed on your UI cards of HA or your AC device's LCD?

**Comment by uSlackr** [comment]
The Devices LCD.  Thanks for the fix.  I'll test it out

**Comment by georgezhao2010** [comment]
> The Devices LCD. Thanks for the fix. I'll test it out

Update to [v0.1.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.1.17), see if it solves the problem.

**Comment by uSlackr** [comment]
That works.  When I first looked at them, they were listed as C in the UI.  I made a temp changed and the UI refreshed to F.  AND the LCD stayed in F!
Thank you!

**Comment by georgezhao2010** [comment]
> That works. When I first looked at them, they were listed as C in the UI. I made a temp changed and the UI refreshed to F. AND the LCD stayed in F! Thank you!

could you pls star this repository if you like it, thank you.
