### ISSUE TITLE
Uptate outdoor and indoor temperature sensors

### ISSUE THREAD

**Issue by marcoahp** [georgezhao2010/midea_ac_lan#153]
When AC is on , both sensors works well, but when AC is off, stop uptating, in the phone app I see the real temps.

**Comment by nocin** [comment]
Noticed the same behavior. I'm using the Integration with a Midea Comfee MSAF5-12HRDN8-QE. 
![image](https://user-images.githubusercontent.com/35531968/204153813-e571a7be-0c95-467e-be7b-e18e902f8c9a.png)


If I remember correctly, when using the [homeassistant-midea-air-appliances-lan](https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan) integration, the temperature values looked better.

**Comment by marcoahp** [comment]
> Noticed the same behavior. I'm using the Integration with a Midea Comfee MSAF5-12HRDN8-QE. ![image](https://user-images.githubusercontent.com/35531968/204153813-e571a7be-0c95-467e-be7b-e18e902f8c9a.png)
> 
> If I remember correctly, when using the [homeassistant-midea-air-appliances-lan](https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan) integration, the temperature values looked better.

Yes, the other integration worked better with the temperature sensors, but had other problems. I could't change temperature from the integration. Would be great a combination of working things of both integrations.

**Comment by louispires** [comment]
Strangely my Indoor temperature is always updating, it is the Outdoor temperature that only reports when the Device is ON:

![image](https://user-images.githubusercontent.com/8841644/204789880-14e8c709-91b9-44e2-a099-993ffb55f568.png)
