### ISSUE TITLE
添加美的空调报错：无法连接美的云获取设备关键信息(Token和Key)

### ISSUE THREAD

**Issue by noinlijin** [georgezhao2010/midea_ac_lan#155]
无法连接美的云获取设备关键信息(Token和Key)

**Comment by kanissssss** [comment]
一样 ，我的也不行。。。

**Comment by mroj2333** [comment]
我也有这个问题

**Comment by weiangongsi** [comment]
热水器也不行了，之前还可以

**Comment by psr4** [comment]
我也不行

**Comment by psr4** [comment]
已经解决  
编辑 costom_components/midea_ac_lan/const.py
修改下方参数
MIDEA_DEFAULT_ACCOUNT = '美的美居账号'
MIDEA_DEFAULT_PASSWORD = '美的美居密码'
MIDEA_DEFAULT_SERVER = "cn"

**Comment by kanissssss** [comment]
你好，按照标准修改了，但是添加的时候还是会提示添加设备失败，同时美居的app会提示账号正在登陆，好像是被限制了登陆。这样要如何解决呢？
















在 2023-02-26 00:51:03，"psr4" ***@***.***> 写道：

已经解决
编辑 costom_components/midea_ac_lan/const.py
修改下方参数
MIDEA_DEFAULT_ACCOUNT = '美的美居账号'
MIDEA_DEFAULT_PASSWORD = '美的美居密码'
MIDEA_DEFAULT_SERVER = "cn"

**Comment by zcc0870** [comment]
也碰到了无法添加，token和key在哪里

**Comment by kanissssss** [comment]
你好，按照标准修改了，但是添加的时候还是会提示添加设备失败，同时美居的app会提示账号正在登陆，好像是被限制了登陆。这样要如何解决呢？













在 2023-06-16 16:06:28，"~" ***@***.***> 写道：

你好，按照标准修改了，但是添加的时候还是会提示添加设备失败，同时美居的app会提示账号正在登陆，好像是被限制了登陆。这样要如何解决呢？
















在 2023-02-26 00:51:03，"psr4" ***@***.***> 写道：

已经解决
编辑 costom_components/midea_ac_lan/const.py
修改下方参数
MIDEA_DEFAULT_ACCOUNT = '美的美居账号'
MIDEA_DEFAULT_PASSWORD = '美的美居密码'
MIDEA_DEFAULT_SERVER = "cn"

**Comment by georgezhao2010** [comment]
Midea has changed MSmartHome-API at July，2023

Fixed in [v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)

**Comment by kanissssss** [comment]
你好，已经升级到0.3.17 还是遇到这个问题会在登录的时候，提示美的家居app登录提示的，设备无法添加成功，文件内的账号密码字段叶修改为自己的，麻烦解决下呀发自我的 iPhone在 2023年8月11日，01:33，George Zhao ***@***.***> 写道：﻿
Closed #155 as completed.
