### ISSUE TITLE
Zone curve switch status for heat pump devices does not update

### ISSUE THREAD

**Issue by ricdeblasis** [georgezhao2010/midea_ac_lan#158]
I noticed that the zone curve switch for the heat pump devices does not reflect the actual status selected on the heat pump. However, setting the zone curve from HA is transferred to the machine but its status is not updated on HA. 

Found the bug on the midea/devices/C3/message.py file at lines 82 and 83. The variables self.zone1_curve_state and self.zone2_curve_state should be self.zone1_curve and self.zone2_curve.

I tested the fix on my HA installation and it seems to work fine.

**Comment by matteo80** [comment]
Thanks, now it works.

**Comment by Perfect-Web** [comment]
has this been merged?

**Comment by matteo80** [comment]
No, you can install It and change in Home Assistant with file editor.

**Comment by georgezhao2010** [comment]
> I noticed that the zone curve switch for the heat pump devices does not reflect the actual status selected on the heat pump. However, setting the zone curve from HA is transferred to the machine but its status is not updated on HA.
> 
> Found the bug on the midea/devices/C3/message.py file at lines 82 and 83. The variables self.zone1_curve_state and self.zone2_curve_state should be self.zone1_curve and self.zone2_curve.
> 
> I tested the fix on my HA installation and it seems to work fine.

Thank you @ricdeblasis, I'll fix it.
