### ISSUE TITLE
洗碗机可以接入，但是无法操作运行

### ISSUE THREAD

**Issue by shawnzhou1120** [georgezhao2010/midea_ac_lan#159]
此插件挺好的，很方便的就能将美的的洗碗机接入到HA中，
但是接入后发现，大部分都是sensor，只能读取状态，只有一个打开电源 和 童锁是 可操作和控制的。
但是其其他功能均不能操作，比如 **_运行程序_** 这个很重要的功能，还有**_程序设置_** 这个功能。
如果只是打开电源，而不能让他运行洗碗程序，其用途非常有限。

其实我主要的目的即设置一个 实体按钮，将实体按钮接入HA，然后通过按一次按钮，即设置自动化XXX时候，洗碗机开始自动进行洗碗。（主要是洗碗时噪音大，影响客厅生活，但对卧室影响小，所以我一般设置预约到凌晨2点进行洗碗，但每次要拿手机app预约很麻烦）。

希望插件能增加让洗碗机执行洗碗程序的功能。

**Comment by georgezhao2010** [comment]
另外你是不是想简单了，至少洗碗机里有碗你才会半夜去洗吧？如果不设置，而无脑执行半夜2点洗碗，真的好吗？要设置今天半夜两点洗不洗，你还不是得掏出手机设一次。

**Comment by vingores** [comment]
Было бы не плохо использовать режимы у меня предлагает эсо а хотелось бы стандартный

**Comment by shawnzhou1120** [comment]
> 另外你是不是想简单了，至少洗碗机里有碗你才会半夜去洗吧？如果不设置，而无脑执行半夜2点洗碗，真的好吗？要设置今天半夜两点洗不洗，你还不是得掏出手机设一次。

其实需求很简单，在HA/NR做一个自动化，这个自动化默认是 禁用状态， 然后在洗碗机旁边贴一个小米按钮，每次放完碗后，点一下按钮，激活洗碗那条自动化（自动化设置为晚上2点洗碗），即可。再设置每天早上6点，自动禁用自动化即可。
