### ISSUE TITLE
Can't change target temperature 

### ISSUE THREAD

**Issue by screem20056** [georgezhao2010/midea_ac_lan#16]
Really like the integration the issue that started after the last update i can not change the target temperature it stays at 24th even with eco mode off 
I tried to lower or raise temperature both are not working 
Thanks

**Comment by georgezhao2010** [comment]
> Really like the integration the issue that started after the last update i can not change the target temperature it stays at 24th even with eco mode off I tried to lower or raise temperature both are not working Thanks

Any exception or someting in logs?

**Comment by georgezhao2010** [comment]
> Really like the integration the issue that started after the last update i can not change the target temperature it stays at 24th even with eco mode off I tried to lower or raise temperature both are not working Thanks

Update to [v0.1.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.1.17), see if it solves the problem.

**Comment by screem20056** [comment]
Worked as before
Thank you 😊
