### ISSUE TITLE
洗碗机默认实体不足问题

### ISSUE THREAD

**Issue by kerncoola** [georgezhao2010/midea_ac_lan#166]
我使用的是布谷洗碗机，默认的实体只有三个，童锁、电源、保管。
<img width="391" alt="iShot2022-12-18 10 41 53" src="https://user-images.githubusercontent.com/13283995/208278829-ddd54c25-6d23-4c59-a45b-0fe0e07495a6.png">

文档中「额外生成实体」列明了很多其它实体，不知道是我的洗碗机不支持还是需要额外添加，没有找到相关资料。

另外还有一个干燥的开关，我这台每次都要手动关闭干燥，很多时候用不到干燥功能，想着用HA设置一个启动后自动关闭干燥功能。
![IMG_4936](https://user-images.githubusercontent.com/13283995/208278886-38bf3d54-2ff0-4342-bd80-4025d5b5e021.PNG)

**Comment by georgezhao2010** [comment]
传感器的下拉列表中可以找到更多传感器实体
