### ISSUE TITLE
自动化部分能否实现温度设定？

### ISSUE THREAD

**Issue by fdsasdfddsa** [georgezhao2010/midea_ac_lan#17]
请问自动化部分能否实现调节温度的功能？似乎只能通过手动来调节，而在自动化设置的动作里似乎没有温度控制的接口。
正在学习HA，可能是我还不会使用的缘故，如果有误还请见谅

**Comment by georgezhao2010** [comment]
> 请问自动化部分能否实现调节温度的功能？似乎只能通过手动来调节，而在自动化设置的动作里似乎没有温度控制的接口。 正在学习HA，可能是我还不会使用的缘故，如果有误还请见谅

HA的标准服务,climate.set_temperatire

**Comment by fdsasdfddsa** [comment]
找到了，之前一点头绪都没有。非常感谢提示！

**Comment by fdsasdfddsa** [comment]
> > 请问自动化部分能否实现调节温度的功能？似乎只能通过手动来调节，而在自动化设置的动作里似乎没有温度控制的接口。 正在学习HA，可能是我还不会使用的缘故，如果有误还请见谅
> 
> HA的标准服务,climate.set_temperatire

找到了，之前一点头绪都没有。非常感谢提示！
