### ISSUE TITLE
Template error: float got invalid input 'unavailable' when rendering template

### ISSUE THREAD

**Issue by flyoffacliff** [georgezhao2010/midea_ac_lan#172]
Sometimes one or more of my units will drop offline until HA is restarted, but the official app continues to work. Here are some log snippets from "journalctl".
[ID] is the redacted ID of the unit.

This one is when the problem starts:

Dec 29 18:09:29 homeassistant homeassistant[344]: 2022-12-29 18:09:29.487 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (( states("sensor.[ID]_indoor_temperature") | float ) * 1.8) +32 }}' but no default was specified') while processing template 'Template("{{ (( states("sensor.[ID]_indoor_temperature") | float ) * 1.8) +32 }}")' for attribute '_attr_native_value' in entity 'sensor.family_room_temperature'

And then this happens every 5 seconds until the system is restarted:

Dec 29 20:32:04 homeassistant homeassistant[344]: 2022-12-29 20:32:04.573 ERROR (Air Conditioner) [custom_components.midea_ac_lan.midea.core.device] [[ID]] Unknown error OverflowError('int too big to convert')

**Comment by georgezhao2010** [comment]
Fixed in v0.3.17
