### ISSUE TITLE
美的管线机传感器获取数据失败

### ISSUE THREAD

**Issue by zjl3265** [georgezhao2010/midea_ac_lan#173]
型号：MG908-R
可以搜索到管线机，但是无法获取数据：
传感器
Filter1 Available Days
未知
Filter1 Life Level
未知
Filter2 Available Days
未知
Filter2 Life Level
未知
Filter3 Available Days
未知
Filter3 Life Level
未知
In TDS
未知
Out TDS
未知
Water Yield
未知

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.18](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.18)
