### ISSUE TITLE
无法连接美的云获取设备关键信息(Token和Key)

### ISSUE THREAD

**Issue by weiangongsi** [georgezhao2010/midea_ac_lan#180]
连接美的热水器，通过ip可以发现新设备，点击提交出现提示‘无法连接美的云获取设备关键信息(Token和Key)’。

**Comment by psr4** [comment]
编辑 costom_components/midea_ac_lan/const.py
修改下方参数
MIDEA_DEFAULT_ACCOUNT = '美的美居账号'
MIDEA_DEFAULT_PASSWORD = '美的美居密码'
MIDEA_DEFAULT_SERVER = "cn"

**Comment by 907739769** [comment]
> 编辑 costom_components/midea_ac_lan/const.py 修改下方参数 MIDEA_DEFAULT_ACCOUNT = '美的美居账号' MIDEA_DEFAULT_PASSWORD = '美的美居密码' MIDEA_DEFAULT_SERVER = "cn"

问题解决了 谢谢
