### ISSUE TITLE
洗衣机的剩余时间传感器无法被home kit识别只能在HA里查看

### ISSUE THREAD

**Issue by SeanFxs** [georgezhao2010/midea_ac_lan#182]

**Comment by SeanFxs** [comment]
使用本插件我可以正常的在HA里看到洗衣机和烘干机的progess和剩余时间作为sensor出现，显示内容也正常，但是尝试使用自带的komekit插件转换到home app 里面时就不能正常识别出来，不知道是不是暂时不支持？

**Comment by felixtsu** [comment]
配合scriptable可以写出来小组件 https://gist.github.com/felixtsu/15c62e968beea820a447bddb1dd84e69

**Comment by georgezhao2010** [comment]
HomeKit只支持有限类型的传感器，如温湿度、空气质量等，不是什么传感器都能转接到HomeKit中
