### ISSUE TITLE
Not an issue: confirmed working perfectly for ProBreeze PB-15 

### ISSUE THREAD

**Issue by SamJongenelen** [georgezhao2010/midea_ac_lan#183]
Hey,

I just wanted to say I found this addon on a tip somewhere, and worked flawlessly with my (European rebrand?) ProBreeze PB-15 model.
Only thing is that I wasn't able to find this repo because it doesn't have the brand listed. 
I didn't just want to create a PR and update the text without the 'brand icon', and it obviously also falls under 'and more'. 

tl;dr; Without mentioning the brand (ProBreeze) this repo is not found on search engines. Any ideas how to improve this?

**Comment by georgezhao2010** [comment]
Thank you @SamJongenelen
