### ISSUE TITLE
美的智能门锁实现起来复杂不或者麻烦大神给个思路想弄懂怎么回事，谢谢

### ISSUE THREAD

**Issue by manpeter** [georgezhao2010/midea_ac_lan#186]
家里搞的美的的智能设备，从门锁到传感器就算搭了HA也没用，全要换了才行，想求一下解决方案

**Comment by georgezhao2010** [comment]
并不太能准确理解你的意思，你可以上[瀚思彼岸论坛](https://bbs.hassbian.com)提问看看
