### ISSUE TITLE
Frequently unavailable BUG

### ISSUE THREAD

**Issue by screem20056** [georgezhao2010/midea_ac_lan#19]
Really appreciate the contusions support.
With the new update the device go unavailable frequently every 2-3 min and online again after refreshing entity config.
Logger: root
Source: helpers/entity.py:660
First occurred: 9:21:11 PM (1 occurrences)
Last logged: 9:21:11 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/midea_ac_lan/state_manager.py", line 71, in run
    self.enable_devices(False)
  File "/config/custom_components/midea_ac_lan/state_manager.py", line 133, in enable_devices
    self.update_all({"available": enable})
  File "/config/custom_components/midea_ac_lan/state_manager.py", line 139, in update_all
    update(updates)
  File "/config/custom_components/midea_ac_lan/midea_entity.py", line 136, in update_state
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 660, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'add_job'
This error i found in the logs
Regards

**Comment by georgezhao2010** [comment]
> Really appreciate the contusions support. With the new update the device go unavailable frequently every 2-3 min and online again after refreshing entity config. Logger: root Source: helpers/entity.py:660 First occurred: 9:21:11 PM (1 occurrences) Last logged: 9:21:11 PM
> 
> Uncaught thread exception Traceback (most recent call last): File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner self.run() File "/config/custom_components/midea_ac_lan/state_manager.py", line 71, in run self.enable_devices(False) File "/config/custom_components/midea_ac_lan/state_manager.py", line 133, in enable_devices self.update_all({"available": enable}) File "/config/custom_components/midea_ac_lan/state_manager.py", line 139, in update_all update(updates) File "/config/custom_components/midea_ac_lan/midea_entity.py", line 136, in update_state self.schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 660, in schedule_update_ha_state self.hass.add_job(self.async_update_ha_state(force_refresh)) AttributeError: 'NoneType' object has no attribute 'add_job' This error i found in the logs Regards

what's your HA version?

**Comment by screem20056** [comment]
> > Really appreciate the contusions support. With the new update the device go unavailable frequently every 2-3 min and online again after refreshing entity config. Logger: root Source: helpers/entity.py:660 First occurred: 9:21:11 PM (1 occurrences) Last logged: 9:21:11 PM
> > Uncaught thread exception Traceback (most recent call last): File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner self.run() File "/config/custom_components/midea_ac_lan/state_manager.py", line 71, in run self.enable_devices(False) File "/config/custom_components/midea_ac_lan/state_manager.py", line 133, in enable_devices self.update_all({"available": enable}) File "/config/custom_components/midea_ac_lan/state_manager.py", line 139, in update_all update(updates) File "/config/custom_components/midea_ac_lan/midea_entity.py", line 136, in update_state self.schedule_update_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 660, in schedule_update_ha_state self.hass.add_job(self.async_update_ha_state(force_refresh)) AttributeError: 'NoneType' object has no attribute 'add_job' This error i found in the logs Regards
> 
> what's your HA version?

Core 2022.7.2

**Comment by georgezhao2010** [comment]
> > > Really appreciate the contusions support. With the new update the device go …
> Core 2022.7.2

It seems I can’t fix anything currently. Let’s keep on monitoring. Try to ping AC in your HA to see if connection is well.

**Comment by screem20056** [comment]
Thanks
