### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by GoodLug** [georgezhao2010/midea_ac_lan#190]
Yesterday evening, when I was nowhere near anything to do with it, midea_ac_lan logged:

[custom_components.midea_ac_lan.midea.core.device] [device_id] Connection error

and has been broken ever since.

There is no other information in the log, making this error message pretty useless - I already know there is a connection error, because nothing shows up in Home Assistant.

Any ideas anyone? Has anyone else had the same thing happen?

**Comment by javerro-tech** [comment]
I have the same issue. I think it started happening after update to 2023.3.1

**Comment by GoodLug** [comment]
> I have the same issue. I think it started happening after update to 2023.3.1

I think it may be because by default HA and the Midea controller have dynamic IP addressing. Try setting static IP addresses, you should be able to do it in your router, which is what I did, and it seems to have fixed the problem.  When you first log in to your router, you will also be able to see if the IP addresses have indeed been changed. If you can't do it via your router, I believe there are some rather complicated CLI routines you can use to achieve the same end.

**Comment by georgezhao2010** [comment]
Right， you should set a static ip for your appliance in your router.
