### ISSUE TITLE
为什么静音模式那些开关不能用

### ISSUE THREAD

**Issue by DreamMaoMao** [georgezhao2010/midea_ac_lan#194]
![image](https://user-images.githubusercontent.com/30348075/230526320-1379ca34-ce2d-4048-b5c6-fb3dcb2ca488.png)

**Comment by georgezhao2010** [comment]
你能否提供进一步的信息？你这信息太简单了些，完全不知道你说什么

**Comment by DreamMaoMao** [comment]
打扰了  我换了其他版本的解决了
