### ISSUE TITLE
Can you please add Midea microwave oven and electric oven

### ISSUE THREAD

**Issue by leihuashan** [georgezhao2010/midea_ac_lan#195]
I have two household appliances of Midea, one is Midea microwave oven (model X3-233A) and the other is Midea electric oven (model PT4012W). Both of them are smart household appliances that can be connected to Midea Merfix APP, but cannot be connected to homeassistant. Can you help me add these two devices?
![85b599dbae07bdc272e1844f014fa03](https://user-images.githubusercontent.com/101453877/230690131-68ee962e-225d-45f8-875a-1d5589f166c1.png)

**Comment by lizaoreo** [comment]
I'd like to see this as well.

**Comment by georgezhao2010** [comment]
Microwave oven and electric oven was supported in [v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)
