### ISSUE TITLE
Can not install current version HAOS

### ISSUE THREAD

**Issue by aoakeley** [georgezhao2010/midea_ac_lan#199]
I just purchased a Toshiba portable AC with wifi - RAC-PT1412JVWRU connected to wi-fi with the Toshiba NA app.

Attempting to install integration receive error " This integration does not support configuration via the UI.  If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

![image](https://user-images.githubusercontent.com/23560263/232341146-f1e7b3d2-9264-4d9b-bbb7-b619a24fa998.png)

No pending updates: 

Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.1 - latest

**Comment by darryldeklerk** [comment]
Same issue

**Comment by fharper** [comment]
I have the same problem. Will try to install manually, but if anyone found a solution, please share.

**Comment by fharper** [comment]
Added it manually by searching for it in HACS, and worked well.
