### ISSUE TITLE
Problem for Protocol Version 2

### ISSUE THREAD

**Issue by shulkx** [georgezhao2010/midea_ac_lan#2]
Hi George,
For protocol version 2, it seems that the _token and _key are optional which will be empty while importing.
This will encounter a problem in function DeviceManager (state_manager.py) for following 2 codes:
`self._token = bytearray.fromhex(token)`
`self._key = bytearray.fromhex(key)`

Here is the log I have when importing one of the V2 AC:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/midea_ac_lan/__init__.py", line 27, in async_setup_entry
    dm = DeviceManager(device_id, host, port, token, key, protocol, model)
  File "/config/custom_components/midea_ac_lan/state_manager.py", line 45, in __init__
    self._token = bytearray.fromhex(token)
TypeError: fromhex() argument must be str, not None`

**Comment by georgezhao2010** [comment]
> Hi George, For protocol version 2, it seems that the _token and _key are optional which will be empty while importing. This will encounter a problem in function DeviceManager (state_manager.py) for following 2 codes: `self._token = bytearray.fromhex(token)` `self._key = bytearray.fromhex(key)`
> 
> Here is the log I have when importing one of the V2 AC: `Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/midea_ac_lan/__init__.py", line 27, in async_setup_entry dm = DeviceManager(device_id, host, port, token, key, protocol, model) File "/config/custom_components/midea_ac_lan/state_manager.py", line 45, in __init__ self._token = bytearray.fromhex(token) TypeError: fromhex() argument must be str, not None`

Thank you for your works and reporting, I'll have a look at it.

**Comment by georgezhao2010** [comment]
Fixed in [f942c19](https://github.com/georgezhao2010/midea_ac_lan/commit/f942c1971c3cbec65752766e945b67ba163eacb6)
