### ISSUE TITLE
小天鹅洗衣机长时间运行后就无法同步状态信息

### ISSUE THREAD

**Issue by cloudzhao9** [georgezhao2010/midea_ac_lan#202]
每次重启完HA后都是好的，但运行1-2天后就没法同步了

**Comment by ywwzwb** [comment]
我也是，洗衣机过几天就掉线了，删除设备重新添加又可以继续用。但是空调就不行。

**Comment by xmzhangya** [comment]
我也是这个情况，已经设置为固定ip，过一段时间就不能获取到洗衣机状态。但是在官方app和路由后台看设备都是在线的。然后只能通过对设备重载（倒也不用删了重新添加）就能恢复正常一段时间。

**Comment by liupeng1135** [comment]
我日常连接两台华凌N8HE1空调，设备连接几周后变为不可用，需重新加载集成才可用，应该也是一类问题

**Comment by georgezhao2010** [comment]
有一个导致连接会断掉的错误已经在v0.3.17修正

其它可能的情况就是你应该设置静态IP省得IP变化
