### ISSUE TITLE
美的饮水机

### ISSUE THREAD

**Issue by zzhhzt** [georgezhao2010/midea_ac_lan#206]
家用大桶水饮水机，能正常连接，就是传感器数据都获取不到

只想取得饮水数据

**Comment by georgezhao2010** [comment]
由于美的饮水机/净水机/水吧机等都归到了一个门类下，所以子型号非常庞杂，协议也非常混乱。

你可以把你的设备ID及SN发送到邮箱[georgezhao75@gmail.com](mailto:georgezhao75@gmail.com)，看看有没有机会。

**Comment by georgezhao2010** [comment]
超过两周没有信息更新，暂时关闭。

关于ED设备的更多支持，已于0.3.19-beta2中实现。
