### ISSUE TITLE
所连接设备一段时间后变为不可用，需重载集成

### ISSUE THREAD

**Issue by liupeng1135** [georgezhao2010/midea_ac_lan#207]
日常连接两台华凌N8HE1空调，设备连接几周后变为不可用，需重新加载集成，希望解决此问题

**Comment by liupeng1135** [comment]
此问题不是个例，论坛里也有反映https://bbs.hassbian.com/thread-19442-1-1.html

**Comment by Mayun6699** [comment]
是的，我这边也遇到这种情况很频繁

**Comment by gucong3000** [comment]
我的三台同型号的美的空调也先后遇到了相同问题，几次跟踪后初步排查情况如下：
1. 不在路由器绑定IP地址，此问题迟早出现。
2. 故障出现时，文件`~/.homeassistant/.storage/core.config_entries`中存储的IP地址是错误的，实测发现修改正确后重启hass可排除故障。
3. 故障出现时，这个错误的IP正好被别的设备占用了，这条有可能是该故障触发的必要条件。
4. 搜索发现，`midea_ac_lan`不会记录设备的mac地址，盲猜是作者未处理程序所记录IP地址的使用设备在线，但无法通信的边界情况。

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/1171691/f58ffa1c-0976-4ab1-8889-825753ca71e8)

**Comment by poseidon2750** [comment]
我已经绑定空调的IP和mac地址，仍然很频繁出现这种状况
家里多台空调轮番失联，每次都需要重载

**Comment by huelsgp27** [comment]
+1

**Comment by xunqing** [comment]
在log中出现下列错误
2023-07-05 17:14:48.522 ERROR (客厅空调) [custom_components.midea_ac_lan.midea.core.device] [211106235787676] Unknown error OverflowError('int too big to convert')

**Comment by buzhuiwen** [comment]
请问你的能耗传感器Air Conditioner Current Energy Consumption有数据吗，我的n8he1 pro当日耗电一直都是0，累计耗电倒是一直在走

**Comment by liupeng1135** [comment]
我的n8he1没有能耗传感器

发自我的iPhone

**Comment by georgezhao2010** [comment]
两种情况会导致设备失联问题，

第一种是未为空调设置静态IP地址，导致IP地址在集成配置之后有变动
第二种是一个错误引起的，一定时间之后会导致某个数字溢出，已经在[v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)中修复

**Comment by liupeng1135** [comment]
谢谢，我回去更新下试试。
