### ISSUE TITLE
美的空调在homekit中温度显示错误，居然显示77°

### ISSUE THREAD

**Issue by Gerry161** [georgezhao2010/midea_ac_lan#208]
美的空调通过Midea AC LAN接入HAC，通过HOMEKIT bridge接入苹果“家庭”，在家庭中，空调温度显示错误。 
空调温度都77°了

我试过，不是摄氏度，华氏度问题，选择摄氏度，华氏度都没变化
 

在HAC中温度是正常的

到了homekit家庭中就不正常了，我试过用siri下指令，把空调温度调整为26°，空调正常调整为26度，但手机就显示85°

有没有高手知道怎么解决？

图片请看https://bbs.hassbian.com/thread-21453-1-1.html

**Comment by matato123** [comment]
你这个可能是显示的华氏度 调整一下

**Comment by georgezhao2010** [comment]
使用的iOS设备，设置中有温度单位设置，如果设置成了华氏度，就会出现此问题。

请自行修改相关设置
