### ISSUE TITLE
美的电饭锅，可以利用传感器来实现定时煮饭功能吗？

### ISSUE THREAD

**Issue by RyanLu99** [georgezhao2010/midea_ac_lan#211]
[image](https://github.com/georgezhao2010/midea_ac_lan/assets/53104358/4d33e8ec-76b5-4b8f-a98a-3b1b2d8ce078)
如何来改变传感器的数值，借此不利用官方app实现定时煮饭功能

**Comment by georgezhao2010** [comment]
可以参阅 #246, 说明了我为什么暂时不做电饭锅/烤箱/洗衣机/电饭锅等电器的控制功能。

本ISSUE暂时关闭，如果以后有机会，也许会加上他们的控制功能。
