### ISSUE TITLE
Device suddenly not tmehr set up

### ISSUE THREAD

**Issue by RudiPohlen** [georgezhao2010/midea_ac_lan#213]
I have an air conditioner with 2 indoor units. In both of them a WLAN stick "Nethome Plus EU-OSK103" is installed. Until a few weeks ago, I could also access and control both devices with HomeAssistant with the Midea AC LAN integration.
At some point, one of the indoor devices went bye-bye and since then can no longer be connected to HA.
I go to Settings, Integrations, Midea AC LAN and click on Add entry. At "Add new appliance" I select Auto and click on Submit. When asked if I want to search for new devices, I click Submit again. Then it searches for a while and shows me a device "Ait Conditioner". And yes, this is my device, which does not want to be connected.
I click on submit again. Then it searches for a while and only "Can't connect to appliance" appears.
Which I have already tried.
Deleted the integration and removed it from HACS and reinstalled it. I can then find and log in all the appliances again, but still not this one.
Adding it manually causes the same problem.
I have installed the integration "Midea Ait Appliances (LAN), since I have a NetHome or MSmartHome account and both devices are also there and controllable, unfortunately also without success.
The app MAsmartHome can find the device without problems, provides me with all the data and everything is controllable. Only the integration in HA does not like more.

**Comment by RudiPohlen** [comment]
Here is the debug protocol. The device in question is the 144036023280225
[home-assistant_midea_ac_lan_2023-06-12T10-01-01.294Z.log](https://github.com/georgezhao2010/midea_ac_lan/files/11721149/home-assistant_midea_ac_lan_2023-06-12T10-01-01.294Z.log)

**Comment by RudiPohlen** [comment]
For all those who also have such a problem. Today my new router arrived and I have set up all devices again. And lo and behold, even the air conditioner could be integrated into Home Assistant again without any problems.

**Comment by georgezhao2010** [comment]
I had the same problem before and checked the reason is that some devices only allow few connections at the same time, maybe you have too many connections from other apps or integrations?

**Comment by georgezhao2010** [comment]
I'll close this issue unless you have more helpful information. If there is any progress you can reopen it and let me know.
