### ISSUE TITLE
Midea Airstill Energy Sensor Issue

### ISSUE THREAD

**Issue by JuliusOdian** [georgezhao2010/midea_ac_lan#214]
I get the following error message in Home Assistant regarding the power consumption sensor of a Midea Airstill 12000BTU AC. Model number: MSFAAU-12HRFN8 (inside) and MOX230-12HFN8 (outside)

The error is:
Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:405

Entity sensor.150633093051923_total_energy_consumption from integration midea_ac_lan has state class total_increasing, but its state is not strictly increasing. Triggered by state 35.0 (35.64) with last_updated set to 2023-06-15T12:24:07.058056+00:00. Please report it to the custom integration author.

The following is the power consumption entity graphed and you can see small dips in what should be a continuously increasing quantity.  
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/83136811/69629300-62be-49f4-8c2a-31dce5f4b12b)

**Comment by georgezhao2010** [comment]
Apart from this bug, is total_energy_consumption basically accurate numerically?

**Comment by georgezhao2010** [comment]
Added more power consumption analysis method  in [v0.3.19](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.19).

you can try diffrent method and see .

https://github.com/georgezhao2010/midea_ac_lan/blob/master/doc/AC.md#customize
