### ISSUE TITLE
新风开关无法静音

### ISSUE THREAD

**Issue by dsl888** [georgezhao2010/midea_ac_lan#219]
远程控制可以使用prompt_tone参数控制是否有蜂鸣按键音，对其他功能都有效，但是新风的开关却不行，怎么设置都有蜂鸣器声，希望大佬解决

**Comment by georgezhao2010** [comment]
你手机App中是否能对新风控制静音？

**Comment by dsl888** [comment]
Hi 你好:


App里面新风和其他温度等一样的，如果关闭了声音，则新风和温度等控制都静音，如果开启了声音，就都有声音
| |
窦书理
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | George ***@***.***> |
| 发送日期 | 2023年08月19日 12:55 |
| 收件人 | georgezhao2010/midea_ac_lan ***@***.***> |
| 抄送人 | dsl888 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [georgezhao2010/midea_ac_lan] 新风开关无法静音 (Issue #219) |

你手机App中是否能对新风控制静音？

**Comment by georgezhao2010** [comment]
> Hi 你好: App里面新风和其他温度等一样的，如果关闭了声音，则新风和温度等控制都静音，如果开启了声音，就都有声音 | | 窦书理 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | George ***@***.***> | | 发送日期 | 2023年08月19日 12:55 | | 收件人 | georgezhao2010/midea_ac_lan ***@***.***> | | 抄送人 | dsl888 ***@***.***>, Author ***@***.***> | | 主题 | Re: [georgezhao2010/midea_ac_lan] 新风开关无法静音 (Issue #219) | 你手机App中是否能对新风控制静音？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我先确认一下你是空调内置新风吧？把你设备的SN（可以在添加设备处Just list Appliances找到）发到我邮箱georgezhao75@gmail.com，带上你的issue编号219.一起发给我

**Comment by georgezhao2010** [comment]
较长时间没有进一步信息，该issue关闭，如有需要再重开。
