### ISSUE TITLE
Unknown error OverflowError

### ISSUE THREAD

**Issue by misiuplus** [georgezhao2010/midea_ac_lan#221]
Hi, I have error, sometimes works fine:
Logger: custom_components.midea_ac_lan.midea.core.device
Source: custom_components/midea_ac_lan/midea/core/device.py:316
Integration: Midea AC LAN ([documentation](https://github.com/georgezhao2010/midea_ac_lan), [issues](https://github.com/georgezhao2010/midea_ac_lan/issues))
First occurred: 22:58:52 (17 occurrences)
Last logged: 23:00:12
[142936511754902] Unknown error OverflowError('int too big to convert')

How to fix it?

From HA:
Air Conditioner 00000Q1A(8)

In real:
Versu Pure X 3,5 kW

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)
