### ISSUE TITLE
美的理想家二代，净水器不能用吗？

### ISSUE THREAD

**Issue by adingtao11** [georgezhao2010/midea_ac_lan#222]
发现不了设备。可以提供美居APP账号，感谢开发者

**Comment by georgezhao2010** [comment]
如果是“ED”代号的净水器，是支持的。发现不了设备也可能是不在一个网段什么的原因，你用指定IP的方式是否可行呢？

**Comment by georgezhao2010** [comment]
超过两周没有信息更新，暂时关闭。

关于ED设备的更多支持，已于0.3.19-beta2中实现。
