### ISSUE TITLE
Please add AC Gear [value] option

### ISSUE THREAD

**Issue by maciey** [georgezhao2010/midea_ac_lan#224]
Please add to integration (if possible) enabling modes: Gear 50/70%   

Currently only ECO mode is possible

**Comment by georgezhao2010** [comment]
> Please add to integration (if possible) enabling modes: Gear 50/70%
> 
> Currently only ECO mode is possible

See this [set_ac_fan_speed](https://github.com/georgezhao2010/midea_ac_lan/blob/master/doc/AC.md#midea_ac_lanset_ac_fan_speed)
