### ISSUE TITLE
添加的空调不知道什么原因总是变为不可用状态

### ISSUE THREAD

**Issue by Uiisland** [georgezhao2010/midea_ac_lan#225]
添加的空调不知道什么原因总是变为不可用状态

**自己解决办法**
**路由器给空调设置固定ip**

我自己是把所有美的的设备都在路由器里直接绑定了静态ip，从我提这个问题到现在还没出现过 不可用的状态，感觉是ha的问题，因为我也有一台小米的空调，也总是变为不可用

**Comment by huelsgp27** [comment]
+1

**Comment by yumengbai** [comment]
同问，这个解决了吗

**Comment by github410117** [comment]
+1,这个怎么解决啊

**Comment by Uiisland** [comment]
> 同问，这个解决了吗

我自己是把所有美的的设备都在路由器里直接绑定了静态ip，从我提这个问题到现在还没出现过 不可用的状态，感觉是ha的问题，因为我也有一台小米的空调，也总是变为不可用

**Comment by Gaoyunhao** [comment]
同问，每次都手动重载一下，很麻烦。

**Comment by oopuuu** [comment]
这个问题有啥好解决方案吗，我也遇到

**Comment by georgezhao2010** [comment]
空调是否设置了固定IP？

**Comment by Uiisland** [comment]
> 空调是否设置了固定IP？

一开始没有，后面设置了固定ip就没出现这个问题了

**Comment by zk1204** [comment]
我设置固定ip还是不是出了鬼了

**Comment by georgezhao2010** [comment]
> 我设置固定ip还是不是出了鬼了

见不见鬼，你贴个调试日志出来就知道了

**Comment by georgezhao2010** [comment]
No more details, closed
