### ISSUE TITLE
Card don't update if value were changed with ir-remote o mideaApp

### ISSUE THREAD

**Issue by valeriotaccardo** [georgezhao2010/midea_ac_lan#226]
Card don't update if value of AC were changed with ir-remote o mideaApp. the values ​​change only when changed by Home Assistant

**Comment by diybateriaslifepo4** [comment]
The same thing happens to me, a while ago I opened an issue commenting that the refresh time was too slow, approximately 60 seconds to update, now it happens to me that many times it doesn't even update, even turning on the air from the remote and the integration never show that it has been turned on, therefore home assistant does not know that it is turned on and it is not useful for my automations.

**Comment by georgezhao2010** [comment]
Show me your debug logs.

**Comment by georgezhao2010** [comment]
No further information has been received for more than two weeks.

The issue will be closed.
