### ISSUE TITLE
Lamborghini AC: Disable LED no longer working

### ISSUE THREAD

**Issue by tommy2d** [georgezhao2010/midea_ac_lan#228]
Previously, I was able to disable the LED temperature display using this integration. No I only get the confirmation beep sound when I send the command, but the led display stays on. Is there anything I can do to help debug this problem?

**Comment by FancyNerd92** [comment]
I have the same problem with mine Bosch ACs! Please Fix it!
I want make an automation for after midnight turning off the led panel because I have problem with any tiny light when I sleep...

**Comment by giannoug** [comment]
On Carrier ACs, Air Conditioner Screen Display switch does nothing at all, not even beep.

**Comment by v1k70rk4** [comment]
I am experiencing this with both my Midea Xtreme Save Pro and Midea Breezless+ air conditioners. They do not turn off the display, but if I turn it off with the remote, then the switch.<<ID>>_screen_display constantly turns on and off about every second until I turn it back on.

So, it does recognize the fact of turning off.

**Comment by georgezhao2010** [comment]
This integration provides two different switches to control display, if none of them work, then it may be that your air conditioner does not support controlling the display over the network.

You can find these switches in integrations->Midea AC LAN->configure->Controls.

**Comment by v1k70rk4** [comment]
In the meantime, a LED switch has appeared in the new MSmartHome application, and when I try to switch it there, it says to use the remote control because my device does not support it. :(

**Comment by giannoug** [comment]
>This integration provides two different switches to control display, if none of them work, then it may be that your air conditioner does not support controlling the display over the network.

Which are the two switches? I can see "Screen Display" which seems to be updated based on the screen status (e.g. turns off when device is turned off) but doesn't control the display. I can also see "Prompt Tone" which turns the beep on and off (but not the display).

**Comment by FancyNerd92** [comment]
There are not have 2 switches for display light just one and not working for me.

**Comment by tommy2d** [comment]
> There are not have 2 switches for display light just one and not working for me.

Same situation over here.

**Comment by georgezhao2010** [comment]
Can you control the LED from the mobile app, or is it only controllable by the ir-remoter? If it can be controlled by an app, please provide your device model information (It can be found in Settings -> Devices & Services -> Midea AC LAN -> Devices -> Device Info).

**Comment by matteos1** [comment]
> Previously, I was able to disable the LED temperature display using this integration. No I only get the confirmation beep sound when I send the command, but the led display stays on. Is there anything I can do to help debug this problem?

How did you recognize Lamborghini AC to the Midea integration?What are the ports to configure? l

**Comment by georgezhao2010** [comment]
Can you control the led display from App, or just support control from IR remote?

If it can’t be controlled from the App, then it’s very likely that it doesn’t support network control for this at all.

**Comment by tommy2d** [comment]
I really thought that I was previously able to do this through home assistant, but given that the vendor’s app does not support it either I might be mistaken.

**Comment by georgezhao2010** [comment]
merge into #129
