### ISSUE TITLE
是否可以加入云端控制

### ISSUE THREAD

**Issue by 609293964** [georgezhao2010/midea_ac_lan#229]
有几台美的空调在其他房子，无法通过局域网寻找添加，现在通过Midea Air Conditioner via eWeLink Cloud在易微联中添加，功能也都正常，但是易微联的功能和传感器数据没有美的美居准确，所以还是期待下云端控制

**Comment by Mibore99** [comment]
同希望考虑加入云端控制，homeassistant和设备不在同一个网段，发现不了设备。

**Comment by georgezhao2010** [comment]
云端控制暂时不考虑了，毕竟这个集成叫做LAN，重点就是本地控制。

只能看看以后会不会有空做。
