### ISSUE TITLE
【下载安装问题】群晖NAS的虚拟机环境下，下载AC LAN失败

### ISSUE THREAD

**Issue by Cute-Banana** [georgezhao2010/midea_ac_lan#231]
通过HACS的集成入口，搜索并下载Midea AC LAN，会一直停留在这个下载的界面，不停转圈，等待了一天还是如此。

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/129645036/1d5ca8d6-7079-45ce-88d2-fd0700147c74)

也尝试过手动安装，在component的文件夹中解压，但是在重启Homeassistant之后，并没有在集成端显示安装成功。

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/129645036/840b6d53-a310-468c-9190-0009a9bdc66b)

HA的版本信息如下：

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/129645036/88fe8abd-7808-4811-b026-df1cce5a699a)

**Comment by georgezhao2010** [comment]
> 通过HACS的集成入口，搜索并下载Midea AC LAN，会一直停留在这个下载的界面，不停转圈，等待了一天还是如此。
> 
>  ...
> 
> 也尝试过手动安装，在component的文件夹中解压，但是在重启Homeassistant之后，并没有在集成端显示安装成功。
> 
> ...
> 


国内对Github的访问困难，所以直接使用HACS下载有时候比较困难，要么多试几次，要么翻墙。

直接放到本地，你放的文件夹有问题，应该把midea_ac_lan-0.3.16/custom_components/media_ac_lan这个文件夹，放到HA的custom_componnents文件夹下

**Comment by hyoou1** [comment]
我这边其他的都可以下载，就这个提示未知错误怎么弄

**Comment by hyoou1** [comment]
![屏幕截图 2024-03-14 220744](https://github.com/georgezhao2010/midea_ac_lan/assets/162999337/a9a3968c-fad7-4232-8a61-edd26e6f7b10)

**Comment by liucheng2050** [comment]
我也遇到相同情况，别的应用可以下载，Midea AC LAN下载失败

**Comment by piyell** [comment]
> 我也遇到相同情况，别的应用可以下载，Midea AC LAN下载失败

same problem
