### ISSUE TITLE
homekit控制AC空调问题

### ISSUE THREAD

**Issue by RomanticHW** [georgezhao2010/midea_ac_lan#232]
风扇和温度分成了两个设备，当我用HomePod打开空调时，它打开默认时制冷。。。。修改什么配置可以让他打开时制冷呢？
我使用“把空调设置成制冷” siri不太聪明，感觉只能修改默认模式来使用，但是不知道该怎么改

**Comment by georgezhao2010** [comment]
我的也是这样，这应该是Homeassistant的HomeKit桥接器的锅，它就会把空调分为两部分。

我的解决办法是把其中的风扇单独命名一下，比如“客厅空调”和“客厅空调风扇”，这样Siri就知道你要控制哪个设备了
