### ISSUE TITLE
Boost Mode on Carrier AC not working

### ISSUE THREAD

**Issue by ryanandres** [georgezhao2010/midea_ac_lan#233]
I'm trying to use the boost mode on a Carrier 40MAQB24B--3 . I tried triggering this via the custom control as well as the preset, all within Home Assistant. The AC beeps as if it received a command, but its behavior does not change at all. The custom control toggle reverts back to its off state and the preset mode reverts to None.

However, i'm still able to trigger boost mode using my IR remote.

**Comment by juanmijm** [comment]
Hello, same issue for me, any solution??? thanks!

**Comment by juanmijm** [comment]
> > Hello, same issue for me, any solution??? thanks!
> 
> I switched to https://github.com/mill1000/midea-ac-py

wow, I have also changed to this integration and now everything works much better, the boost mode already works, it updates the data more quickly, and it doesn't get hung up, also now an indoor and outdoor temperature sensor appears, it's great, thank you very much!

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.18](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.18), you two could try to see if it works correctly.
