### ISSUE TITLE
HA throwing error

### ISSUE THREAD

**Issue by brouna** [georgezhao2010/midea_ac_lan#235]
This error originated from a custom integration.

Logger: custom_components.midea_ac_lan.midea.core.device
Source: custom_components/midea_ac_lan/midea/core/device.py:316 
Integration: Midea AC LAN (documentation, issues) 
First occurred: July 12, 2023 at 8:49:38 AM (76421 occurrences) 
Last logged: 3:09:54 PM

[151732604690694] Unknown error OverflowError('int too big to convert')
[150633093131978] Unknown error OverflowError('int too big to convert')

**Comment by astavitsky-nybc** [comment]
Same issue - reboot seemed to solve it.

**Comment by urmston** [comment]
I've had the same error about 3 times in the past few weeks on 2 different units, never at the same time. Reloading the integration resolved the problem each time.

**Comment by chemelli74** [comment]
@georgezhao2010 , could you please be so kind to make a new release from `master` branch ? It seems to contain some important fixes.

Thank you in advance,

Simone

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)
