### ISSUE TITLE
Midea AC Filter

### ISSUE THREAD

**Issue by manjotsc** [georgezhao2010/midea_ac_lan#238]
Anyway to acknowledge clean filter from Home Assistant? Have open Midea App to acknowledge.

Thanks,

**Comment by georgezhao2010** [comment]
> Anyway to acknowledge clean filter from Home Assistant? Have open Midea App to acknowledge.
> 
> Thanks,

The sensor `sensor.{DEVICEID}_full_dust`, does it works correct?

See the doc https://github.com/georgezhao2010/midea_ac_lan/blob/master/doc/AC.md#extra-entities

**Comment by manjotsc** [comment]
@georgezhao2010 Yes, the sensor does work inside Home Assistant. However, there is no way to reset the state from Home Assistant itself. You have to go to the app or the unit itself.

See Attachment

Thanks,

![Screenshot_20230903-124526_Midea Air](https://github.com/georgezhao2010/midea_ac_lan/assets/51430971/82f06e9c-f86f-470e-8466-02e0986769d3)
![Screenshot 2023-09-03 124433](https://github.com/georgezhao2010/midea_ac_lan/assets/51430971/8a875d04-4e2e-4064-89a3-78c22d08eab1)
![Screenshot 2023-09-03 124450](https://github.com/georgezhao2010/midea_ac_lan/assets/51430971/39dd8a0d-38b9-4859-a13c-fa5fbc33f478)

**Comment by georgezhao2010** [comment]
> @georgezhao2010 Yes, the sensor does work inside Home Assistant. However, there is no way to reset the state from Home Assistant itself. You have to go to the app or the unit itself.
> 

Now I understand that you may need a button to reset the filter. But I don’t understand why you need to control this button from the HA. Is it helpful for your home automation? Or do you just want to give up using the App totally?

**Comment by georgezhao2010** [comment]
> @georgezhao2010 just want to give up app totally.

I’m sorry, but I believe this feature is unnecessary and I don’t foresee myself investing effort into it.
