### ISSUE TITLE
能否支持东芝T7-86E6智能马桶盖(Toshiba Type C2)

### ISSUE THREAD

**Issue by DenneyTang** [georgezhao2010/midea_ac_lan#241]
大佬，能否支持一下东芝这款智能坐便器？

型号：东芝T7-86E6
Appliance code：211106233272671
Type：C2
Supported：False

目前是能够被集成组件识别到，但没办法添加。看看如果需要什么信息我可以提供，谢谢啦！

**Comment by georgezhao2010** [comment]
马桶盖....这个用的人很多嘛，你想实现马桶盖哪些功能呢？

另外把识别到的设备的SN发给我邮箱吧，georgezhao75@gmail.com

**Comment by DenneyTang** [comment]
> 马桶盖....这个用的人很多嘛，你想实现马桶盖哪些功能呢？
> 
> 另外把识别到的设备的SN发给我邮箱吧，[georgezhao75@gmail.com](mailto:georgezhao75@gmail.com)

谢谢大佬！SN发你邮箱了。

主要是这玩意有时自动座圈加热，大热天的30℃还在发热，读取状态做联动。

另外就是希望能监听马桶盖的打开关闭状态，或者是否坐人的状态，然后决定是否保持卫生间灯常亮。

简单说就是读取一些主要状态做联动，主要几个状态当然越多越好😏：
1、开盖状态（工作状态）
2、坐人状态（工作状态）
3、座圈温度
4、滤芯状态
5、喷水温度
6、其它（如截图）
![Screenshot_20230805_073551_com midea ai appliances](https://github.com/georgezhao2010/midea_ac_lan/assets/19922795/9a6a8d86-7779-4a37-9a36-390c436d98d2)

**Comment by DenneyTang** [comment]
对了能否除读取状态外，还可以通过service服务改变马桶盖的设置，谢谢啦！

**Comment by georgezhao2010** [comment]
Supported in [v0.3.19](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.19)
