### ISSUE TITLE
Set horizontal and vertical blade angles

### ISSUE THREAD

**Issue by v1k70rk4** [georgezhao2010/midea_ac_lan#243]
This is more of a feature request than a bug. 
In the new mSmart app, you can already set horizontal and vertical blade angles. Could this somehow be integrated? 
Or does anyone have a manual on what commands to give? 
I currently solve this with infrared transmission.

The types of my air conditioners:
- midea xtreme save pro
- midea breezless+

Thank you in advance for your help.

**Comment by Viss** [comment]
+1 for this!
I bought two new units - a midea duo 14k btu ac + heat heatpump, and an additional midea 14k btu heatpump ac unit. 

Both can set the vent angles in the app, and after checking the entity in HA I can't see any attribute anywhere for the vent settings. It would be SUPER AMAZING to be able to use HA to change the angle of the vents (I never turn on swing, I aim them at the respective ceiling fans in each room), and when these things are powered down and then up again the vent defaults to "straight up", so I always have to manually go adjust them

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/1756255/fd8cef79-0619-41c6-8941-1d553f667cbc)

**Comment by Viss** [comment]
If there's something I can do to help out here, please let me know!

**Comment by v1k70rk4** [comment]
> Both can set the vent angles in the app, and after checking the entity in HA I can't see any attribute anywhere for the vent settings. It would be SUPER AMAZING to be able to use HA to change the angle of the vents (I never turn on swing, I aim them at the respective ceiling fans in each room), and when these things are powered down and then up again the vent defaults to "straight up", so I always have to manually go adjust them

Hello,

There's a trick for this :) If your air conditioner supports the "Indirect Wind" feature, then when you turn it on, the blade will point upwards at fan speed 1. Wait for two seconds and then invoke the "Midea AC LAN: Set AC fan speed" and set it to auto or your desired speed.

Unfortunately, my Breezless doesn't support this, but it works on the other one.

**Comment by Viss** [comment]
Thats sort of the opposite of what im going for, I need to aim it more or less straight forward. the units I have aim the vent at basically a 45 degree angle or so when i set it to 'forward', so I aim it into a ceiling fan and it circulates throughout a large room. it works very well too - but until the support to move the vents gets added to this integration, i still have to use the phone app to manually change the vent direction every time the unit is powered down and back up again

**Comment by georgezhao2010** [comment]
I’m sorry, but I believe this feature is unnecessary for most peoples and I don’t foresee myself investing effort into it.

**Comment by Viss** [comment]
can you please give me some pointers for how I can do it myself? I use it every day

**Comment by georgezhao2010** [comment]
> can you please give me some pointers for how I can do it myself? I use it every day
> 

Could you please provide the model of your device? You can find this information in Settings -> Devices & Services -> Midea AC LAN -> Devices -> Device Info. Once I have that, I’ll give you a lua script specifically for your device.

**Comment by Viss** [comment]
I think this is it:

Air Conditioner 00000Q18

**Comment by georgezhao2010** [comment]
> I think this is it: Air Conditioner 00000Q18

Perhaps you might find what you’re looking for in this LUA script.

[T_0000_AC_75.zip](https://github.com/georgezhao2010/midea_ac_lan/files/12704244/T_0000_AC_75.zip)

**Comment by v1k70rk4** [comment]
> > I think this is it: Air Conditioner 00000Q18
> 
> Perhaps you might find what you’re looking for in this LUA script.
> 
> [T_0000_AC_75.zip](https://github.com/georgezhao2010/midea_ac_lan/files/12704244/T_0000_AC_75.zip)

Can you possibly send me such a LUA script as well? The model number of my air conditioners is:
00000Q19
00000Q11

**Comment by Viss** [comment]
i glanced at the lua script and didnt see anything in it that mentioned specific vent positions. I'll go through it in more detail - I'm curious what this script is and where it came from. It looks like the instructions sent to the midea units are sent as hex bytes amd everything is encoded a certain way, so perhaps someone decompiled the apk and identified each command.

If I could get some insight there I could try and give it a go

**Comment by georgezhao2010** [comment]
@v1k70rk4 @Viss 

I’ve found that perhaps just having the model might not be sufficient to download the correct LUA file. Could you provide the Serial Number (SN) of your device?  You can find the SN by navigating to ‘Settings -> Devices & Services -> Midea AC LAN -> Add device -> Just list appliances (List all appliances only)

**Comment by Viss** [comment]
it looks like i can get it out of the midea app, because i tried via  home assistant as youve instructed but it said 'not found'.

**Comment by wisse-smit** [comment]
Hello all, reading this discussion with great interest. I have the same option in the Carrier app and am also looking for a way to set the blade direction in an automation to a specific level rather than turning on the swing function which I never use. In the afternoon I want to heat a specific place in the room more downwarss for lunch with direct air, and in the evening the flow should be more upwards. I have couple of carrier 42QHG009D8S models. I have looked everywhere for more information but couldn't find anything. If you figured anything out in the meantime @Viss I would love to know! If this would be available in some way that would be perfect!

**Comment by Viss** [comment]
sadly i have had no luck so far. the lua scripts dont seem to indicate what api endpoints control the blade positions and i dont have enough intel to dissect the protocol myself

**Comment by bartoszkaminski** [comment]
Did anyone have any luck with that? I'm also looking forward to seeing this feature and I made some unsuccessful tries to implement it.

With my previous AC (also Midea-like: Rotenso Roni) I was able to control it with tuya_local integration. You can see the config here: https://github.com/make-all/tuya-local/blob/0a503e52384e059d33dd34de2352a5c25084d6b6/custom_components/tuya_local/devices/rotenso_ronix_heatpump.yaml#L4

Now I have Rotenso Versu Pure and this one only works with NetHome Plus app so I'm unable to use tuya_local.

**Comment by Viss** [comment]
what im doing in the meantime is using an automation to check for when the midea ac duo turns from 'off' to 'cool', then starting the vertical swing, counting 9 seconds, then turning it back off again. that positions the vertical swing to mostly where i would like it to be, but it would be very very handy being able to manually specify where to aim the vent like we can in the midea app
