### ISSUE TITLE
Can't connect to Midea cloud to take appliance‘s key-info(Token and Key)

### ISSUE THREAD

**Issue by dougle03** [georgezhao2010/midea_ac_lan#251]
Hi,
Having this problem when trying to add a couple of AC units. I have 4, the first 2 installed ok a couple of weeks ago. Had two more fitted today and now getting the above error. I also had to reset my password in the app which was weird...
I've done the const.py un and pw change but still no luck...
Any help, thanks, Pete
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/59865048/bfa6ce88-ece9-4394-8903-529363a9209f)

**Comment by Rihan9** [comment]
Same problem here. The documentation don't speak abount change something on the const.py file. Do you need to set something? I have tried to set my username/password without much success

**Comment by georgezhao2010** [comment]
Midea has changed MSmartHome-API
Fixed in [v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)

**Comment by Rihan9** [comment]
Works perfectly! Thank you!

**Comment by dougle03** [comment]
> Midea has changed MSmartHome-API Fixed in [v0.3.17](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.17)

Any idea when it'll get pushed out via HACS? Thanks

**Comment by dougle03** [comment]
Nevermind, it's rolled out. Many thanks,
