### ISSUE TITLE
20230804 今天跟新之后实体不存在

### ISSUE THREAD

**Issue by 907739769** [georgezhao2010/midea_ac_lan#252]
之前能用的实体不存在了

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/27858369/cec116b3-1598-4efb-85c7-057fd55f973a)

**Comment by georgezhao2010** [comment]
你的HomaAssistent的版本
另外打开该集成的调试，重启HA，然后日志给我看一下呢

**Comment by 907739769** [comment]
Logger: homeassistant.components.climate
Source: custom_components/midea_ac_lan/climate.py:282
Integration: 空调 (documentation, issues)
First occurred: 22:04:03 (6 occurrences)
Last logged: 22:04:03

Error while setting up midea_ac_lan platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/midea_ac_lan/climate.py", line 46, in async_setup_entry
    devs.append(MideaCCClimate(device, entity_key))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/climate.py", line 282, in __init__
    self._modes = [HVACMode.OFF, HVACMode.FAN_ONLY, HVACMode.DRY, HHVACMode.HEAT, HVACMode.COOL, HVACMode.AUTO]
                                                                  ^^^^^^^^^
NameError: name 'HHVACMode' is not defined

**Comment by 907739769** [comment]
![2222](https://github.com/georgezhao2010/midea_ac_lan/assets/27858369/0ea9c546-de18-4101-b204-7bef165caaa9)
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/27858369/5bc7d4a8-4c73-481f-818e-af318950578c)

**Comment by georgezhao2010** [comment]
> 

好的我知道了，奇怪的是，这个问题并不是这次更新引起的。

**Comment by woodycloudy** [comment]
我也是MDV Wi-Fi Controller，不能用了！辛苦大佬了！后续有望解决就好
