### ISSUE TITLE
0.3.17中，风管机控制器MDV Wi-Fi Controller不再提供此实体

### ISSUE THREAD

**Issue by woodycloudy** [georgezhao2010/midea_ac_lan#257]
大佬好，辛苦了！最近刚用你的插件，十分感谢！0.3.16的时候添加了风管机的控制器MDV Wi-Fi Controller，还能控制一切正常！升级了0.3.17后用不了，提示：集成“midea_ac_lan”不再提供此实体。如果实体不再使用，可以在“设置”中删除它。求求大佬修复一下，不知道为何升级要把它删了。还有一个问题0.3.16添加了风管机控制器，在HA里能够跟其他空调一样调温度和风速，但是桥接到homeit，风管机只能调温度，风速没了，其他空调倒是正常。

**Comment by woodycloudy** [comment]
我重装0.3.17后，添加集成MDV Wi-Fi Controller，不再显示有1个设备和1个实体了。换回0.3.16添加就一切正常。

**Comment by woodycloudy** [comment]
刚看到另一个人也遇到了，我跟他一样日志
Logger: homeassistant.components.climate
Source: custom_components/midea_ac_lan/climate.py:282 
Integration: 空调 (documentation, issues) 
First occurred: 00:25:06 (1 occurrences) 
Last logged: 00:25:06

Error while setting up midea_ac_lan platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/midea_ac_lan/climate.py", line 46, in async_setup_entry
    devs.append(MideaCCClimate(device, entity_key))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac_lan/climate.py", line 282, in __init__
    self._modes = [HVACMode.OFF, HVACMode.FAN_ONLY, HVACMode.DRY, HHVACMode.HEAT, HVACMode.COOL, HVACMode.AUTO]
                                                                  ^^^^^^^^^
NameError: name 'HHVACMode' is not defined

**Comment by georgezhao2010** [comment]
> 刚看到另一个人也遇到了，我跟他一样日志 Logger: homeassistant.components.climate Source: custom_components/midea_ac_lan/climate.py:282 Integration: 空调 (documentation, issues) First occurred: 00:25:06 (1 occurrences) Last logged: 00:25:06
> 
> Error while setting up midea_ac_lan platform for climate Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform await asyncio.shield(task) File "/config/custom_components/midea_ac_lan/climate.py", line 46, in async_setup_entry devs.append(MideaCCClimate(device, entity_key)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/midea_ac_lan/climate.py", line 282, in **init** self._modes = [HVACMode.OFF, HVACMode.FAN_ONLY, HVACMode.DRY, HHVACMode.HEAT, HVACMode.COOL, HVACMode.AUTO] ^^^^^^^^^ NameError: name 'HHVACMode' is not defined

https://github.com/georgezhao2010/midea_ac_lan/issues/252#issuecomment-1665751650
