### ISSUE TITLE
滚筒洗衣机能否增加实体控制？

### ISSUE THREAD

**Issue by zy19921108** [georgezhao2010/midea_ac_lan#258]
大佬，滚筒洗衣机能否增加更多的控制实体，比如说洗涤程序(混合洗、快洗15'、羊毛洗、智能洗、护色洗、羽绒洗、单烘干、单脱水等等)的控制增加，洗涤的温度、水位、转速、漂洗次数等内容增加控制实体，谢谢！

**Comment by georgezhao2010** [comment]
参阅 https://github.com/georgezhao2010/midea_ac_lan/issues/246#issuecomment-1675240424
