### ISSUE TITLE
美的中央空调调温功能消失

### ISSUE THREAD

**Issue by SkyEagle8352** [georgezhao2010/midea_ac_lan#262]
如图，之前还有调温功能的，现在只能控制开关了，重启过也删了重新添加过。

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/16552289/48ceb3ef-d997-48f0-908b-423b271beb3d)

**Comment by georgezhao2010** [comment]
什么意思，调温不是使用climate实体吗？你贴这个图是说明啥

**Comment by SkyEagle8352** [comment]
> 什么意思，调温不是使用climate实体吗？你贴这个图是说明啥

就是之前有climate实体可以调温，这里现在加载不出来了

**Comment by georgezhao2010** [comment]
日志有什么信息输出

**Comment by SkyEagle8352** [comment]
日志输出
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/16552289/a50dc4d5-1940-4b7c-a68b-0b094e1532ec)
在HACS下的，0.3.17

**Comment by georgezhao2010** [comment]
这可不算日志，你按照README，打开调试模式，然后重启Homeassistant，把homeassistant下的home-assistant.log发出来，或者邮件发给我

**Comment by SkyEagle8352** [comment]
大佬，请麻烦棒看一下，谢谢啦！
________________________________
发件人: George Zhao ***@***.***>
发送时间: 2023年8月12日 15:50
收件人: georgezhao2010/midea_ac_lan ***@***.***>
抄送: Haoyang Yang ***@***.***>; Author ***@***.***>
主题: Re: [georgezhao2010/midea_ac_lan] 美的中央空调调温功能消失 (Issue #262)


这可不算日志，你按照README，打开调试模式，然后重启Homeassistant，把homeassistant下的home-assistant.log发出来，或者邮件发给我

―

**Comment by georgezhao2010** [comment]
> 

看什么，你也没发日志啊

**Comment by SkyEagle8352** [comment]
sorry我在邮件上上传了日志，这里不知道为啥没显示出来，现在我直接在这里传了，不好意思！
[home-assistant.log](https://github.com/georgezhao2010/midea_ac_lan/files/12328914/home-assistant.log)

**Comment by georgezhao2010** [comment]
> sorry我在邮件上上传了日志，这里不知道为啥没显示出来，现在我直接在这里传了，不好意思！ [home-assistant.log](https://github.com/georgezhao2010/midea_ac_lan/files/12328914/home-assistant.log)

我知道你的问题了，你用编辑工具打开`custom_components/midea_ac_lan/climate.py`，搜索`HHVACMode`,然后去掉一个H，改成`HVACMode`，重启HA，就好了，你先这样临时用着。

问题我已经修正，会在下一个版本更新时发布。

**Comment by SkyEagle8352** [comment]
好的，非常感谢！


杨昊旸

在 2023年8月13日，14:55，George Zhao ***@***.***> 写道：

﻿

sorry我在邮件上上传了日志，这里不知道为啥没显示出来，现在我直接在这里传了，不好意思！ home-assistant.log<https://github.com/georgezhao2010/midea_ac_lan/files/12328914/home-assistant.log>

我知道你的问题了，你用编辑工具打开custom_components/midea_ac_lan/climate.py，搜索HHVACMode,然后去掉一个H，改成HVACMode，重启HA，就好了，你先这样临时用着。

问题我已经修正，会在下一个版本更新时发布。

**Comment by georgezhao2010** [comment]
Fixed in [v0.3.18](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.18)

**Comment by SkyEagle8352** [comment]
> Fixed in [v0.3.18](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.18)
更新之后，无法加载配置向导
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/16552289/8bb09650-26f6-426d-8b18-55be0fa4d7fb)
