### ISSUE TITLE
Stopped working after update to Version v0.3.18

### ISSUE THREAD

**Issue by rehle65** [georgezhao2010/midea_ac_lan#264]
I had to restore my HA environment, because the integration for Midea stopped working after update to the latest version. Anyone else having issues? I am running the latest version of HA (2023.08.2)

**Comment by georgezhao2010** [comment]
Please re-download the latest release in HACS. If the issue persists with the re-downloaded version, show me your logs.

**Comment by rehle65** [comment]
Thank you. After re-downloading the latest release in HACS everything is working find. Whatever caused the issue, I cannot say. Anyways, thank you for your help!
