### ISSUE TITLE
No longer able to set electric water heater target temperature

### ISSUE THREAD

**Issue by svi-nja** [georgezhao2010/midea_ac_lan#267]
I have been using a Midea D100-20ED6 electric water heater with this integration for a couple of months. For the last week or so I have been unable to set target temperature. The message that appears in the UI reads  _"not supported between instances of 'NoneType' and 'int'"_

Log file:
[midea e2.txt](https://github.com/georgezhao2010/midea_ac_lan/files/12334501/midea.e2.txt)

**Comment by svi-nja** [comment]
Hi George, here is about 30 minutes worth of logs, including a HA restart and a water heater power cycle. Let me know if you need me to let the debug logger run for longer.

[home-assistant_midea_ac_lan_2023-08-14T14-20-27.908Z.log.zip](https://github.com/georgezhao2010/midea_ac_lan/files/12335891/home-assistant_midea_ac_lan_2023-08-14T14-20-27.908Z.log.zip)

**Comment by georgezhao2010** [comment]
> Hi George, here is about 30 minutes worth of logs, including a HA restart and a water heater power cycle. Let me know if you need me to let the debug logger run for longer.
> 
> [home-assistant_midea_ac_lan_2023-08-14T14-20-27.908Z.log.zip](https://github.com/georgezhao2010/midea_ac_lan/files/12335891/home-assistant_midea_ac_lan_2023-08-14T14-20-27.908Z.log.zip)

Thank you for your logs. Please follow this issue, I may make some changes that require your testing in the near future.

**Comment by svi-nja** [comment]
This one appears to be working fine: 

`    def old_protocol(self):
        return self._sub_type <= 82 or self._sub_type == 85 or self._sub_type == 36353 if self._sub_type else False`

I would be happy to test the solution intended for a future update, so please feel free let me know if you need me to.

**Comment by georgezhao2010** [comment]
fixed in [v0.3.19](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.19)
