### ISSUE TITLE
 any documentation on how to set up Customize?

### ISSUE THREAD

**Issue by luckyyyyy** [georgezhao2010/midea_ac_lan#268]
I have a fan that needs to be adjusted in 12 levels, but I can't find where to set the JSON speed_count. How should it be configured?

**Comment by georgezhao2010** [comment]
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/27534713/c842c2ed-55a7-490a-a094-e2e721465f9b)

**Comment by luckyyyyy** [comment]
> ![image](https://user-images.githubusercontent.com/27534713/260520528-c842c2ed-55a7-490a-a094-e2e721465f9b.png)

Thank you, I have encountered another problem. When I added the fan to HomeKit integration, it appeared as multiple switches. How should I hide them?

<img width="378" alt="image" src="https://github.com/georgezhao2010/midea_ac_lan/assets/9210430/23d29d3d-dd59-4b09-989f-4066939f8db7">

<img width="938" alt="image" src="https://github.com/georgezhao2010/midea_ac_lan/assets/9210430/0645f93c-418b-4f6f-bd24-edf3984ad214">

**Comment by georgezhao2010** [comment]
I’m sorry, but I have no idea how to solve your homekit problem. You might want to check out https://github.com/home-assistant/core/issues for some possible solutions.
