### ISSUE TITLE
能否增加美的网关设备实现对美的面板开关的控制？

### ISSUE THREAD

**Issue by SkyEagle8352** [georgezhao2010/midea_ac_lan#274]
如题，家里的各种灯的面板开关是通过美的网关集成到美的美居控制的，请问有没有相关的功能可以增加或者文档？

**Comment by georgezhao2010** [comment]
我没有接触过美的网关设备，也不太清楚它是如何管理设备的，你如果方便，把你美居用户名密码发我邮箱georgezhao75@gmail.com

**Comment by georgezhao2010** [comment]
> 如题，家里的各种灯的面板开关是通过美的网关集成到美的美居控制的，请问有没有相关的功能可以增加或者文档？

初步了解的是网关不可直接本地控制，没有协议可供下载,，子设备也暂时没找方法到如何通过网关控制。

你可以尝试用任何tcp客户端尝试连接网关的6444端口，看是否向本地开放。

**Comment by SkyEagle8352** [comment]
> 

好像也不太行，也不知道网关是如何与下面的zigbee设备具体怎么通讯的。

请问后续版本中是否能加入对美的空气传感器(Appliance code: 186916977960538 Type: AD SN: 0000ADA11000WR1PA2193010Z0090000)和智能电炖锅(Appliance code: 211106237101679 Type: E8 SN: 0000E8511612014572C0711001561C4G)的支持呢？

**Comment by aunhappy** [comment]
`你可以尝试用任何tcp客户端尝试连接网关的6444端口，看是否向本地开放。`
这个怎么调呢？

**Comment by georgezhao2010** [comment]
> `你可以尝试用任何tcp客户端尝试连接网关的6444端口，看是否向本地开放。` 这个怎么调呢？

就是验证网关设备是否开放了6444端口，你可以用端口扫描工具，也可以尝试`telnet [网关IP] 6444`的方式看能否建立连接。

**Comment by aunhappy** [comment]
> 就是验证网关设备是否开放了6444端口，你可以用端口扫描工具，也可以尝试`telnet [网关IP] 6444`的方式看能否建立连接。

我用端口扫描工具，网关开放了 22 23 53 端口，没有开 6444 端口

**Comment by georgezhao2010** [comment]
> 

22端口，又到了猜密码环节了。

没有6444基本就意味着无法通过本集成控制，恐怕得专门出一个MideaGateway之类的项目了。

可我又没网关，有也很难做（摊手

**Comment by aunhappy** [comment]
这是扫描到的一些信息


状态: | 确定
-- | --
操作系统: | Linux
IP: | 192.168.1.176
MAC: | FC:DD:55:F9:00:02
制造商: | Shenzhen WeWins wireless Co.,Ltd
NetBIOS: |  
用户: |  
类型: |  
日期: |  
备注: |  


服务 | 详情
-- | --
Port 22 (TCP) | Dropbear sshd 2014.63 protocol 2.0
Port 23 (TCP) | BusyBox telnetd
Port 53 (TCP) | domain

我试了 admin root password 这些密码组合都不对

**Comment by aunhappy** [comment]
对了 `telnet 192.168.1.176` 时，显示的是 OpenWrt login:

**Comment by georgezhao2010** [comment]
> 对了 `telnet 192.168.1.176` 时，显示的是 OpenWrt login:

这个恐怕得逆向美居app去看密码是怎么样的了，不可能真的猜中的

**Comment by aunhappy** [comment]
> 这个恐怕得逆向美居app去看密码是怎么样的了，不可能真的猜中的

怎么逆向啊，有没有教程啥的，我用了好几个安卓模拟器，美居APP都安装了启动不了。。。想抓个包都难

**Comment by aunhappy** [comment]
折腾好久抓包，每次控制开关的时候，是 put 调用 https://mp-ali.smartmidea.net/mas/v5/app/proxy?alias=/v1/appliance/operation/controlPanelFour/210006721649345 这个地址，
header 信息：

  | PUT /mas/v5/app/proxy?alias=/v1/appliance/operation/controlPanelFour/210006721649345 HTTP/1.1
-- | --
User-Agent | meiju/8.20.0.2 (Android;xaga7.1.2)
accessToken | T1hfxgzj5z4******
regionSign | B0CDCA9A524B333517AC21E818******
sign | 4bfe033519835368fd4a835c3167c2f9bd7e1acda41d50d1c8d448c7f3******
secretVersion | 1
random | 1693030777202
version | 8.20.0
systemVersion | 7.1.2
platform | 0
Content-Type | application/json; charset=utf-8
Content-Length | 128
Host | mp-ali.smartmidea.net
Connection | Keep-Alive
Accept-Encoding | gzip

尝试用 apktool 解包，既没找到 sign 怎么签名的，也没找到控制开关的代码在哪……太难了：（

**Comment by georgezhao2010** [comment]
> 折腾好久抓包，每次控制开关的时候，是 put 调用 https://mp-ali.smartmidea.net/mas/v5/app/proxy?alias=/v1/appliance/operation/controlPanelFour/210006721649345 这个地址， header 信息：
> 
>  	PUT /mas/v5/app/proxy?alias=/v1/appliance/operation/controlPanelFour/210006721649345 HTTP/1.1
> User-Agent	meiju/8.20.0.2 (Android;xaga7.1.2)
> accessToken	T1hfxgzj5z4******
> regionSign	B0CDCA9A524B333517AC21E818******
> sign	4bfe033519835368fd4a835c3167c2f9bd7e1acda41d50d1c8d448c7f3******
> secretVersion	1
> random	1693030777202
> version	8.20.0
> systemVersion	7.1.2
> platform	0
> Content-Type	application/json; charset=utf-8
> Content-Length	128
> Host	mp-ali.smartmidea.net
> Connection	Keep-Alive
> Accept-Encoding	gzip
> 尝试用 apktool 解包，既没找到 sign 怎么签名的，也没找到控制开关的代码在哪……太难了：（

我就说你不用折腾抓包读取控制了，你还不如抓包看看，美居启动的时候，下载哪个网关的协议插件。

**Comment by aunhappy** [comment]
不知道这两个是你说的协议插件吗？
http://mjfile-pro.smartmidea.net/T0x16_2023071303.zip
https://mjdownload-pro.smartmidea.net/2022/7/30/11/vbdxmyRKCPmPOSxfNczK.zip
有好多请求，就这两个是下载压缩包的

下面是控制开关时的body
```json
{
	"deviceId": "210006721649345",
	"msgId": "58793822",
	"deviceControlList": [{
		"attribute": 0,
		"endPoint": 3
	}],
	"nodeId": "00158D000820F1B7"
}

**Comment by aunhappy** [comment]
刚又发现一个 post https://mp-ali.smartmidea.net/mas/v5/app/proxy?alias=/v1/appliance/protocol/lua/luaGet 时，返回
```json
{
	"code": 0,
	"msg": "成功",
	"data": {
		"applianceMFCode": "0000",
		"applianceType": "0xDB",
		"url": "http://m-apps-pro.smartmidea.net/900/T_0000_DB_31283_2022111102.lua",
		"modelNumber": "31283",
		"sn8": null,
		"version": 2022111102,
		"fileName": "T_0000_DB_31283_2022111102.lua",
		"md5": "11a15529f2edd5d6c1641770e6168734"
	}
}
```

这个 http://m-apps-pro.smartmidea.net/900/T_0000_DB_31283_2022111102.lua 也许是？

**Comment by georgezhao2010** [comment]
http://mjfile-pro.smartmidea.net/T0x16_2023071303.zip 这个是网关的前端代码，你可以研究研究

**Comment by SikaiGGMU** [comment]
> > 就是验证网关设备是否开放了6444端口，你可以用端口扫描工具，也可以尝试`telnet [网关IP] 6444`的方式看能否建立连接。
> 
> 我用端口扫描工具，网关开放了 22 23 53 端口，没有开 6444 端口

拆开找串口 进去改root密码吧

**Comment by georgezhao2010** [comment]
> 如题，家里的各种灯的面板开关是通过美的网关集成到美的美居控制的，请问有没有相关的功能可以增加或者文档？

由于网关暂时不具备接入条件，此issue关闭，新设备接入你也不用提，都会慢慢做的。
