### ISSUE TITLE
Override temperature attribute with external sensor - Midea AC

### ISSUE THREAD

**Issue by kuba1975** [georgezhao2010/midea_ac_lan#276]
Hi, this is not the bug per se, it is just a question if there is a way to override AC unit's temperature with external sensor? In general I find the temperatures measured by AC units as very misleading, and I thing that it's far much better to rely on external sensors.
So I would like to have configured this integration to disregard any temperature that shows right now as sensor.xxxxxxx_indoor_temperature with the value from another sensor that is already set up in HA (say - sensor.yyyyyyy_indoor_temperature). Would anybody know how to do it? thanks!

**Comment by georgezhao2010** [comment]
Hello,

The function of controlling the air conditioner based on the temperature sensor is actually built into the air conditioner itself, adding an external sensor will not change this logic. Or do you just want to display the value of an external temperature sensor on the HA air conditioner card?

**Comment by kuba1975** [comment]
thanks for prompt response.. I am thinking just displaying the external sensor value on AC card would be ok.

**Comment by georgezhao2010** [comment]
> thanks for prompt response.. I am thinking just displaying the external sensor value on AC card would be ok.

You'd better try this https://github.com/nervetattoo/simple-thermostat

**Comment by kuba1975** [comment]
yeah, but it will not pass the correct temperature to HomeKit, will it? I assume it will just use another Lovelace card in HA. I thought that this is not relevant but I mainly use your integration to expose Midea ACs in HomeKit (that's easier for my roommates) so was thinking changing this in source will fix the issue :)

**Comment by georgezhao2010** [comment]
> yeah, but it will not pass the correct temperature to HomeKit, will it? I assume it will just use another Lovelace card in HA. I thought that this is not relevant but I mainly use your integration to expose Midea ACs in HomeKit (that's easier for my roommates) so was thinking changing this in source will fix the issue :)

Thanks for your advice, I have no plan for this in the near future, but you could make a template clliamte entity to solve your problem (follow this link https://www.home-assistant.io/integrations/template/) and it's easyer.
