### ISSUE TITLE
期待添加读取中央空调工程模式运行参数的功能

### ISSUE THREAD

**Issue by 845044248** [georgezhao2010/midea_ac_lan#278]
首先感谢大哥的辛勤奉献和技术支持，让我们用上这么好的插件。
目前在用是玲珑1代中央空调，线控器能正确识别并显示参数。但实际上该款空调线控器可以开启工程模式，并调出室外机相关实时运行参数，如运行功率、电流、室外温度能各种参数。请问可否读取这些参数并以图表形式展示？
事实上只要是带wifi的线控器都支持调出工程参数，如能解决该问题应该所有2008年后生产的中央空调都支持，这对用户了解自身空调工况和运维师傅判断机器毛病都能提供巨大帮助，十分感谢！
可提供解决该问题的相关支持和工程模式手册。

**Comment by georgezhao2010** [comment]
> 

你这是CC类型还是AC类型的中央空调？

**Comment by georgezhao2010** [comment]
> 首先感谢大哥的辛勤奉献和技术支持，让我们用上这么好的插件。 目前在用是玲珑1代中央空调，线控器能正确识别并显示参数。但实际上该款空调线控器可以开启工程模式，并调出室外机相关实时运行参数，如运行功率、电流、室外温度能各种参数。请问可否读取这些参数并以图表形式展示？ 事实上只要是带wifi的线控器都支持调出工程参数，如能解决该问题应该所有2008年后生产的中央空调都支持，这对用户了解自身空调工况和运维师傅判断机器毛病都能提供巨大帮助，十分感谢！ 可提供解决该问题的相关支持和工程模式手册。

首先，感谢你的感谢，尽管你连星都没给项目点过一个。

其次，你线控器是CC类型还是AC类型的？

**Comment by 845044248** [comment]
> 



> > 首先感谢大哥的辛勤奉献和技术支持，让我们用上这么好的插件。 目前在用是玲珑1代中央空调，线控器能正确识别并显示参数。但实际上该款空调线控器可以开启工程模式，并调出室外机相关实时运行参数，如运行功率、电流、室外温度能各种参数。请问可否读取这些参数并以图表形式展示？ 事实上只要是带wifi的线控器都支持调出工程参数，如能解决该问题应该所有2008年后生产的中央空调都支持，这对用户了解自身空调工况和运维师傅判断机器毛病都能提供巨大帮助，十分感谢！ 可提供解决该问题的相关支持和工程模式手册。
> 
> 首先，感谢你的感谢，尽管你连星都没给项目点过一个。
> 
> 其次，你线控器是CC类型还是AC类型的？

不好意思，初来乍到，现已补上star。

如何分辨CC还是AC？线控器型号是KJR-86G/BK(WIFI)

**Comment by georgezhao2010** [comment]
> > 
> 
> > > 首先感谢大哥的辛勤奉献和技术支持，让我们用上这么好的插件。 目前在用是玲珑1代中央空调，线控器能正确识别并显示参数。但实际上该款空调线控器可以开启工程模式，并调出室外机相关实时运行参数，如运行功率、电流、室外温度能各种参数。请问可否读取这些参数并以图表形式展示？ 事实上只要是带wifi的线控器都支持调出工程参数，如能解决该问题应该所有2008年后生产的中央空调都支持，这对用户了解自身空调工况和运维师傅判断机器毛病都能提供巨大帮助，十分感谢！ 可提供解决该问题的相关支持和工程模式手册。
> > 
> > 
> > 首先，感谢你的感谢，尽管你连星都没给项目点过一个。
> > 其次，你线控器是CC类型还是AC类型的？
> 
> 不好意思，初来乍到，现已补上star。
> 
> 如何分辨CC还是AC？线控器型号是KJR-86G/BK(WIFI)

你添加设备的时候，显示设备的类型是Air Container还是MDV Wi-Fi Controller？这两种都是中央空调的Wi-Fi线控器，可是协议完全不同。

应该是新老两代产品线。

**Comment by 845044248** [comment]
> > > 
> > 
> > 
> > > > 首先感谢大哥的辛勤奉献和技术支持，让我们用上这么好的插件。 目前在用是玲珑1代中央空调，线控器能正确识别并显示参数。但实际上该款空调线控器可以开启工程模式，并调出室外机相关实时运行参数，如运行功率、电流、室外温度能各种参数。请问可否读取这些参数并以图表形式展示？ 事实上只要是带wifi的线控器都支持调出工程参数，如能解决该问题应该所有2008年后生产的中央空调都支持，这对用户了解自身空调工况和运维师傅判断机器毛病都能提供巨大帮助，十分感谢！ 可提供解决该问题的相关支持和工程模式手册。
> > > 
> > > 
> > > 首先，感谢你的感谢，尽管你连星都没给项目点过一个。
> > > 其次，你线控器是CC类型还是AC类型的？
> > 
> > 
> > 不好意思，初来乍到，现已补上star。
> > 如何分辨CC还是AC？线控器型号是KJR-86G/BK(WIFI)
> 
> 你添加设备的时候，显示设备的类型是Air Conditioner还是MDV Wi-Fi Controller？这两种都是中央空调的Wi-Fi线控器，可是协议完全不同。
> 
> 应该是新老两代产品线。

MDV Wi-Fi Controller

**Comment by georgezhao2010** [comment]
> > > > 
> > > 
> > > 
> > > > > 首先感谢大哥的辛勤奉献和技术支持，让我们用上这么好的插件。 目前在用是玲珑1代中央空调，线控器能正确识别并显示参数。但实际上该款空调线控器可以开启工程模式，并调出室外机相关实时运行参数，如运行功率、电流、室外温度能各种参数。请问可否读取这些参数并以图表形式展示？ 事实上只要是带wifi的线控器都支持调出工程参数，如能解决该问题应该所有2008年后生产的中央空调都支持，这对用户了解自身空调工况和运维师傅判断机器毛病都能提供巨大帮助，十分感谢！ 可提供解决该问题的相关支持和工程模式手册。
> > > > 
> > > > 
> > > > 首先，感谢你的感谢，尽管你连星都没给项目点过一个。
> > > > 其次，你线控器是CC类型还是AC类型的？
> > > 
> > > 
> > > 不好意思，初来乍到，现已补上star。
> > > 如何分辨CC还是AC？线控器型号是KJR-86G/BK(WIFI)
> > 
> > 
> > 你添加设备的时候，显示设备的类型是Air Conditioner还是MDV Wi-Fi Controller？这两种都是中央空调的Wi-Fi线控器，可是协议完全不同。
> > 应该是新老两代产品线。
> 
> MDV Wi-Fi Controller

我现在手中的协议完全没有你说的这些数据，所以空调不发，插件是不可能做出来的。

所以你提供一下你设备的SN，可以在（Just list appliance）中看到，发到我邮箱中我看看你的空调CC协议中是否包含了这些信息。

不包含，那就没戏。

**Comment by 845044248** [comment]
设备信息
MDV Wi-Fi Controller 000K86EB(0)
制造商：Midea


实体id
climate.211106235942394_climate


请问是这个sn码吗？





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "georgezhao2010/midea_ac_lan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月22日(星期二) 凌晨0:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [georgezhao2010/midea_ac_lan] 期待添加读取中央空调工程模式运行参数的功能 (Issue #278)





        
首先感谢大哥的辛勤奉献和技术支持，让我们用上这么好的插件。 目前在用是玲珑1代中央空调，线控器能正确识别并显示参数。但实际上该款空调线控器可以开启工程模式，并调出室外机相关实时运行参数，如运行功率、电流、室外温度能各种参数。请问可否读取这些参数并以图表形式展示？ 事实上只要是带wifi的线控器都支持调出工程参数，如能解决该问题应该所有2008年后生产的中央空调都支持，这对用户了解自身空调工况和运维师傅判断机器毛病都能提供巨大帮助，十分感谢！ 可提供解决该问题的相关支持和工程模式手册。
  
首先，感谢你的感谢，尽管你连星都没给项目点过一个。
 其次，你线控器是CC类型还是AC类型的？
  
不好意思，初来乍到，现已补上star。
 如何分辨CC还是AC？线控器型号是KJR-86G/BK(WIFI)
  
你添加设备的时候，显示设备的类型是Air Conditioner还是MDV Wi-Fi Controller？这两种都是中央空调的Wi-Fi线控器，可是协议完全不同。
 应该是新老两代产品线。
  
MDV Wi-Fi Controller
  
我现在手中的协议完全没有你说的这些数据，所以空调不发，插件是不可能做出来的。
 
所以你提供一下你设备的SN，可以在（Just list appliance）中看到，发到我邮箱中我看看你的空调CC协议中是否包含了这些信息。
 
不包含，那就没戏。

**Comment by georgezhao2010** [comment]
> 000K86EB

算了，你不用找了，CC设备能获取的所有信息如下，不包含你要求的那些信息，你的要求无法满足，本issue关闭。

```
uptable["KEY_VERSION"] = "version"
uptable["KEY_CMD_TYPE"] = "cmd_type"
uptable["KEY_POWER"] = "power"
uptable["KEY_MODE"] = "mode"
uptable["KEY_WIND_SPEED"] = "wind_speed"
uptable["KEY_TEMPERATURE"] = "temperature"
uptable["KEY_SMALL_TEMPERATURE"] = "small_temperature"
uptable["KEY_CONTROL_FAN_SPEED"] = "control_fan_speed"
uptable["KEY_PTC_SETTING"] = "ptc_setting"
uptable["KEY_PTC_POWER"] = "ptc"
uptable["KEY_EXHAUST"] = "exhaust"
uptable["KEY_WIND_UD"] = "wind_swing_ud"
uptable["KEY_ECO"] = "eco"
uptable["KEY_WIND_SWING_LR"] = "wind_swing_lr"
uptable["KEY_WIND_SWING_UD_SITE"] = "wind_swing_ud_site"
uptable["KEY_WIND_SWING_LR_SITE"] = "wind_swing_lr_site"
uptable["KEY_POWER_OFF_TIME"] = "power_off_time_value"
uptable["KEY_POWER_ON_TIME"] = "power_on_time_value"
uptable["KEY_SLEEP_SWITCH"] = "sleep_switch"
uptable["KEY_DIGIT_DISPLAY_SWITCH"] = "digit_display_switch"
uptable["KEY_INDOOR_TEMPERATURE"] = "indoor_temperature"
uptable["KEY_EVAPORATOR_ENTRANCE_TEMPERATURE"] = "evaporator_entrance_temperature"
uptable["KEY_EVAPORATOR_EXIT_TEMPERATURE"] = "evaporator_exit_temperature"
uptable["KEY_ERROR_FROM_MACHINE_STYLE"] = "error_from_machine_style"
uptable["KEY_ERROR_CODE"] = "error_code"
uptable["KEY_SUPPORT_DECIMALS"] = "support_decimals"
uptable["KEY_OUT_MACHINE_TYPE"] = "out_machine_type"
uptable["KEY_IS_SUPPORT_MODE_AUTO"] = "is_support_mode_auto"
uptable["KEY_TEMPERATURE_UNIT"] = "temperature_unit"
uptable["KEY_MODE_PRIORITY"] = "mode_priority"
uptable["KEY_FAN_SPEED_LEVEL_TYPE"] = "fan_speed_level_type"
uptable["KEY_WIRECTRL_CHILD_LOCK"] = "wirectrl_child_lock"
uptable["KEY_CLEAN_WARNING_CLEAR"] = "clean_warning_clear"
uptable["KEY_CLEAN_WARNING_STATE"] = "clean_warning_state"
uptable["KEY_IS_SUPPORT_EHEAT"] = "is_support_eheat"
uptable["KEY_IS_SUPPORT_SWING_UD"] = "is_support_swing_ud"
uptable["KEY_IS_SUPPORT_SWING_LR"] = "is_support_swing_lr"
```
