### ISSUE TITLE
Warning "Take sub type timed out"

### ISSUE THREAD

**Issue by 7wells** [georgezhao2010/midea_ac_lan#280]
Hello!

I see the warning "Take sub type timed out" in HA's protocol. What does it mean?

See details below:

```
Logger: custom_components.midea_ac_lan.midea.core.device
Source: custom_components/midea_ac_lan/midea/core/device.py:322
Integration: Midea AC LAN (documentation, issues)
First occurred: 21:32:12 (1 occurrences)
Last logged: 21:32:12

Take sub type timed out
```

Thanks for your great addon and your help! ❤️

**Comment by georgezhao2010** [comment]
> Hello!
> 
> I see the warning "Take sub type timed out" in HA's protocol. What does it mean?
> 
> See details below:
> 
> ```
> Logger: custom_components.midea_ac_lan.midea.core.device
> Source: custom_components/midea_ac_lan/midea/core/device.py:322
> Integration: Midea AC LAN (documentation, issues)
> First occurred: 21:32:12 (1 occurrences)
> Last logged: 21:32:12
> 
> Take sub type timed out
> ```
> 
> Thanks for your great addon and your help! ❤️

Ignore it if everything works fine, I'll remove this warning in future version.

**Comment by misiuplus** [comment]
I have this same warning and than my entity becomes unavailable. Only discover/again connect the device solves the problem. This situation happens several times a week. On the Polish group I found a lot of comments from people who have the same problem. This issue affects Rotenso devices.
 
From HA:
Air Conditioner 00000Q1A(8)

In real:
Versu Pure X 3,5 kW

Logger: custom_components.midea_ac_lan.midea.core.device
Source: custom_components/midea_ac_lan/midea/core/device.py:322
Integration: Midea AC LAN ([documentation](https://github.com/georgezhao2010/midea_ac_lan#readme), [issues](https://github.com/georgezhao2010/midea_ac_lan/issues)) 
First occurred: 19 sierpnia 2023 o 14:33:24 (1 occurrences) 
Last logged: 19 sierpnia 2023 o 14:33:24

Take sub type timed out

**Comment by georgezhao2010** [comment]
> I have this same warning and than my entity becomes unavailable. Only discover/again connect the device solves the problem. This situation happens several times a week. On the Polish group I found a lot of comments from people who have the same problem. This issue affects Rotenso devices.
> 
> From HA: Air Conditioner 00000Q1A(8)
> 
> In real: Versu Pure X 3,5 kW
> 
> Logger: custom_components.midea_ac_lan.midea.core.device Source: custom_components/midea_ac_lan/midea/core/device.py:322 Integration: Midea AC LAN ([documentation](https://github.com/georgezhao2010/midea_ac_lan#readme), [issues](https://github.com/georgezhao2010/midea_ac_lan/issues)) First occurred: 19 sierpnia 2023 o 14:33:24 (1 occurrences) Last logged: 19 sierpnia 2023 o 14:33:24
> 
> Take sub type timed out

Thank you for your report. When this component is connected to a Midea device, it sends a command to request the sub-type of the device, if the device doesn’t respond to the request, it will show as a warning. In most case, it does't affect anything. You can announce this on the Polish group.

**Comment by misiuplus** [comment]
Thank you for the quick reply. Why might na entity become unavailable? What could be the problem? In this case the automations stop working. I have to reload the device every time.

**Comment by georgezhao2010** [comment]
> Thank you for the quick reply. Why might na entity become unavailable? What could be the problem? In this case the automations stop working. I have to reload the device every time.

Have you assigned a static IP address for the device in the router? The IP of the device  changed can cause the device to unavailable.

Please upgrade to the newest release of midea_ac_lan, as an issue in the older version can cause this problem.

I'm going to close this issue, if the problem you reported persists, please reopen a new ISSUE to report it.
