### ISSUE TITLE
美的理想家三代中央空调支持

### ISSUE THREAD

**Issue by AgonyXD** [georgezhao2010/midea_ac_lan#281]
### Device type and model (or SN)

Air Conditioner 22396505(None) 0000005112239650532250XXXXXXXXXX

### The description of new feature

美的理想家三代中央空调，显示支持，但添加设备后无法控制,显示不可用

**Comment by georgezhao2010** [comment]
> 

让你发出来的日志呢？你用的插件版本呢？

**Comment by georgezhao2010** [comment]
而且你提的这叫new feature quest？

**Comment by georgezhao2010** [comment]
我关闭了，回去重新选择错误报告四个中国字提交好吗
