### ISSUE TITLE
希望新增酷省电空调

### ISSUE THREAD

**Issue by liuyongqing1** [georgezhao2010/midea_ac_lan#283]
### 设备类型或型号 (或SN)

Air Conditioner 22251535(32773) 

### 新功能的描述

目前功能上不支持酷省电功能，其他功能正常

**Comment by georgezhao2010** [comment]
空调只能支持大家都有或绝大多数人都有的功能，否则以美的的各种花花名词每个都要支持一遍的话，没有足够的精力，这个我留两个月，如果有多人有相同需求的话，我再予以考虑。

**Comment by Hunter08067** [comment]
为什么我这根本就无法识别酷省电空调？

**Comment by liuyongqing1** [comment]
> 为什么我这根本就无法识别酷省电空调？

可以啊 我的直接就识别了 只是很多功能在这里用不了。

**Comment by Hunter08067** [comment]
我的连设备都发现不了，但美的美居用着正常。。。路由器和电器都是同网段下的，没NAT







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "georgezhao2010/midea_ac_lan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 上午10:15
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [georgezhao2010/midea_ac_lan] 希望新增酷省电空调 (Issue #283)





  
为什么我这根本就无法识别酷省电空调？
  
可以啊 我的直接就识别了 只是很多功能在这里用不了。

**Comment by georgezhao2010** [comment]
否决，不会开发此功能，凭个人精力，只能做一些大部分人都有的功能，否则只算空调的话，特色功能就不下30种，支持不过来。
