### ISSUE TITLE
Midea Dehumidifier model MAD35S1WWT shows odd controls on card and in device info

### ISSUE THREAD

**Issue by ncd7** [georgezhao2010/midea_ac_lan#284]
### HA core version

2023.8.4

### Intergration version

0.3.18

### Device type and model

Dehumidifier 00000Q18(None) by Midea

### The description of problem

Thank you for a great add -- the discovery was very simple once I added the dehumifier to my local network via the Midea Air app. (I assume now I can remove it from the app). 
However, this dehumidifier shows as a very weird card on the dashboard, it doesn't have any meaningful controls other than On/Off.
I'm not sure why I cannot set things like "Manual" vs "Comfort" (aka Auto) vs "Continuous" directly from this card (maybe with little icons) :(. Also, I cannot control the "Turbo" OFF/ON :(.
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/2722344/ec8e427f-fcab-4d5e-9690-e1dac43e1ce6)

If I select the device itself, it gives me some somewhat odd choices for the dropdowns.
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/2722344/e7638cb1-d06e-4fc1-984a-2c27d5c47104)

When I tested them it seems that the shoe dry or clothes dry enable "Turbo" mode.

Finally, I do not see any sensors but maybe I need to look more into it.

Is it possible to fix these oddities? Or there are just too many different devices? I was hoping since the name of the integraiton is "Midea" and this is a Midea device, this will be better supported.

Otherwise, I really love your addon! Thanks.

**Comment by georgezhao2010** [comment]
Are you a HA beginner?

This integration provides a humidifer entity to HA, the frontend UI Card is not provides by this integration and the features that the card can provide depend on HA. If you find it strange, perhaps you should look for another humidifier/dehumidifier card to display the entity.

About more extra sensors, this integration provides  [Extra sensor and switch entities](https://github.com/georgezhao2010/midea_ac_lan#extra-sensor-and-switch-entities) , you could find them out in CONFIGURE for this integration in Settings -> Devices & Services -> Midea AC LAN -> Devices -> CONFIGURE.

There is nothing need to fix.
