### ISSUE TITLE
Latest v02.0.1 makes AC switch between available and unavailable every few seconds

### ISSUE THREAD

**Issue by diedvdyk** [georgezhao2010/midea_ac_lan#29]
The latest v02.0.1 makes my 2 AC's switch between available and unavailable every few seconds.
Unfortunately I dont see any logging what is causing this.

**Comment by diedvdyk** [comment]
Rolled back to v0.1.19 and not seeing this behaviour

**Comment by georgezhao2010** [comment]
> Yes two V2 devices Debug log :
> 
> ...

I knew the problem, wait a moment and update to 0.2.2

**Comment by diedvdyk** [comment]
0.2.2 solved the problem. Thnx
