### ISSUE TITLE
Temperature Reading is wrong after latest update 

### ISSUE THREAD

**Issue by HFGodoy** [georgezhao2010/midea_ac_lan#295]
### Intergration version

0.3.19

### Device type and model

 Air Conditioner 00000Q18(8) by Midea

### Used App

ComfortStar

### The description of problem

After the latest update, the temperature reading (Celcius) is wrong.   (Should be 24 degrees and showing -4.7 degrees).    I had to roll back to the previous version to get an accurate reading.   In addition, I thought Dry mode was exposed to HomeKit and now I cannot seem to get it.   Thank you,

**Comment by georgezhao2010** [comment]
Try to fix this issue following https://github.com/georgezhao2010/midea_ac_lan/issues/292#issuecomment-1705095328

**Comment by HFGodoy** [comment]
Thank you.  This fixed the inaccurate reading.       

Any idea on why Dry mode is not exposed to HomeKit Anymore?  Should I open a new issue to track it?   Thank you again.

**Comment by georgezhao2010** [comment]
Fixed in v0.3.20
