### ISSUE TITLE
Error in the log

### ISSUE THREAD

**Issue by diedvdyk** [georgezhao2010/midea_ac_lan#298]
### HA core version

2023.8.4

### Intergration version

0.3.19

### Device type and model

Qlima Airco

### Used App

...

### The description of problem

This is in my log since the update 0.3.19. My airco isnt controllable anymore

Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType'

### The logs

Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType'

**Comment by georgezhao2010** [comment]
I need more log of issue, enable the debug log and show me more.

**Comment by georgezhao2010** [comment]
> ### The description of problem
> This is in my log since the update 0.3.19. My airco isnt controllable anymore
> 
> Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType'
> 

Or following this https://github.com/georgezhao2010/midea_ac_lan/issues/294#issuecomment-1705662632

**Comment by diedvdyk** [comment]
following #294 solved my problem
