### ISSUE TITLE
"Required key not available" when setting up integration

### ISSUE THREAD

**Issue by advicepyro** [georgezhao2010/midea_ac_lan#299]
### HA core version

2023.9.0

### Intergration version

0.3.20

### Device type and model

(unknown - device is not setup)

### Used App

SmartHome

### The description of problem

Getting the following error in the logs when setting up the integration using Auto:

```
home-assistant  | 2023-09-07 22:09:42.959 ERROR (MainThread) [aiohttp.server] Error handling request
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
home-assistant  |     resp = await request_handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
home-assistant  |     resp = await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
home-assistant  |     response = await handler(request)
home-assistant  |                ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
home-assistant  |     result = await handler(request, **request.match_info)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
home-assistant  |     return await func(self, request, *args, **kwargs)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
home-assistant  |     return await super().post(request, flow_id)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
home-assistant  |     result = await method(view, request, data, *args, **kwargs)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
home-assistant  |     result = await self._flow_mgr.async_configure(flow_id, data)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 298, in async_configure
home-assistant  |     result = await self._async_handle_step(
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
home-assistant  |     result: FlowResult = await getattr(flow, method)(user_input)
home-assistant  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/midea_ac_lan/config_flow.py", line 109, in async_step_discover
home-assistant  |     self.devices = discover(self.supports.keys())
home-assistant  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/midea_ac_lan/midea/core/discover.py", line 51, in discover
home-assistant  |     sock.sendto(BROADCAST_MSG, (addr, 6445))
home-assistant  | OSError: [Errno 126] Required key not available
```

**Comment by georgezhao2010** [comment]
> ### HA core version
> 2023.9.0
> 
> ### The description of problem
> Getting the following error in the logs when setting up the integration using Auto:
> 

Does it work fine in older version of HA?

**Comment by georgezhao2010** [comment]
I can‘t reproduce this issue in HA2023.9.0.

Could you try to add some debugging codes to find out where the problem is?

Open the file midea_ac_lan/midea/core/discover.py, add `_LOGGER.debug(f"All address for broadcast: {addrs}")` before line 49 `for v in range(0, 3):`

Like this
```python
    if ip_address is None:
        addrs = enum_all_broadcast()
    else:
        addrs = [ip_address]
    _LOGGER.debug(f"All address for broadcast: {addrs}")
    for v in range(0, 3):
        for addr in addrs:
            sock.sendto(BROADCAST_MSG, (addr, 6445))
            sock.sendto(BROADCAST_MSG, (addr, 20086))
```

Then enable debug log for midea_ac_lan and restart HA, setting up the integration as your did before and show me the logs.

**Comment by lwh201314** [comment]
此错误来自自定义集成。

Logger: custom_components.midea_ac_lan.midea.core.device
Source: custom_components/midea_ac_lan/midea/core/device.py:330
Integration: Midea AC LAN (documentation, issues)
First occurred: 06:39:14 (7084 occurrences)
Last logged: 09:55:58

[70368744874652] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType')
[140737488423457] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType')
[211106232889928] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType')

**Comment by georgezhao2010** [comment]
> 



> 此错误来自自定义集成。
> 
> Logger: custom_components.midea_ac_lan.midea.core.device Source: custom_components/midea_ac_lan/midea/core/device.py:330 Integration: Midea AC LAN (documentation, issues) First occurred: 06:39:14 (7084 occurrences) Last logged: 09:55:58
> 
> [70368744874652] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType') [140737488423457] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType') [211106232889928] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType')
> 
> HA 2023.9.0

You should open a new issue to report your problem, or try to follow https://github.com/georgezhao2010/midea_ac_lan/issues/294#issuecomment-1705662632 and see if problem is sloved.

**Comment by georgezhao2010** [comment]
No response for a long time, closed for a while

**Comment by advicepyro** [comment]
@georgezhao2010 sorry, was busy and didn't get a chance to test this. I am not able to test this in an older HA version. I've updated the integration to the latest 0.3.21 plus provided my own MSmartHome credentials.

When I choose to auto discover or list all devices, this shows in debug followed by the same error:

```
home-assistant  | 2023-09-20 18:06:24.287 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] All addresses for broadcast: ['192.168.1.255', '10.111.8.255', '172.20.255.255', '172.18.255.255', '172.19.255.255', '172.17.255.255']
home-assistant  | 2023-09-20 18:06:24.290 ERROR (MainThread) [aiohttp.server] Error handling request
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
home-assistant  |     resp = await request_handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
home-assistant  |     resp = await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
home-assistant  |     return await handler(request)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
home-assistant  |     response = await handler(request)
home-assistant  |                ^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
home-assistant  |     result = await handler(request, **request.match_info)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
home-assistant  |     return await func(self, request, *args, **kwargs)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
home-assistant  |     return await super().post(request, flow_id)
home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
home-assistant  |     result = await method(view, request, data, *args, **kwargs)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
home-assistant  |     result = await self._flow_mgr.async_configure(flow_id, data)
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 298, in async_configure
home-assistant  |     result = await self._async_handle_step(
home-assistant  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 394, in _async_handle_step
home-assistant  |     result: FlowResult = await getattr(flow, method)(user_input)
home-assistant  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/midea_ac_lan/config_flow.py", line 168, in async_step_discovery
home-assistant  |     self.devices = discover(self.supports.keys(), ip_address=ip_address)
home-assistant  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
home-assistant  |   File "/config/custom_components/midea_ac_lan/midea/core/discover.py", line 51, in discover
home-assistant  |     sock.sendto(BROADCAST_MSG, (addr, 6445))
home-assistant  | OSError: [Errno 126] Required key not available
```



I installed HA using the Docker container. Do I need to add more capabilities to the image? Is this a networking machine maybe?

**Comment by georgezhao2010** [comment]
> @georgezhao2010 sorry, was busy and didn't get a chance to test this. I am not able to test this in an older HA version. I've updated the integration to the latest 0.3.21 plus provided my own MSmartHome credentials.
> 
> When I choose to auto discover or list all devices, this shows in debug followed by the same error:
> 
> ```
> home-assistant  | 2023-09-20 18:06:24.287 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] All addresses for broadcast: ['192.168.1.255', '10.111.8.255', '172.20.255.255', '172.18.255.255', '172.19.255.255', '172.17.255.255']
> home-assistant  | 2023-09-20 18:06:24.290 ERROR (MainThread) [aiohttp.server] Error handling request
> home-assistant  | Traceback (most recent call last):
> home-assistant  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
> home-assistant  |     resp = await request_handler(request)
> home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> home-assistant  |   ...
> home-assistant  |   File "/config/custom_components/midea_ac_lan/midea/core/discover.py", line 51, in discover
> home-assistant  |     sock.sendto(BROADCAST_MSG, (addr, 6445))
> home-assistant  | OSError: [Errno 126] Required key not available
> ```
> 
> I installed HA using the Docker container. Do I need to add more capabilities to the image? Is this a networking issue maybe? My other integrations that discover WiZ and Tuya devices on my local network work fine though.
> 
> I can try adding it manually but I don't know where to get the appliance code from (device is a Midea dehumidifier)

@advicepyro

In Python, “OSError: [Errno 126] Required key not available” is an operating system error, typically indicating that a required key is not available or missing when using an encrypted file system or hardware device. This error may be triggered when attempting to access a resource that requires a specific key. 

Do you used any encrypted file system or encrypted hardware device?

I have never received reports of similar issues before and I’m not quite sure why it would occur.

**Comment by advicepyro** [comment]
Not that I'm aware of. I'm wondering if the other docker containers that I have running might be creating a network which causes this conflict. Will investigate more and edit this comment with updates.

**Comment by advicepyro** [comment]
So out of curiosity, I modified discover.py and modified `enum_all_broadcast()` to see what would happen if I forced in just 192.168.1.255:

```
def enum_all_broadcast():
    return ['192.168.1.255']

```

Success! My dehumidifer was detected and now it's working.
So perhaps there needs to be a way to gracefully handle those addresses you can't access...

**Comment by georgezhao2010** [comment]
> So out of curiosity, I modified discover.py and modified `enum_all_broadcast()` to see what would happen if I forced in just 192.168.1.255:
> 
> ```
> def enum_all_broadcast():
>     return ['192.168.1.255']
> ```
> 
> Success! My dehumidifer was detected and now it's working. So perhaps there needs to be a way to gracefully handle those addresses you can't access...

OK, I’ll filter out the invalid nets.
