### ISSUE TITLE
能否在set_temperatue中加入设置havc mode

### ISSUE THREAD

**Issue by meatballgithub** [georgezhao2010/midea_ac_lan#3]
HA climate service的模板里set_temperature是可以设置havc mode的，经过实测和看了眼作者的代码，发现在climate.py文件中 set_temperature(self,**kwargs)函数里，只设置了温度，没有对havc_mode处理，不知道作者有空能否在set_temperature内加上设置havc mode。感谢

**Comment by georgezhao2010** [comment]
https://bbs.hassbian.com/forum.php?mod=redirect&goto=findpost&ptid=16812&pid=461820
