### ISSUE TITLE
Anyone willing to share your MSmartHome/Midea Air/NetHome Plus account with me?

### ISSUE THREAD

**Issue by georgezhao2010** [georgezhao2010/midea_ac_lan#302]
I am currently conducting research on decoding commands for Midea devices. Unfortunately, I don’t have any Midea devices linked to my MSmartHome account, which has made the research process challenging. Would anyone be open to sharing their own account with me for research purposes? I assure you that I will not manipulate your devices at any time, nor will I disclose your account information or password to any third parties.

If you are willing to share your account, please send your app name, username and password to [georgezhao75@gmail.com](mailto:georgezhao75@gmail.com). Your assistance is greatly appreciated.

**Comment by verhoop** [comment]
PLease see mail

**Comment by georgezhao2010** [comment]
I need more accounts, any one can help me?
