### ISSUE TITLE
HA无法连接美的云获取设备关键信息(Token和Key)

### ISSUE THREAD

**Issue by zhuangxiaohui** [georgezhao2010/midea_ac_lan#305]
### HA版本

2023.7

### 集成版本

0.3.20

### 使用的App

美的美居

### 问题详细描述

无法连接美的云获取设备关键信息(Token和Key)GitHub 下载最新版本0.3.20插件https://github.com/georgezhao2010/midea_ac_lan/releases

按照[https://www.bilibili.com/video/BV1Zs4y1Z7Bf/ ](https://www.bilibili.com/video/BV1Zs4y1Z7Bf/ )  这个视频配置的实现不了
`MIDEA_DEFAULT_ACCOUNT = '美的美居用户名'`
`MIDEA_DEFAULT_PASSWORD = '自己的密码'`
`MIDEA_DEFAULT_SERVER = "cn"  #这里写cn`

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/5791725/71dd7200-b36a-46c1-91c7-b304d3665ff1)

后面看了源代码，没有cn这个配置的服务，只有  # MSmartHome/美居/SmartLife但按照这个也是不知道MIDEA_DEFAULT_ACCOUNT和MIDEA_DEFAULT_PASSWORD **怎么配置才对**，帐号密码从哪里获取，之前版本从美的美居获取可以的
这个是通过bytes.fromhex(format())配置的
`MIDEA_DEFAULT_ACCOUNT = bytes.fromhex(format((
        10344144934015248205520140834971142348820699691584394687921071489928 ^
        398398236948723456298617505430821312369832194862309
), 'X')).decode('UTF-8')
MIDEA_DEFAULT_PASSWORD = bytes.fromhex(format((
        912456867810398896618648167016171432030329 ^
        912349053982727146476130466822420349834278
), 'X')).decode('UTF-8')
MIDEA_DEFAULT_SERVER = "美居" # MSmartHome/美居/SmartLife`

**Comment by georgezhao2010** [comment]
> ### 问题详细描述
> 无法连接美的云获取设备关键信息(Token和Key)GitHub 下载最新版本0.3.20插件https://github.com/georgezhao2010/midea_ac_lan/releases

这个报错信息本身不是个错误，而是你的网络问题

如果你想问如何配置成自己的美居账号

在const中改成这样：
```python
MIDEA_DEFAULT_ACCOUNT = '你的美居账号'
MIDEA_DEFAULT_PASSWORD = `你的美居密码`
MIDEA_DEFAULT_SERVER = "美居" # MSmartHome/美居/SmartLife
```

**Comment by zhuangxiaohui** [comment]
> > ### 问题详细描述
> > 无法连接美的云获取设备关键信息(Token和Key)GitHub 下载最新版本0.3.20插件https://github.com/georgezhao2010/midea_ac_lan/releases
> 
> 这个报错信息本身不是个错误，而是你的网络问题
> 
> 如果你想问如何配置成自己的美居账号
> 
> 在const.py中改成这样：
> 
> ```python
> MIDEA_DEFAULT_ACCOUNT = "你的美居账号"
> MIDEA_DEFAULT_PASSWORD = "你的美居密码"
> MIDEA_DEFAULT_SERVER = "美居" # MSmartHome/美居/SmartLife
> ```

怎么排查是网络问题，还是别的问题，我正确按下面方式配置，重启还是提示这个错误
```
MIDEA_DEFAULT_ACCOUNT = "你的美居账号"
MIDEA_DEFAULT_PASSWORD = "你的美居密码"
MIDEA_DEFAULT_SERVER = "美居" # MSmartHome/美居/SmartLife
```

**Comment by georgezhao2010** [comment]
> 怎么排查是网络问题，还是别的问题，我正确按下面方式配置，重启还是提示这个错误
> 
> ```
> MIDEA_DEFAULT_ACCOUNT = "你的美居账号"
> MIDEA_DEFAULT_PASSWORD = "你的美居密码"
> MIDEA_DEFAULT_SERVER = "美居" # MSmartHome/美居/SmartLife
> ```

报这个错误就是无法连接美的云，无论是美居云或MSmart云，那就是网络问题呗。只不过这网络问题出在你那还是出在你的网络运营商还是更高层级，我这就不得而知了。

要么你打全DEBUG日志，自己分析一下，网络登录部分有一些隐私信息也不好发上来。

**Comment by lumumu** [comment]
我也遇到了，一样的网络前段时间还没问题的。

**Comment by zhuangxiaohui** [comment]
> 我了解可能出了什么问题，因为账户密码是公开的，所以有人恶意从美的的MSmartHome删除了这个账户，导致无法登录。
> 
> 现在我已经把账户注册回来了，应该可以了。

可以了，我删除HA的缓存可以了，谢谢[georgezhao2010](https://github.com/georgezhao2010)，我纠结好多天

**Comment by 282888888** [comment]
![QQ截图20231015134520](https://github.com/georgezhao2010/midea_ac_lan/assets/61619957/7131be8a-d06e-424d-a168-df1fbe213150)
不管怎么搜索,只能这样弹出来,点提交,无限重复

**Comment by magicdalian** [comment]
因为家里有很多美的的设备，我看.storage里面有很多设备的Key和Token， 删除了其他设备受影响吗？目前我只有管线机和空调无法获取token
