### ISSUE TITLE
希望添加新设备——小烤箱

### ISSUE THREAD

**Issue by tfkzptzt** [georgezhao2010/midea_ac_lan#307]
### 设备类型或型号 (或SN)

0000B43117100032817081XXXXXXXXX

### 新功能的描述

型号：PT4011W
这应该和B1一样，都是电烤箱，但实际检测出来的是类型是B4。
我刚才查了一下，B1是大烤箱，B4是小烤箱。

**Comment by georgezhao2010** [comment]
已于v0.3.21中支持
