### ISSUE TITLE
希望补充支持暖风机功能

### ISSUE THREAD

**Issue by YoungLuk59** [georgezhao2010/midea_ac_lan#310]
### 设备类型或型号 (或SN)

377570667241XXXXXXXXXX，型号HFW20EK

### 新功能的描述

该暖风机自身功能共5个：
1、开关（已支持）
2、Heating Level（只能读取，不能控制）
3、摆风（未支持）
4+5、定时+氛围灯（不必要）

1、开关
本项目已支持启停。
2、Heating Level
暖风机HFW20EK，工作档位只有3个：送风、低热、高热，在HA的Heating Level里显示为0、1、3。
但是仅能查看当前档位，不能通过HA控制档位，拖动控制条和在more-info面板里调节模式都没有效果
3、摆风
没有看到该属性。

**Comment by YoungLuk59** [comment]
是不是要提供美的美居账户？

**Comment by georgezhao2010** [comment]
> ### 设备类型或型号 (或SN)
> 377570667241XXXXXXXXXX，型号HFW20EK
> 
> ### 新功能的描述
> 该暖风机自身功能共5个： 1、开关（已支持） 2、Heating Level（只能读取，不能控制） 3、摆风（未支持） 4+5、定时+氛围灯（不必要）
> 
> 1、开关 本项目已支持启停。 2、Heating Level 暖风机HFW20EK，工作档位只有3个：送风、低热、高热，在HA的Heating Level里显示为0、1、3。 但是仅能查看当前档位，不能通过HA控制档位，拖动控制条和在more-info面板里调节模式都没有效果 3、摆风 没有看到该属性。

模板中不是告诉你上哪读取SN或者型号信息了吗？你提供的这俩信息没一个是对的。

**Comment by georgezhao2010** [comment]
没回应就关闭，无法接受此请求。

**Comment by YoungLuk59** [comment]
不好意思，不常用github
设备型号：Electric Heater 57066724
SN：0000FB311570667241B041XXXXXXXXXX

**Comment by YoungLuk59** [comment]
![SP 2023-12-17_18'37'00'](https://github.com/georgezhao2010/midea_ac_lan/assets/76720829/568d9119-5a83-4949-835d-f6efdde34764)
![SP 2023-12-17_18'37'47'](https://github.com/georgezhao2010/midea_ac_lan/assets/76720829/b35e3679-6970-4dc5-accd-e524dc88bf7f)
