### ISSUE TITLE
搜索到的设备不全

### ISSUE THREAD

**Issue by Hunter08067** [georgezhao2010/midea_ac_lan#312]
### 集成版本

0.3.20

### 设备类型及型号

SQ50蒸烤箱、WX2000洗碗机、酷省电系列空调

### 使用的App

美的美居

### 问题详细描述

SQ50蒸烤箱、WX2000洗碗机、酷省电系列空调，无法探测到设备。

**Comment by georgezhao2010** [comment]
那你要打开调试日志，提供搜索时的日志嘛

**Comment by Hunter08067** [comment]
调试日志详见附件





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "georgezhao2010/midea_ac_lan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 上午10:59
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [georgezhao2010/midea_ac_lan] 搜索到的设备不全 (Issue #312)





 
那你要打开调试日志，提供搜索时的日志嘛

**Comment by georgezhao2010** [comment]
> 调试日志详见附件 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "georgezhao2010/midea_ac_lan" ***@***.***&gt;; 发送时间:&nbsp;2023年9月18日(星期一) 上午10:59 ***@***.***&gt;; ***@***.******@***.******@***.***&gt;; 主题:&nbsp;Re: [georgezhao2010/midea_ac_lan] 搜索到的设备不全 (Issue #312) 那你要打开调试日志，提供搜索时的日志嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

没有什么附件

**Comment by Hunter08067** [comment]
调试日志详见附件


我发了3份附件，有打包压缩的也有没压缩的。您收不到么？是不是被拦截了？





&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "georgezhao2010/midea_ac_lan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 上午10:59
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [georgezhao2010/midea_ac_lan] 搜索到的设备不全 (Issue #312)





 
那你要打开调试日志，提供搜索时的日志嘛
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

home-assistant_midea_ac_lan_2023-09-18T06-41-22.307Z.zip (4.1K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5f613834a08999cec728a9071066541e4a155c500f5252501f050b07044b5152570015050e54071c03550a570253525354580b0c365e66595d0c5d19571515584115595a42390b585604596b5705395d530f67060654551c025815050e3256071f550919045448020256621a4c0f16310f&t=exs_ftn_download&code=2a846ff1

**Comment by georgezhao2010** [comment]
> 调试日志详见附件 我发了3份附件，有打包压缩的也有没压缩的。您收不到么？是不是被拦截了？ &nbsp;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "georgezhao2010/midea_ac_lan" ***@***.***&gt;; 发送时间:&nbsp;2023年9月18日(星期一) 上午10:59 ***@***.***&gt;; ***@***.******@***.******@***.***&gt;; 主题:&nbsp;Re: [georgezhao2010/midea_ac_lan] 搜索到的设备不全 (Issue #312) 那你要打开调试日志，提供搜索时的日志嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 从QQ邮箱发来的超大附件 home-assistant_midea_ac_lan_2023-09-18T06-41-22.307Z.zip (4.1K, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=5f613834a08999cec728a9071066541e4a155c500f5252501f050b07044b5152570015050e54071c03550a570253525354580b0c365e66595d0c5d19571515584115595a42390b585604596b5705395d530f67060654551c025815050e3256071f550919045448020256621a4c0f16310f&t=exs_ftn_download&code=2a846ff1

你邮件中的附件并不能发到github的issue中来，你自己过来看看能不能看到你的附件。你要是想解决问题呢，就老老实实来issue中把你日志贴上。

**Comment by georgezhao2010** [comment]
> 调试日志详见附件 我发了3份附件，有打包压缩的也有没压缩的。您收不到么？是不是被拦截了？
>

日志中显示搜索到了三个设备，分别是E3燃气热水器/DC干衣机/DB滚筒洗衣机，我不知道你说的搜索不全是什么意思，但只有这三个设备响应了搜索广播。搜索不到我也没办法，要么你多搜两次看看，要么使用指定IP配置。

这个问题无从解决，issue我关闭了。
```
{'device_id': 211106237335721, 'type': 227, 'ip_address': '192.168.31.207', 'port': 6444, 'model': '51101877', 'sn': '0000E35115110187736021400112ZLRH', 'protocol': 3}
Found a supported device: {'device_id': 211106237375423, 'type': 220, 'ip_address': '192.168.31.205', 'port': 6444, 'model': '38206508', 'sn': '0000DC5133820650836075A00129UD0K', 'protocol': 3}
{'device_id': 208907213616913, 'type': 219, 'ip_address': '192.168.31.202', 'port': 6444, 'model': '38127929', 'sn': '0000DB5133812792935126100297B5RX', 'protocol': 3}
```
