### ISSUE TITLE
美的燃气热水器 JSQ30-RS8 默认实体Gas Water Heater Default entity温度单位为华氏度

### ISSUE THREAD

**Issue by fakeuniversal** [georgezhao2010/midea_ac_lan#313]
### Device type and model (or SN)

Gas Water Heater JSQ30-RS8 SN:0000E35315110187Z29231XXXXXXXXXX

### The description of new feature

Current temperature及目标温度单位都是华氏度但Gas Water Heater Current Temperature这个实体里面是摄氏度，是不是优化一下统一成℃更好一些呀
![joOyZiUk](https://github.com/georgezhao2010/midea_ac_lan/assets/78199431/fe1b70c0-d151-4d78-812c-8bf02ae88578)

**Comment by georgezhao2010** [comment]
你自己HA单位是不是设错了，燃气热水器返回的单位和数值都是摄氏度。

**Comment by fakeuniversal** [comment]
> 你自己HA单位是不是设错了，燃气热水器返回的单位和数值都是摄氏度。
> 
> ```python
>     @property
>     def temperature_unit(self):
>         return TEMP_CELSIUS
> ```
> 
> 要转换也是HA根据你的单位设置转换的，我代码中没有返回华氏度。

检查了下是HA单位变成华氏度了，如图因为两个实体单位不一样所以没去检查HA的设置。
