### ISSUE TITLE
添加新设备的教程

### ISSUE THREAD

**Issue by goddade** [georgezhao2010/midea_ac_lan#316]
### 设备类型或型号 (或SN)

0

### 新功能的描述

有没有添加新设备的教程。比如如何连接设备，探知设备的通信协议，找到能用的命令，等。

**Comment by georgezhao2010** [comment]
你可以琢磨琢磨这个项目

https://github.com/georgezhao2010/midea-auto-codec

可以下载你设备的lua脚本，负责指令翻译
