### ISSUE TITLE
美的P60洗碗机请求增加运行按钮

### ISSUE THREAD

**Issue by wdmywm3** [georgezhao2010/midea_ac_lan#321]
### 设备类型及型号 (或SN)

Dishwasher 76000613

### 新功能的描述

P60洗碗机用mal已经可以几乎完美接入ha，各项信息也都有显示，只不过目前集成的power开关，对应的是设备的“开机”功能，而开机之后要让洗碗机开始洗碗，则依旧需要点击app中的“运行”按钮，而集成中目前似乎并无这个运行按钮
虽然理论上洗碗机放好了碗就该点击面板/app点击运行开始清洗了，但由于家里做这件事较多的是我长辈，她看不清面板上的字，但又经常门关好一转头，忘了要去手机app里点击运行，于是洗碗机就被晾了一晚上没动
我希望可以设置每天到了点还没运行过洗碗机，就让它自动运行起来，但是少了一个运行按钮
如果可以增加的话，感激不尽！！

**Comment by georgezhao2010** [comment]
> ### 设备类型及型号 (或SN)
> Dishwasher 76000613
> 
> ### 新功能的描述
> P60洗碗机用mal已经可以几乎完美接入ha，各项信息也都有显示，只不过目前集成的power开关，对应的是设备的“开机”功能，而开机之后要让洗碗机开始洗碗，则依旧需要点击app中的“运行”按钮，而集成中目前似乎并无这个运行按钮 虽然理论上洗碗机放好了碗就该点击面板/app点击运行开始清洗了，但由于家里做这件事较多的是我长辈，她看不清面板上的字，但又经常门关好一转头，忘了要去手机app里点击运行，于是洗碗机就被晾了一晚上没动 我希望可以设置每天到了点还没运行过洗碗机，就让它自动运行起来，但是少了一个运行按钮 如果可以增加的话，感激不尽！！

这个你参照 #346，要开始洗碗机/洗衣机/电饭锅等等涉及到模式的设备，涉及到要设置洗涤/煮饭的所用模式/时间等等内容，而由于美的市场的需求，把本来差不多的各种模式设计得五花八门。拿电饭锅来说，你能想象让电饭锅开始做饭有几十种模式可选吗？美的有资源有人力一个型号维持一套逻辑，但我个人没有这种能力用同一套逻辑兼容所有的洗碗机/洗衣机/电饭锅品类下不同型号的五花八门的各种模式，几十种全列出来让你选你也不会方便更何况你的机器可能只支持几十种模式中的1、2、3种而已，其它设置对你的机器都是无效的。更何况还有什么时间设定、什么转速设定、强度设定、洗涤遍数设定等等，没有一套逻辑能适合所有型号。

所以，在这类电器中，做了你要求的功能，可能只会给你带来相反的体验。这就是为什么干脆不做。

**Comment by nhddhr** [comment]
> > ### 设备类型及型号 (或SN)
> > 洗碗机 76000613
> > ### 新功能的描述
> > P60洗碗机使用mal已经可以几乎完美接入了哈，各项信息也都有显示，只是目前集成的电源开关，对应的是设备的“开机”功能，而开机之后要让洗碗机开始清洗碗，则仍然需要点击app中的“运行”按钮，而集成中目前似乎并没有这个运行按钮虽然理论上洗碗机放好碗就该点击面板/app点击运行开始清理了，但由于家里做了这件事预示的是我长辈，她看到明显面板上的字，但又经常门关好一转头，忘了去手机应用程序里点击运行，于是洗碗机就被遗忘了晚上没我希望设置每天到了点还没有运行过洗碗机，就实现自动运行起来，但是少了一个运行按钮如果可以增加的话，感激不尽！
> 
> 这个你参照#246，要开始洗碗机/洗衣机/电饭锅等等涉及到模式的设备，涉及到要设置洗涤/煮饭的所用模式/时间等等内容，而由于美国的市场需求，把大概的各种模式设计得五花八门。拿电饭锅来说，你可以想象让电饭锅开始烹饪有几十种模式任选吗？美的有资源有人力求一个模型维持一套逻辑，但我个人没有这种能力用同逻辑集兼容所有的洗碗机/洗衣机/电饭锅品类下不同型号的五花八门的各种模式，几十种全上市来让你选你也不会方便更方便你的机器可能只支持几十种模式中的1、2、3种而已，其他设置对你的机器都是无效的。更何况还有什么时间设定、什么固定设定、强度设定、洗涤次数设定设置，等等没有一套逻辑功能适合所有型号。
> 
> 所以，在这类电器中，做到了你要求的功能，可能只会给你带来额外的体验。这就是为什么干脆不做。

那做出这个洗碗机插件，只是为了看状态吗，感觉这样没有任何意义呀。因为我这还涉及冬天电费补贴，冬天晚8点后，1毛钱一度电，然后就想设置成冬天晚8点后开始洗碗。但是您这只有电源键，没有启动键，所以相当于是个摆设。

**Comment by nhddhr** [comment]
> > > ### 设备类型及型号 (或SN)
> > > 洗碗机 76000613
> > > ### 新功能的描述
> > > P60洗碗机使用mal已经可以几乎完美接入了哈，各项信息也都有显示，只是目前集成的电源开关，对应的是设备的“开机”功能，而开机之后要让洗碗机开始清洗碗，则仍然需要点击app中的“运行”按钮，而集成中目前似乎并没有这个运行按钮虽然理论上洗碗机放好碗就该点击面板/app点击运行开始清理了，但由于家里做了这件事预示的是我长辈，她看到明显面板上的字，但又经常门关好一转头，忘了去手机应用程序里点击运行，于是洗碗机就被遗忘了晚上没我希望设置每天到了点还没有运行过洗碗机，就实现自动运行起来，但是少了一个运行按钮如果可以增加的话，感激不尽！
> > 
> > 
> > 这个你参照#246，要开始洗碗机/洗衣机/电饭锅等等涉及到模式的设备，涉及到要设置洗涤/煮饭的所用模式/时间等等内容，而由于美国的市场需求，把大概的各种模式设计得五花八门。拿电饭锅来说，你可以想象让电饭锅开始烹饪有几十种模式任选吗？美的有资源有人力求一个模型维持一套逻辑，但我个人没有这种能力用同逻辑集兼容所有的洗碗机/洗衣机/电饭锅品类下不同型号的五花八门的各种模式，几十种全上市来让你选你也不会方便更方便你的机器可能只支持几十种模式中的1、2、3种而已，其他设置对你的机器都是无效的。更何况还有什么时间设定、什么固定设定、强度设定、洗涤次数设定设置，等等没有一套逻辑功能适合所有型号。
> > 所以，在这类电器中，做到了你要求的功能，可能只会给你带来额外的体验。这就是为什么干脆不做。
> 
> 那做出这个洗碗机插件，只是为了看状态吗，感觉这样没有任何意义呀。因为我这还涉及冬天电费补贴，冬天晚8点后，1毛钱一度电，然后就想设置成冬天晚8点后开始洗碗。但是您这只有电源键，没有启动键，所以相当于是个摆设。

而且我这模式一般都是默认的，一般也不用改模式，直接开机运行就成了

**Comment by nhddhr** [comment]
如果大佬方便的话，辛苦给加个启动按钮，感激不尽。设备信息
Dishwasher 7600062K

**Comment by georgezhao2010** [comment]
> > > ### 设备类型及型号 (或SN)
> > > 洗碗机 76000613
> > > ### 新功能的描述
> > > P60洗碗机使用mal已经可以几乎完美接入了哈，各项信息也都有显示，只是目前集成的电源开关，对应的是设备的“开机”功能，而开机之后要让洗碗机开始清洗碗，则仍然需要点击app中的“运行”按钮，而集成中目前似乎并没有这个运行按钮虽然理论上洗碗机放好碗就该点击面板/app点击运行开始清理了，但由于家里做了这件事预示的是我长辈，她看到明显面板上的字，但又经常门关好一转头，忘了去手机应用程序里点击运行，于是洗碗机就被遗忘了晚上没我希望设置每天到了点还没有运行过洗碗机，就实现自动运行起来，但是少了一个运行按钮如果可以增加的话，感激不尽！
> > 
> > 
> > 这个你参照#246，要开始洗碗机/洗衣机/电饭锅等等涉及到模式的设备，涉及到要设置洗涤/煮饭的所用模式/时间等等内容，而由于美国的市场需求，把大概的各种模式设计得五花八门。拿电饭锅来说，你可以想象让电饭锅开始烹饪有几十种模式任选吗？美的有资源有人力求一个模型维持一套逻辑，但我个人没有这种能力用同逻辑集兼容所有的洗碗机/洗衣机/电饭锅品类下不同型号的五花八门的各种模式，几十种全上市来让你选你也不会方便更方便你的机器可能只支持几十种模式中的1、2、3种而已，其他设置对你的机器都是无效的。更何况还有什么时间设定、什么固定设定、强度设定、洗涤次数设定设置，等等没有一套逻辑功能适合所有型号。
> > 所以，在这类电器中，做到了你要求的功能，可能只会给你带来额外的体验。这就是为什么干脆不做。
> 
> 那做出这个洗碗机插件，只是为了看状态吗，感觉这样没有任何意义呀。因为我这还涉及冬天电费补贴，冬天晚8点后，1毛钱一度电，然后就想设置成冬天晚8点后开始洗碗。但是您这只有电源键，没有启动键，所以相当于是个摆设。

哦，“没有意义”，“是个摆设”，说话还真好听。

本意做一些传感器进去，就是为了了解当前洗碗机工作状态，洗完可以语音提示什么的，你觉得没有意义，那就不要用了好吧。

**Comment by nhddhr** [comment]
你说话也够好听的，没事，我不用就是了

**Comment by georgezhao2010** [comment]
连接到 #246 以后综合考虑
