### ISSUE TITLE
美的循环扇上下摇头更新后无法使用

### ISSUE THREAD

**Issue by sasukebinbin** [georgezhao2010/midea_ac_lan#330]
### HA版本

2023.8

### 集成版本

0.3.21

### 设备类型及型号

Fan 56001178

### 使用的App

美的美居

### 问题详细描述

之前的版本是可以上下摇头的,可能是2个版本之前
在Oscillation Mode下选择Tilting会打开上下摇头模式或Both会打开上下左右摇头
现在只要选择Tilting
如果当前在左右摇头,就会关闭左右摇头
如果当前不动,那还是不动

**Comment by georgezhao2010** [comment]
> ### 问题详细描述
> 之前的版本是可以上下摇头的,可能是2个版本之前 在Oscillation Mode下选择Tilting会打开上下摇头模式或Both会打开上下左右摇头 现在只要选择Tilting 如果当前在左右摇头,就会关闭左右摇头 如果当前不动,那还是不动


印象中FA这设备近期没有做任何功能性修改，所以除非你能准确说一下哪个版本是正常的，我进行下对比。或者看看日志中是否有什么报错信息。

**Comment by sasukebinbin** [comment]
我现在装回了最早的0.3.17, 使用没有问题.
多谢了

**Comment by georgezhao2010** [comment]
Fixed in https://github.com/georgezhao2010/midea_ac_lan/commit/7a1b6d0ab6434c03d86a03712d3d5cbc5878ba69
