### ISSUE TITLE
Air Conditioner - Swing Horizontal and Vertical inverted

### ISSUE THREAD

**Issue by srodighiero** [georgezhao2010/midea_ac_lan#331]
### HA core version

2023.9.3

### Intergration version

0.3.21

### Device type and model

Air Conditioner 00000Q12 by Midea

### Used App

MSmartHome

### The description of problem

Compared to controls on native MSmartHome App, Swing controls are inverted.
So for example: when selected Swing Horizontal on HA, it enables Swing Vertical on SmartHome, and viceversa.

Air Appliance: Midea AC Breezeless+

**Comment by georgezhao2010** [comment]
> ### The description of problem
> Compared to controls on native MSmartHome App, Swing controls are inverted. So for example: when selected Swing Horizontal on HA, it enables Swing Vertical on SmartHome, and viceversa.

Unless the majority of devices have the same issue, I believe it’s a specific problem with your individual device.

Let’s see if we receive more reports of a similar issue.

**Comment by srodighiero** [comment]
> > ### The description of problem
> > Compared to controls on native MSmartHome App, Swing controls are inverted. So for example: when selected Swing Horizontal on HA, it enables Swing Vertical on SmartHome, and viceversa.
> 
> Unless the majority of devices have the same issue, I believe it’s a specific problem with your individual device.
> 
> Let’s see if we receive more reports of a similar issue.

@georgezhao2010 ...nevermind. Yesterday evening I have tested it "live" in front of the A/C: It turns out that it is the MSmartHome reporting inverted controls, while your integration is instead correct.

Thank you and sorry for the bother, we can close the issue.
