### ISSUE TITLE
Unable to change Indoor & Outdoor temperature sensors to Fahrenheit

### ISSUE THREAD

**Issue by markshank** [georgezhao2010/midea_ac_lan#333]
### HA core version

2023.9.2

### Intergration version

v0.3.21

### Device type and model

Air Conditioner 00000Q1A

### Used App

SmartHome

### The description of problem

Change temperature sensor settings to F unit of measurement and Update.  Does not persist change.  It remains C.

![Temperature_Sensor_Screenshot 2023-09-27 105038](https://github.com/georgezhao2010/midea_ac_lan/assets/25345979/addec98f-c666-4c96-bccb-9ff4e42a07db)

**Comment by georgezhao2010** [comment]
> ### The description of problem
> Change temperature sensor settings to F unit of measurement and Update. Does not persist change. It remains C.
> 

The code for temperature conversion is not included in this integration. The numerical conversion of temperature is done by Home Assistant, such as the temperature displayed by the climate entity. You may want to raise an issue or feature request with Home Assistant to see if they can perform numerical conversion based on your preferred unit.

**Comment by markshank** [comment]
The climate entity actually works as intended.  My issue is with the sensor entities:
![Climate vs Sensor entities Screenshot 2023-09-27 134343](https://github.com/georgezhao2010/midea_ac_lan/assets/25345979/cf7ae072-3c9f-4ff4-9518-d59ac8f3a569)

I don't have this issue with Z-Wave sensor entities:
![Stelpro Climate vs Sensor entities Screenshot 2023-09-27 134906](https://github.com/georgezhao2010/midea_ac_lan/assets/25345979/3414c489-dbb4-422a-bf35-6f23100a89d2)

**Comment by georgezhao2010** [comment]
> The climate entity actually works as intended. My issue is with the sensor entities: 
> I don't have this issue with Z-Wave sensor entities: 

Whether it’s a sensor entity or a climate entity, I transmit the temperature in Celsius. However, Home Assistant based on your default temperature unit settings, has converted the temperature figures for the climate entity but has not performed the same conversion for the sensor entity. Do you understand?

If you need to display the sensor temperature in Fahrenheit, you can accomplish this using a template sensor.

**Comment by markshank** [comment]
What I am hearing is you are blaming Home Assistant for the issue.  So I presented evidence that other integrations don't have the issue that yours does.  They behave better.

At least you have offered a workaround to your issue.

**Comment by georgezhao2010** [comment]
> What I am hearing is you are blaming Home Assistant for the issue. So I presented evidence that other integrations don't have the issue that yours does. They behave better.
> 
> At least you have offered a workaround to your issue.

I’m sorry, regardless of how other integrations, this integration does not have plans to add a numerical conversion feature in the short term.

**Comment by georgezhao2010** [comment]
> What I am hearing is you are blaming Home Assistant for the issue. So I presented evidence that other integrations don't have the issue that yours does. They behave better.
> 
> At least you have offered a workaround to your issue.

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/27534713/ea1d30d6-9d78-45c0-aab1-7298ea050478)

In system settings of HA,  it displays ‘Note: The unit of temperature sensors is always updated.’ However, in reality, the values and units of the temperature sensors are not being updated, so I believe this is an issue with HA.

**Comment by georgezhao2010** [comment]
> What I am hearing is you are blaming Home Assistant for the issue. So I presented evidence that other integrations don't have the issue that yours does. They behave better.
> 
> At least you have offered a workaround to your issue.

I'm sorry, you are right, I'm wrong. It can be solved.

**Comment by markshank** [comment]
No worries.  Thank you for taking another look at it.

**Comment by georgezhao2010** [comment]
Fixed in https://github.com/georgezhao2010/midea_ac_lan/commit/9a1fd3ff158d5e8f3b956829a9b8a8b811853cb1
