### ISSUE TITLE
Account credentials failing

### ISSUE THREAD

**Issue by will-riley** [georgezhao2010/midea_ac_lan#336]
### HA core version

2023.9.3

### Intergration version

0.3.21

### Device type and model

Midea AC MAW10V1QWT

### Used App

HA

### The description of problem

Getting this error trying to discover automatically. I'm using the same credentials as to log into the Midea Air app for initial setup. Same response using MSmartHome or 美的美居. Should I be using something else for "Account*" field? Thx

### The logs

[custom_components.midea_ac_lan.midea.core.cloud] Midea cloud API url: https://mp-prod.smartmidea.net/mas/v5/app/proxy?alias=/v1/user/login/id/get, data: {'loginAccount': 'myemail@mydomain.com', 'reqId': '9bb2a3dbe7fda41deaa159fe9235b548', 'stamp': '20230929141704'}, response: b'{"msg": 'mobile=myemail@mydomain.com' value is illegal.","code":1006}'

**Comment by georgezhao2010** [comment]
> ### The description of problem
> Getting this error trying to discover automatically. I'm using the same credentials as to log into the Midea Air app for initial setup. Same response using MSmartHome or 美的美居. Should I be using something else for "Account*" field? Thx

Currently, your account settings require you to enter your MSmartHome or 美的美居 account. The Midea Air account is not supported at the moment. If you do not have an MSmartHome account, you can apply for one for free, without the need to bind any device to this account.

I will support more types of App accounts in the next version.
