### ISSUE TITLE
ASHP compatibility?

### ISSUE THREAD

**Issue by LeiChat** [georgezhao2010/midea_ac_lan#337]
### Device type and model (or SN)

MHC-V6

### The description of new feature

Is this awesome integration compatible with Midea Air Source Heat Pumps? (MHC-V4, 6, 8 12)

Any idea what hardware is required to connect the modbus to LAN please?

**Comment by georgezhao2010** [comment]
> ### Device type and model (or SN)
> MHC-V6
> 
> ### The description of new feature
> Is this awesome integration compatible with Midea Air Source Heat Pumps? (MHC-V4, 6, 8 12)
> 
> Any idea what hardware is required to connect the modbus to LAN please?

Yes, this integration supports ASHP.

But

Does your device support control from the network, for instance using an App? This integration currently only supports devices using a specific network protocol (M-Smart Protocol), and there are no plans to extend support other methods or protocols.

More info about modbus to LAN, you can follow the discussion on this forum. https://renewableheatinghub.co.uk/forums/renewable-heating-air-source-heap-pumps-ashps/connecting-home-assistant-to-a-midea-heat-pump/paged/2

**Comment by LeiChat** [comment]
Thank you for the reply and link.
