### ISSUE TITLE
添加colmo中央空调总控器的支持请求

### ISSUE THREAD

**Issue by 740527654** [georgezhao2010/midea_ac_lan#338]
### 设备类型及型号 (或SN)

AC

### 新功能的描述

设备ID：ab70013243
![Camera_XHS_16961712500093fafb80c-ab17-30ca-8082-c665ea7b4e70](https://github.com/georgezhao2010/midea_ac_lan/assets/63200055/1d703f03-5f7e-4e7a-ac2e-6996e180ff04)
请问可以进行适配么

**Comment by georgezhao2010** [comment]
> ### 设备类型及型号 (或SN)
> AC
> 
> ### 新功能的描述
> 设备ID：ab70013243 ![Camera_XHS_16961712500093fafb80c-ab17-30ca-8082-c665ea7b4e70](https://user-images.githubusercontent.com/63200055/271835345-1d703f03-5f7e-4e7a-ac2e-6996e180ff04.jpg) 请问可以进行适配么

本集成只支持使用美的M-Smart协议的设备，也就是说，你使用本集成，List all appliances only功能能列出的设备才能支持，你看你能那能搜索到吗？如果能搜索到，请提供设备的Type及SN。

如果List all appliances only无法搜索到设备，那可能就不支持了。

**Comment by jay1943000** [comment]
wifi线控器已经接入成功，但wifi线控器的新风功能无法单独控制，关闭空调后新风也会跟着关闭，有办法单独控制新风吗

**Comment by georgezhao2010** [comment]
没有更多信息就暂时关闭了
