### ISSUE TITLE
silent mode on C3 type device - Heat Pump Wi-Fi Controller

### ISSUE THREAD

**Issue by michaapyr** [georgezhao2010/midea_ac_lan#339]
### Device type and model (or SN)

C3 - Heat Pump Wi-Fi Controller

### The description of new feature

Hi,
this wifi controller have the silent(quiet) mode option, this option also has a choice of "level 1" and "level 2" of silent operation. The option is present in midea smarthome (msmart) app.
Is there any chance you could look up for possibility to implement it in this integration? That would be awesome.

Thank you so much much for your work, now I couldn't imagine to live without this integration.

**Comment by georgezhao2010** [comment]
> ### The description of new feature
> Hi, this wifi controller have the silent(quiet) mode option, this option also has a choice of "level 1" and "level 2" of silent operation. The option is present in midea smarthome (msmart) app. Is there any chance you could look up for possibility to implement it in this integration? That would be awesome.

Could you enable the debug log, set the silent operation to ‘level 1’, ‘level 2’ or any other levels, then show me the logs? Also, could you show me a snapshot of the silent operation page in the app?

**Comment by michaapyr** [comment]
Hi, huge thank you for your reply!

device model: "Heat Pump Wi-Fi Controller 171H120F
producer: Midea "

I'm attaching the screens from the app, there are the other options like that level selection, but just turning the silent mode on/or off would be huge. To do that in the app I have to click: Silent -> "off/on toggle" -> Save

here's the debug of controller update:
```
2023-10-02 08:37:47.223 DEBUG (Heat Pump Wi-Fi Controller) [custom_components.midea_ac_lan.midea.core.device] [144036023374928] Sending: {'header': 'aa0bc300000000000003', 'body': '01', 'message type': '03', 'body type': '01'}
2023-10-02 08:37:47.410 DEBUG (Heat Pump Wi-Fi Controller) [custom_components.midea_ac_lan.midea.devices.c3.device] [144036023374928] Received: {'header': 'aa23c300000000000003', 'body': '010017a00303201e27c037191912371919053c223c14200000', 'message type': '03', 'body type': '01'}
2023-10-02 08:37:47.411 DEBUG (Heat Pump Wi-Fi Controller) [custom_components.midea_ac_lan.midea.core.device] [144036023374928] Status update: {'zone1_power': False, 'zone2_power': False, 'dhw_power': False, 'zone1_curve': False, 'zone2_curve': False, 'disinfect': False, 'fast_dhw': False, 'zone_temp_type': [True, False], 'mode': 3, 'mode_auto': 3, 'zone_target_temp': [32, 30], 'dhw_target_temp': 39, 'room_target_temp': 96.0, 'zone_heating_temp_max': [55, 55], 'zone_heating_temp_min': [25, 25], 'zone_cooling_temp_max': [25, 25], 'zone_cooling_temp_min': [18, 5], 'room_temp_max': 30.0, 'room_temp_min': 17.0, 'dhw_temp_max': 60, 'dhw_temp_min': 20, 'tank_actual_temperature': 32, 'zone1_water_temp_mode': False, 'zone2_water_temp_mode': False, 'zone1_room_temp_mode': False, 'zone2_room_temp_mode': False}
```

![debug](https://github.com/georgezhao2010/midea_ac_lan/assets/8495955/df894ff9-d1f5-4ce3-9c91-c0cfa01868ff)
![silence level option screen](https://github.com/georgezhao2010/midea_ac_lan/assets/8495955/a8a66677-d9d5-415e-96fd-f4260c174970)
![next screen - silence options](https://github.com/georgezhao2010/midea_ac_lan/assets/8495955/6cd210ed-bb23-44e9-8335-a15037513022)
![next screen - silent on off option](https://github.com/georgezhao2010/midea_ac_lan/assets/8495955/92d00bfe-e73d-4032-becc-766aec5fafda)
![main screen - silent option](https://github.com/georgezhao2010/midea_ac_lan/assets/8495955/1389336e-e1a3-40aa-9627-b9b6db3421b4)

**Comment by georgezhao2010** [comment]
> Hi, huge thank you for your reply!
> 
> device model: "Heat Pump Wi-Fi Controller 171H120F producer: Midea "
> 
> I'm attaching the screens from the app, there are the other options like that level selection, but just turning the silent mode on/off would be huge. To do that in the app I have to click: Silent -> "off/on toggle" -> Save
> 
> 

Do not post the logs as a picture, it serves no other purpose than to harm my eyes.

Moreover, the logs are too sparse for analysis. You should enable the logs, then activate silent mode, wait for 2 minutes, deactivate silent mode, wait another 2 minutes, and finally disable the logs.

**Comment by georgezhao2010** [comment]
> Sure, thank you,
> 
> 16:41:10 - silent mode is turned on 16:43:10 - silent mode is turned off
> 
> message "body" difference: "010017a00303201e27c037191912371919053c223c14260000" - turned off "010017a20303201e27c037191912371919053c223c14260000" - turned on
> 

Thank you for your logs and testing.

I added 2 switches for Heat Pump, `silent_mode` and `eco_mode`. Could you clone a latest code and test it and see if them work fine.

**Comment by michaapyr** [comment]
Hi, it seems to simply work, will be testing out the current master version. That is amazing, thank you!!

**Comment by georgezhao2010** [comment]
implemented in v0.3.22

**Comment by erikgieseler** [comment]
How to activate the super silent mode?
I only have a silent mode switch.

**Comment by michaapyr** [comment]
Hi, I was trying to find a change in message body when super silent mode was turned on, but there wasn't any. I wasn't looking a lot for this, you can try to compare the message bodies in the debug logs yourself.

**Comment by michaapyr** [comment]
it probably goes in some additional message? if there is a thing like that? I showed how it looks on the app, however on the controller it looks like this:
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/8495955/c34c9f9d-4a8a-4cb3-a959-ec5a00d4ac1f)

I thought that the HA switch will work like this "CURRENT STATE" switch on a controller, but when you turn on the HA switch, the "SILENT LEVEL" always changes to "1" somehow, even when you changed it to "2" in the app or in the controller. 

@georgezhao2010 could you try to look again for that?
