### ISSUE TITLE
Ha log error

### ISSUE THREAD

**Issue by uSlackr** [georgezhao2010/midea_ac_lan#340]
### HA core version

2023.9.3

### Intergration version

0.3.21

### Device type and model

Midea U INverter AC

### Used App

Midea Air

### The description of problem

The error below is occurring 30,000 times a day.  The integration still seems to work fine.

### The logs

Logger: custom_components.midea_ac_lan.midea.core.device
Source: custom_components/midea_ac_lan/midea/core/device.py:140
Integration: Midea AC LAN (documentation, issues)
First occurred: September 30, 2023 at 10:25:51 PM (45603 occurrences)
Last logged: 7:33:28 PM

[15393162918736] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType')
[30786325735557] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType')
[15393162964663] Unknown error: /config/custom_components/midea_ac_lan/midea/core/device.py, 120, TypeError('str, bytes or bytearray expected, not NoneType')

**Comment by georgezhao2010** [comment]
> ### The description of problem
> The error below is occurring 30,000 times a day. The integration still seems to work fine.
> 

You can try following #294 #298

**Comment by uSlackr** [comment]
I will test it out. Thank you.

\\Greg

________________________________

**Comment by uSlackr** [comment]
Thank you for the assist and the integration.  Setting the IPs seems to have resolved the issue.

**Comment by smartlifedecors** [comment]
Unable to install from HACS, Says unknown error persistently. I have been trying since 3 days. It's almost 30 attempts per day. Still unable to install. Please help

**Comment by uSlackr** [comment]
> Unable to install from HACS, Says unknown error persistently. I have been trying since 3 days. It's almost 30 attempts per day. Still unable to install. Please help

I suggest you open a new issue. This one was resolved and closed.
