### ISSUE TITLE
Midea AC LAN  - Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by machejc** [georgezhao2010/midea_ac_lan#343]
### HA core version

2023.9.3

### Intergration version

3.21

### Device type and model

Air Conditioner - MAP14HS1TBL

### Used App

Just Home Assistant

### The description of problem

Midea_AC_LAN installs fine on HACS Integrations. After HA restart, went to Devices & services, Integrations and clicked on + ADD INTEGRATION on the lower right hand screen and searched for Midea AC LAN. Clicked on it and got the following message:

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

Looking at home-assistant.log I see:

2023-10-05 16:39:46.388 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: No module named 'Crypto'

Really stumped. Any ideas.

**Comment by georgezhao2010** [comment]
> ### The description of problem
> Midea_AC_LAN installs fine on HACS Integrations. After HA restart, went to Devices & services, Integrations and clicked on + ADD INTEGRATION on the lower right hand screen and searched for Midea AC LAN. Clicked on it and got the following message:
> 
> Error Config flow could not be loaded: {"message":"Invalid handler specified"}
> 
> Looking at home-assistant.log I see:
> 
> 2023-10-05 16:39:46.388 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: No module named 'Crypto'
> 
> Really stumped. Any ideas.
> 

If you’re manually configuring HomeAssistant, you might be missing some components, so it’s recommended to install using HAOS or Docker. If your environment lacks the Crypto library, you can install it in HA by running `pip install pycryptodome`
