### ISSUE TITLE
no devices or entities with auto config, but list appliances shows supported results 

### ISSUE THREAD

**Issue by ahmadnassri** [georgezhao2010/midea_ac_lan#346]
### HA core version

2023.10.1

### Intergration version

0.3.21

### Device type and model

Dehumidifier MAD50P1AWS

### Used App

SmartHome

### The description of problem

login is successful, but no devices found.

![Screenshot_20231010_072528_Home Assistant](https://github.com/georgezhao2010/midea_ac_lan/assets/183195/d7e93f3b-597e-4211-8e82-e0169305d006)

listing devices shows supported result:

![Screenshot_20231010_072511_Discord](https://github.com/georgezhao2010/midea_ac_lan/assets/183195/b4cc5e22-27c6-4d44-a3c5-20df4bb18117)

**Comment by georgezhao2010** [comment]
> ### The description of problem
> login is successful, but no devices found.

https://github.com/georgezhao2010/midea_ac_lan#add-device

```
After the account is configured, Click 'ADD DEVICE' once more to add new device. You could repeat the above action to add multiple devices.
```

**Comment by ahmadnassri** [comment]
ooooh! that was confusing! it works now, thank you.
