### ISSUE TITLE
所有能找到的设备均提示 无法连接到指定设备

### ISSUE THREAD

**Issue by lenlanF** [georgezhao2010/midea_ac_lan#351]
### HA core version

20231002.0 - latest

### Intergration version

0.3.22

### Device type and model

208907213263390 (Dishwasher)

### Used App

美的美居

### The description of problem

使用的是Discover automatically，添加集成后想要新增设备，使用的是自动查找，可以查找出所有的设备，对应APP在每次尝试时有提示对应登录提示，但最终提示 无法连接到指定设备，无法新增，所有设备均一样
设备包括：
208907213263390 (Dishwasher)
210006724733350 (Air Conditioner)
208907213263390 (Dishwasher)
211106236858849 (Air Conditioner)
210006724733281 (Air Conditioner)
210006724771277 (Integrated Ceiling Fan)

**Comment by Arvin-chen** [comment]
我也是所有设备提示无法连接到指定设备

**Comment by MeowYue** [comment]
https://github.com/georgezhao2010/midea_ac_lan/issues/349 感觉基本上就是这个原因，等作者修复吧

**Comment by kffnqtd** [comment]
一样的问题，但是又挺奇怪，四台空调，一台没问题，三台连不上。删除了用手动配置可以重新连接，暂时能正常使用

**Comment by georgezhao2010** [comment]
合并进 #349
