### ISSUE TITLE
Can't log in into midea account

### ISSUE THREAD

**Issue by Juliper** [georgezhao2010/midea_ac_lan#352]
### HA core version

2023.10.1

### Intergration version

0.3.21

### Device type and model

Dehumidifier

### Used App

Midea Air

### The description of problem

I downloaded midea_ac_lan from hacs and now try to log in with my midea account but I cant seem to get it working. My account works with the midea air app but not in hs. For account I type in my email or just the prefix of the email but both doesn't work.

Am I doing something wrong?

**Comment by georgezhao2010** [comment]
> ### HA core version
> 2023.10.1
> 
> ### Intergration version
> 0.3.21
> 
> ### Device type and model
> Dehumidifier
> 
> ### Used App
> Midea Air
> 
> ### The description of problem
> I downloaded midea_ac_lan from hacs and now try to log in with my midea account but I cant seem to get it working. My account works with the midea air app but not in hs. For account I type in my email or just the prefix of the email but both doesn't work.
> 
> Am I doing something wrong?
> 
> ### The logs
> _No response_

Could you sent your Midea Air account & password to my mail georgezhao75@gmail.com

**Comment by MichalLytek** [comment]
I suffer from the same issue.

I had older version and when I tried to add new device, I received `Can't connect to Midea cloud to take appliance‘s key-info(Token and Key)` error.

So I've updateded the integration to the latest version and now having this issue:

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/10618781/5adf718e-2d3e-4234-a93f-beef97fd9c1e)

Nethome Plus app `com.midea.aircondition` works without any issue and can control the devices.

**Comment by Sorentino1964** [comment]
Dito
I suffer from the same issue.

**Comment by georgezhao2010** [comment]
Fixed in v0.3.22

**Comment by copart** [comment]
with 0.3.22 I still cannot login, same issue

**Comment by Dgitalcat12** [comment]
with 0.3.22 it detects my device, but could don't  login 美的美居
<img width="435" alt="Screenshot 2024-04-08 at 23 56 32" src="https://github.com/georgezhao2010/midea_ac_lan/assets/166293129/51e8e0a2-03eb-4117-b017-e026262dbb09">
