### ISSUE TITLE
美的旋耀没有生成防直吹实体

### ISSUE THREAD

**Issue by wu178751257** [georgezhao2010/midea_ac_lan#355]
### Device type and model (or SN)

air conditioner 22012841

### The description of new feature

生成的只有默认实体，但是空调支持防直吹，我看说明里是有额外生成实体防直吹或者无风感。麻烦大佬看下是没有适配这一款还是需要自己创建实体

**Comment by georgezhao2010** [comment]
> ### The description of new feature
> 生成的只有默认实体，但是空调支持防直吹，我看说明里是有额外生成实体防直吹或者无风感。麻烦大佬看下是没有适配这一款还是需要自己创建实体

如果没读过README，麻烦去读，每个人都来问这种问题，我可没精力一一解答。
