### ISSUE TITLE
美的风管机期待能够接入

### ISSUE THREAD

**Issue by SikaiGGMU** [georgezhao2010/midea_ac_lan#36]
token每次都变化

**Comment by SikaiGGMU** [comment]
INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP
ERROR:msmart.security::authentication failed
ERROR:msmart.lan:Authentication failed for 192.168.3.41:42040 -> 192.168.3.47:6444 retries: 0 time: 0.08
INFO:msmart.lan:Got TCP key for 192.168.3.41:42040 -> 192.168.3.47:6444 retries: 0 time: 1.08 tcp_key: 647d1af753cfb0fab1e899d15a6442f9041a1bc37baa366ca045d62c9d5894ad
INFO:msmart.cli:*** Found a device: {'name': 'midea_cc_0265', 'ssid': 'midea_cc_0265', 'ip': '192.168.3.47', 'port': 6444, 'id': 186916977292662, 'version': 3, 'token': '6D9A86CDA77EBBA42D87984030B106FFB50B4EDAD7F3EACDC51D5EA814A1538AD519752345ADBCDAD9A275755FE519D758A11A51024CE220C7C30FEDF3D58A83', 'key': 'CE7BE70FDD7948268F4CE50F76183C25F06F671E86B34BB0B1582AF088B3E871', 'type': 'cc', 'sn': '0CC31126002BWF0C06410026576A7', 'model': '02BWF', 'support': False, 'run_test': True}

**Comment by georgezhao2010** [comment]
> INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP ERROR:msmart.security::authentication failed ERROR:msmart.lan:Authentication failed for 192.168.3.41:42040 -> 192.168.3.47:6444 retries: 0 time: 0.08 INFO:msmart.lan:Got TCP key for 192.168.3.41:42040 -> 192.168.3.47:6444 retries: 0 time: 1.08 tcp_key: 647d1af753cfb0fab1e899d15a6442f9041a1bc37baa366ca045d62c9d5894ad INFO:msmart.cli:*** Found a device: {'name': 'midea_cc_0265', 'ssid': 'midea_cc_0265', 'ip': '192.168.3.47', 'port': 6444, 'id': 186916977292662, 'version': 3, 'token': '6D9A86CDA77EBBA42D87984030B106FFB50B4EDAD7F3EACDC51D5EA814A1538AD519752345ADBCDAD9A275755FE519D758A11A51024CE220C7C30FEDF3D58A83', 'key': 'CE7BE70FDD7948268F4CE50F76183C25F06F671E86B34BB0B1582AF088B3E871', 'type': 'cc', 'sn': '0CC31126002BWF0C06410026576A7', 'model': '02BWF', 'support': False, 'run_test': True}

别着急，差不多一周之内
