### ISSUE TITLE
能加入一些特色功能的lan控制么

### ISSUE THREAD

**Issue by olarodes** [georgezhao2010/midea_ac_lan#4]
比如新风 （包括档位）
净化、除菌、回温抽湿、智慧眼、小天使等等

**Comment by olarodes** [comment]
如果需要抓包的话，我可以来处理
是不是只要有ADB的安卓手机就可以

**Comment by georgezhao2010** [comment]
> 比如新风 （包括档位） 净化、除菌、回温抽湿、智慧眼、小天使等等

这些功能短期内暂不考虑实现，不过你可以把你的空调品牌、型号（HA中设备与服务->设备，对应的设备一行的型号）、以及想要实现的额外功能列出，我统计一下看看。

**Comment by gy6221** [comment]
设备型号：华凌N8HE1（对应HA型号40023）
需求功能：干燥开关（不是抽湿，此开关控制关机后是否继续吹一会把蒸发器吹干）

**Comment by book12345678** [comment]
请看能否增加美的柜式空调（型号50895）的如下功能：无风感。遥控器和APP 里面是两个分项：上无风感、下无风感。谢谢！

**Comment by georgezhao2010** [comment]
> 请看能否增加美的柜式空调（型号50895）的如下功能：无风感。遥控器和APP 里面是两个分项：上无风感、下无风感。谢谢！

‘’‘
	/**
	 * 上下无风感功能切换
	 * @param {Boolean} upIsOpen:true 上无风感功能打开，false 上无风感功能关闭
	 * @param {Boolean} downIsOpen:true 上无风感功能打开，false 上无风感功能关闭
	 * 上下无风感仅在制冷模式下有效
	 */
’‘’
如果提需求的人是给这个repos star过的，说不定支持得能早些哦，但我觉得貌似你木有star。

**Comment by georgezhao2010** [comment]
> 设备型号：华凌N8HE1（对应HA型号40023） 需求功能：干燥开关（不是抽湿，此开关控制关机后是否继续吹一会把蒸发器吹干）

这位也是，先star再提需求，我觉得是起码的尊重吧。
