### ISSUE TITLE
0.3.1找不到空调    提示  未在网络上发现可用新设备

### ISSUE THREAD

**Issue by calvin886886** [georgezhao2010/midea_ac_lan#40]
原来用0.1.9可以找到家里所有的空调.

**Comment by georgezhao2010** [comment]
> 原来用0.1.9可以找到家里所有的空调.

要么就检查一下你的网络情况，比如在docker内部ping一下空调。要么就提供一下搜索时的DEBUG日志，咱们看看。

或者你现在就退回到0.1.9看看能不能搜索到。

**Comment by calvin886886** [comment]
应该是我这系统的问题.....原来是群晖上的ha.后面转到了电视盒子上的NAS  导致找不到.
我最后的处理办法就是在群晖上先识别出来.然后copy KEY和TOKEN.到电视盒子上的ha.
成功添加,
网络环境是一样的.就不知道是什么原因找不到设备
盒子运行 Linux Ubuntu 20.04.4 LTS 服务器系统
Home Assistant 2022.7.7
前端版本： 20220707.1 - latest

**Comment by georgezhao2010** [comment]
> 应该是我这系统的问题.....原来是群晖上的ha.后面转到了电视盒子上的NAS 导致找不到. 我最后的处理办法就是在群晖上先识别出来.然后copy KEY和TOKEN.到电视盒子上的ha. 成功添加, 网络环境是一样的.就不知道是什么原因找不到设备 盒子运行 Linux Ubuntu 20.04.4 LTS 服务器系统 Home Assistant 2022.7.7 前端版本： 20220707.1 - latest

我觉得啊，是这样的：

无论是HAOS还是NAS的Docker，其实HA都是运行在docker中的，这就要求docker配置时必须是host模式（也就是使用宿主机同样的网络），否则HA将和你其它设备不在同一个网段上，跨网段搜索是不行的。

这可能是你新设备无法进行搜索的原因。
