### ISSUE TITLE
希望能添加设备ID为数字以外的内容

### ISSUE THREAD

**Issue by MoontoC** [georgezhao2010/midea_ac_lan#41]
希望能添加设备ID为数字以外的内容, 现在的情况是限定数字, 也就是字母e和0-9, 非常不便

**Comment by MoontoC** [comment]
我描述的有点问题, 手动添加看了一下, 是叫做"设备编号的东西"

**Comment by georgezhao2010** [comment]
> 我描述的有点问题, 手动添加看了一下, 是叫做"设备编号"的东西, 这个是可以随便填什么的, 而且所有实体ID都以它为前缀, 添加设备后可以随便改, 实体ID的前缀也可以随意改, 但只有添加时不行

你之所以能在添加时能随便改设备编号（或者说ID，一回事），是美的部分设备的BUG，没有对通讯过程中的ID做校验，但大部分设备你并不能“随便填什么”，而是填错一位数字都不行。

我们家空调有一台确实可以随便填ID，但其它空调就不行。

所以，你愿意改什么，还是添加以后随便改吧。

**Comment by MoontoC** [comment]
> > 我描述的有点问题, 手动添加看了一下, 是叫做"设备编号"的东西, 这个是可以随便填什么的, 而且所有实体ID都以它为前缀, 添加设备后可以随便改, 实体ID的前缀也可以随意改, 但只有添加时不行
> 
> 你之所以能在添加时能随便改设备编号（或者说ID，一回事），是美的部分设备的BUG，没有对通讯过程中的ID做校验，但大部分设备你并不能“随便填什么”，而是填错一位数字都不行。
> 
> 我们家空调有一台确实可以随便填ID，但其它空调就不行。
> 
> 所以，你愿意改什么，还是添加以后随便改吧。

如果是大部分机型都不能随意填写, 而且必须保持全数字这样难以人类记忆的设备名称, 不如像大多数HASS设备那样, 独立一个完全可以定义的用户名称, 让设备编号不需要参与其中也挺好嘛

**Comment by georgezhao2010** [comment]
> > > 我描述的有点问题, 手动添加看了一下, 是叫做"设备编号"的东西, 这个是可以随便填什么的, 而且所有实体ID都以它为前缀, 添加设备后可以随便改, 实体ID的前缀也可以随意改, 但只有添加时不行
> > 
> > 
> > 你之所以能在添加时能随便改设备编号（或者说ID，一回事），是美的部分设备的BUG，没有对通讯过程中的ID做校验，但大部分设备你并不能“随便填什么”，而是填错一位数字都不行。
> > 我们家空调有一台确实可以随便填ID，但其它空调就不行。
> > 所以，你愿意改什么，还是添加以后随便改吧。
> 
> 如果是大部分机型都不能随意填写, 而且必须保持全数字这样难以人类记忆的设备名称, 不如像大多数HASS设备那样, 独立一个完全可以定义的用户名称, 让设备编号不需要参与其中也挺好嘛

你的设备在HA中本来就可以随意命名，谁让你记这串数字了？它在HA中不是这样的吗？哪有数字？

![climate](https://user-images.githubusercontent.com/27534713/182240167-afd2fa94-2048-47e4-82ce-5520686a17b0.png)

**Comment by MoontoC** [comment]
> > > > 我描述的有点问题, 手动添加看了一下, 是叫做"设备编号"的东西, 这个是可以随便填什么的, 而且所有实体ID都以它为前缀, 添加设备后可以随便改, 实体ID的前缀也可以随意改, 但只有添加时不行
> > > 
> > > 
> > > 你之所以能在添加时能随便改设备编号（或者说ID，一回事），是美的部分设备的BUG，没有对通讯过程中的ID做校验，但大部分设备你并不能“随便填什么”，而是填错一位数字都不行。
> > > 我们家空调有一台确实可以随便填ID，但其它空调就不行。
> > > 所以，你愿意改什么，还是添加以后随便改吧。
> > 
> > 
> > 如果是大部分机型都不能随意填写, 而且必须保持全数字这样难以人类记忆的设备名称, 不如像大多数HASS设备那样, 独立一个完全可以定义的用户名称, 让设备编号不需要参与其中也挺好嘛
> 
> 你的设备、以及实体在HA中本来就可以随意命名，谁让你记这串数字了？它在HA中不是这样的吗？哪有数字？
> 
> ![climate](https://user-images.githubusercontent.com/27534713/182240167-afd2fa94-2048-47e4-82ce-5520686a17b0.png)

这个卡片是什么卡啊, 看起来挺好用

**Comment by unixcs** [comment]
> > > > 我描述的有点问题, 手动添加看了一下, 是叫做"设备编号"的东西, 这个是可以随便填什么的, 而且所有实体ID都以它为前缀, 添加设备后可以随便改, 实体ID的前缀也可以随意改, 但只有添加时不行
> > > 
> > > 
> > > 你之所以能在添加时能随便改设备编号（或者说ID，一回事），是美的部分设备的BUG，没有对通讯过程中的ID做校验，但大部分设备你并不能“随便填什么”，而是填错一位数字都不行。
> > > 我们家空调有一台确实可以随便填ID，但其它空调就不行。
> > > 所以，你愿意改什么，还是添加以后随便改吧。
> > 
> > 
> > 如果是大部分机型都不能随意填写, 而且必须保持全数字这样难以人类记忆的设备名称, 不如像大多数HASS设备那样, 独立一个完全可以定义的用户名称, 让设备编号不需要参与其中也挺好嘛
> 
> 你的设备、以及实体在HA中本来就可以随意命名，谁让你记这串数字了？它在HA中不是这样的吗？哪有数字？
> 
> ![climate](https://user-images.githubusercontent.com/27534713/182240167-afd2fa94-2048-47e4-82ce-5520686a17b0.png)

请问这里空调显示的ui界面，使用的哪个皮肤
 ![climate](https://user-images.githubusercontent.com/27534713/182240167-afd2fa94-2048-47e4-82ce-5520686a17b0.png)

**Comment by MoontoC** [comment]
> 请问这里空调显示的ui界面，使用的哪个皮肤 

https://github.com/nervetattoo/simple-thermostat
