### ISSUE TITLE
通过正确的美的美居账号登陆提示账户密码错误 

### ISSUE THREAD

**Issue by leeh107** [georgezhao2010/midea_ac_lan#418]
### HA版本

Core 2024.1.0b2/Supervisor 2023.12.1/Operating System 11.3.rc1/Frontend 20231228.0

### 集成版本

0.3.22

### 设备类型及型号

美的油烟机

### 使用的App

ha

### 问题详细描述

之前是正常的，更新midea ac lan后 油烟机电源开关实体无法使用，删除设备后重新添加发现无法正常必须输入账户密码。使用正确的美的美居账户后进行的配置界面的登录，提示账户密码错误。

### The logs

![1](https://github.com/georgezhao2010/midea_ac_lan/assets/118667118/475d5191-237d-4670-b75f-641ee0b407e1)

**Comment by leeh107** [comment]
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/118667118/9e986dbd-5eb5-40e5-811c-62bee3e58083)

**Comment by leeh107** [comment]
![image](https://github.com/georgezhao2010/midea_ac_lan/assets/118667118/234ed4aa-d891-46d7-a321-47e47e1d008f)

**Comment by qjiang888** [comment]
现在是不能用了，我更新后再也用不了了，退回老版本也不行了，因为修改过app密码了

**Comment by leeh107** [comment]
请问有谁知道解决方法？那两个密钥通过什么方式能够手动获得？如果有密钥 我想是可以使用手动添加进行设备添加的

**Comment by 563816752** [comment]
错误的账户密码在哪里删除啊？

**Comment by lydigaga** [comment]
请问具体是如何解决的 我同样遇到此问题

**Comment by android0276** [comment]
想问下如何解决的，我的死活都不行，一直提示密码错误，时区我看也是对的

**Comment by leeh107** [comment]
> 想问下如何解决的，我的死活都不行，一直提示密码错误，时区我看也是对的

根据我目前收集到的信息，现在是无解的。尝试手动获取key

**Comment by android0276** [comment]
如何手动，能截图看下吗，获取了填写到哪里，把yaml的配置发下，感谢

**Comment by qjiang888** [comment]
> 如何手动，能截图看下吗，获取了填写到哪里，把yaml的配置下，感谢version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /root/homeassistant-gy:/config
      - /etc/localtime:/etc/localtime:ro
    #  - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    privileged: true
    network_mode: host``

**Comment by qjiang888** [comment]
environment:
      - TZ=Asia/Shanghai
我添加这个就可以登陆了

**Comment by android0276** [comment]
开发者同学能不能帮忙看下临时解决的方案

**Comment by android0276** [comment]
洗衣机洗完衣服想收到小爱播报，求接入

**Comment by Printfo** [comment]
> 洗衣机洗完衣服想收到小爱播报，求接入
试试node-red。

**Comment by android0276** [comment]
登录都不成功，何谈 node-red，是不是小天鹅洗衣机不支持啊，这个插件

**Comment by android0276** [comment]
@Printfo

**Comment by leeh107** [comment]
现在有解决方法了吗？怎么弄？有人知道吗

**Comment by leeh107** [comment]
我删除了 midea ac lan安装文件重新安装也不行，更改美的美居的账号密码也不行?有人知到怎么获取美的美居里设备的key的方法吗？我手动添加试试。下一步准备重新安装homeassistont了，不过重装只有就没有继续使用homeassistont的必要了。有人知道之前添加的设备怎么能够备份吗？

**Comment by leeh107** [comment]
放弃使用mideaaclan 使用厂商提供的app  问题关闭

**Comment by heychek** [comment]
这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码哪个版本动过这个地方

**Comment by snowleopardw** [comment]
> 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码哪个版本动过这个地方

正解。const.py 文件中新增 3 行。账号密码对应位置替换下。
MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao'
MIDEA_DEFAULT_PASSWORD = 'nidemima'
MIDEA_DEFAULT_SERVER = "美居"

**Comment by gmmy1979** [comment]
> > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码哪个版本动过这个地方
> 
> 正解。const.py 文件中新增 3 行。账号密码对应位置替换下。 MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美居"

如果还是不行的话，删除这个文件夹：.STORAGE/MIDEA_AC_LAN

**Comment by hulei1997** [comment]
> > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码版本过此
> 
> 正解。const.py 文件中新增 3 行。账号密码对应位置替换下。 MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美居"

谢谢，一个烦恼我很久的问题，已解决

**Comment by SongYoungLv** [comment]
> > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码版本过此
> 
> 正解。const.py 文件中新增 3 行。账号密码对应位置替换下。 MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美居"

更正一下，第三行的“美居”无法正常打开
应该为：
MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao'
MIDEA_DEFAULT_PASSWORD = 'nidemima'
MIDEA_DEFAULT_SERVER = "美的美居"

**Comment by squallyjy** [comment]
> > > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码版本过此
> > 
> > 
> > 正解。const.py 文件中新增 3 行。账号密码对应位置替换下。 MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美居"
> 
> 更正一下，第三行的“美居”无法正常打开 应该为： MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美的美居"

在此基础上试了还是不行。
后来进.storage/midea_ac_lan然后删除account.json，再去添加新设备的时候重新输了账号密码然后选择美的美居，登陆成功了。。。

**Comment by GordonYoungCao** [comment]
> > > > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码版本过此
> > > 
> > > 
> > > 正解。const.py 文件中新增 3 行。账号密码对应位置替换下。 MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美居"
> > 
> > 
> > 更正一下，第三行的“美居”无法正常打开 应该为： MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美的美居"
> 
> 在此基础上试了还是不行。 后来进.storage/midea_ac_lan然后删除account.json，再去添加新设备的时候重新输了账号密码然后选择美的美居，登陆成功了。。。

请问.storagee/midea_ac_lan的完整路径是什么？

**Comment by GordonYoungCao** [comment]
> > > > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码版本过此
> > > 
> > > 
> > > 正解。const.py 文件中新增 3 行。账号密码对应位置替换下。 MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美居"
> > 
> > 
> > 更正一下，第三行的“美居”无法正常打开 应该为： MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美的美居"
> 
> 在此基础上试了还是不行。 后来进.storage/midea_ac_lan然后删除account.json，再去添加新设备的时候重新输了账号密码然后选择美的美居，登陆成功了。。。

大佬，牛啊，解决问题了
