### ISSUE TITLE
Midea heat pump outside temperature issue when below zero

### ISSUE THREAD

**Issue by Fenix131313** [georgezhao2010/midea_ac_lan#427]
### Intergration version

0.3.22

### Device type and model

Heat Pump Wi-Fi Controller 171H120F

### Used App

MSmartHome

### The description of problem

The outdoor temperature is showing wrong number when its below zero outside.
![Midea](https://github.com/georgezhao2010/midea_ac_lan/assets/32354671/e6e8afe1-f03b-4fe7-96e5-4110ec010db6)

**Comment by Unwies** [comment]
There is a work around, which works:
https://github.com/georgezhao2010/midea_ac_lan/issues/394#issuecomment-1837959454


Work around:
Open file homeassistant/custom_components/midea_ac_lan/midea/devices/c3/message.py and replace line:
self.outdoor_temperature = body[data_offset + 9]

With line:
self.outdoor_temperature = body[data_offset + 9] - 256 if body[data_offset + 9] > 127 else body[data_offset + 9]

**Comment by Fenix131313** [comment]
thank you, it works, i feel stupid now for not searching the comments...
