### ISSUE TITLE
在Hass上添加时出现意外

### ISSUE THREAD

**Issue by EmersonCh1458** [georgezhao2010/midea_ac_lan#43]
如题，显示“此集成不支持通过 UI 配置。如果您是从 Home Assistant 网站点击链接前来，请确保您运行的是最新版本的 Home Assistant。”可我就是最新版了，求解。

版本 | core-2022.7.7
安装类型 | Home Assistant Core
开发版 | false
Supervisor | false
Docker | false
用户 | root
虚拟环境 | true
Python 版本 | 3.9.2
操作系统系列 | Linux
操作系统版本 | 3.10.72+
CPU 架构 | aarch64
时区 | Asia/Shanghai

**Comment by georgezhao2010** [comment]
> 如题，显示“此集成不支持通过 UI 配置。如果您是从 Home Assistant 网站点击链接前来，请确保您运行的是最新版本的 Home Assistant。”可我就是最新版了，求解。
> 
> 版本 | core-2022.7.7 安装类型 | Home Assistant Core 开发版 | false Supervisor | false Docker | false 用户 | root 虚拟环境 | true Python 版本 | 3.9.2 操作系统系列 | Linux 操作系统版本 | 3.10.72+ CPU 架构 | aarch64 时区 | Asia/Shanghai

那就肯定是报错了，给我看看报错的日志呢

**Comment by EmersonCh1458** [comment]
终端爆错是这样的 

> 2022-08-02 15:49:43 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration midea_ac_lan: No module named 'Crypto'

**Comment by EmersonCh1458** [comment]
日志也是这个

> 2022-08-02 15:49:43 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration midea_ac_lan: No module named 'Crypto'

**Comment by georgezhao2010** [comment]
> 终端爆错是这样的
> 
> > 2022-08-02 15:49:43 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration midea_ac_lan: No module named 'Crypto'

啊哈，这个HA是你自己配的环境？Crypto库按理说是默认包含在HA中的。

你这得自己安装这个库了。
在HA的docker中，运行以下命令

```
pip3 install crypto
pip3 install pycryptodome
````

**Comment by EmersonCh1458** [comment]
> 

这确实是我自己配的，但用的是python方式装的（因为是用安卓搭Linux deploy转的）
我去尝试一下🫠

**Comment by EmersonCh1458** [comment]
> > 终端爆错是这样的
> > > 2022-08-02 15:49:43 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration midea_ac_lan: No module named 'Crypto'
> 
> 啊哈，这个HA是你自己配的环境？Crypto库按理说是默认包含在HA中的。
> 
> 你这得自己安装这个库了。 在HA的docker中，运行以下命令
> 
> ```
> pip3 install crypto
> pip3 install pycryptodome
> ```

解决了（其实就是之前忘在python搭的虚拟环境内装crypto和pycryptodome😂）
感谢🙏
