### ISSUE TITLE
[INFO] Collaboration for porting to core

### ISSUE THREAD

**Issue by chemelli74** [georgezhao2010/midea_ac_lan#436]
### Device type and model (or SN)

-

### The description of new feature

Hi @georgezhao2010 , would you evaluate the possibility to include this great integration in HA itself ?

I and @necroneco are willing to partecipate in the journey.
Let us know if it something that is interesting for you as it's for us both.

**Comment by caibinqing** [comment]
Hi @georgezhao2010,
Just checking in to see if you're interested in considering our proposal to integrate this feature into the HA core. 
Looking forward to hearing your thoughts!

**Comment by chemelli74** [comment]
New repo: <https://github.com/wuwentao/midea_ac_lan>
