### ISSUE TITLE
[feature request]自动配置支持指定IP段

### ISSUE THREAD

**Issue by shtingeri** [georgezhao2010/midea_ac_lan#45]
手动模式的一些参数不容易获得。
自动模式很棒，但是在docker容器里有时候不能用（网络不是host）。如果能在让自动模式在指定IP段扫描，就很完美了。

这个类似的[项目](https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan/blob/main/README.md) 可以指定IP网段，但是很可惜国内的账号不能用。

**Comment by georgezhao2010** [comment]
> 手动模式的一些参数不容易获得。 自动模式很棒，但是在docker容器里有时候不能用（网络不是host）。如果能在让自动模式在指定IP段扫描，就很完美了。
> 
> 这个类似的[项目](https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan/blob/main/README.md) 可以指定IP网段，但是很可惜国内的账号不能用。

实际已经支持，只不过我一直没更新到github
![image](https://user-images.githubusercontent.com/27534713/183300474-985d3a6b-f35b-4ffd-8e62-ecde85f0e6ba.png)

**Comment by shtingeri** [comment]
感谢解答
