### ISSUE TITLE
New sensor

### ISSUE THREAD

**Issue by farkinca1971** [georgezhao2010/midea_ac_lan#46]
Hello

Is it possible to implement a new sensor for the power compsuntion perhaps?
The factory app has got this feature, thus I think this data is retrievetable.
Thanks a lot for your hard work :)

Zoltán

**Comment by georgezhao2010** [comment]
> Hello
> 
> Is it possible to implement a new sensor for the power compsuntion perhaps? The factory app has got this feature, thus I think this data is retrievetable. Thanks a lot for your hard work :)
> 
> Zoltán

I have tried this before but my air-conditioner always returns 0, probably my device doesn't support this capability.

I'll implement it in next version, ok?

**Comment by farkinca1971** [comment]
Hello,

Thank You very much for your effort. Fyi, I have a mission2 device. I hope it will work. :)

Zoltán

**Comment by georgezhao2010** [comment]
> Hello,
> 
> Thank You very much for your effort. Fyi, I have a mission2 device. I hope it will work. :)
> 
> Zoltán

Added real-time power sensors in [v0.3.4](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.4)

**Comment by farkinca1971** [comment]
Hello

The power sensors are working perfectly. Thanks a lot ! :)
