### ISSUE TITLE
Cannot retrieve key and token

### ISSUE THREAD

**Issue by mribeiro** [georgezhao2010/midea_ac_lan#48]
I just got a couple ACs from Midea and I'm having a hard time putting them up in home assistant.
I ran `midea-discover` and got the following info:

`INFO:msmart.cli:*** Found a device: {'name': 'net_ac_6F**', 'ssid': 'net_ac_6F**', 'ip': '192.168.21.241', 'port': 6444, 'id': 145***112, 'version': 3, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P****000', 'model': '00Q1B', 'support': True, 'run_test': True}`

As you can see, Key and Token are `None`. Also trying to integrate automatically from Home Assistant UI it stays forever loading.

How can I get the Key and Token? Or what other piece of info can I add so someone can help me?

Thanks!

**Comment by georgezhao2010** [comment]
> I just got a couple ACs from Midea and I'm having a hard time putting them up in home assistant. I ran `midea-discover` and got the following info:
> 
> `INFO:msmart.cli:*** Found a device: {'name': 'net_ac_6F**', 'ssid': 'net_ac_6F**', 'ip': '192.168.21.241', 'port': 6444, 'id': 145***112, 'version': 3, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P****000', 'model': '00Q1B', 'support': True, 'run_test': True}`
> 
> As you can see, Key and Token are `None`. Also trying to integrate automatically from Home Assistant UI it stays forever loading.
> 
> How can I get the Key and Token? Or what other piece of info can I add so someone can help me?
> 
> Thanks!

I've found a small part of devices cannot get the correct TOKEN and KEY,  unfortunately,  your device is one of them.

I've tried to find a solution but have no clue yet, but I'll keep following up on this.

**Comment by mribeiro** [comment]
Hey @georgezhao2010 
So... this is embarrassing. What actually happened is that I was not putting in my credentials. 

Sorry about that.
Closing this off

**Comment by jmdv-es** [comment]
Hi, I'm new to this, I want to find token and key for my device. How should I do this?

This issue mentions the `midea-discover`, where should i run this?

Much thanks.
