### ISSUE TITLE
Deprecated is_aux_heat on climate

### ISSUE THREAD

**Issue by rokam** [georgezhao2010/midea_ac_lan#483]
### HA core version

2024.4.0

### Intergration version

0.3.22

### Device type and model

Any climate

### Used App

Any

### The description of problem

is_aux_heat will not work on climate devices after version 2024.10.0
https://developers.home-assistant.io/blog/2024/03/10/climate-aux-heater-deprecated/

**Comment by Scope666** [comment]
Got a similar warning:
<img width="538" alt="image" src="https://github.com/georgezhao2010/midea_ac_lan/assets/31927547/b87b6ded-e874-4bc5-ad26-5d8cd8ac0f93">

**Comment by paramburu** [comment]
+1

**Comment by acheapshot** [comment]
+1

**Comment by PepPepet** [comment]
+1

**Comment by CyrielRct** [comment]
+1

**Comment by MarkHofmann11** [comment]
+1

**Comment by eucciferri** [comment]
+1

**Comment by zeduperes** [comment]
+1

**Comment by yyb-me** [comment]
+1

**Comment by sboixg** [comment]
+1

**Comment by attilaersek** [comment]
~afaik the #420 will fix it. hope it can be merged soon!~ edit: actually after looking into the change more thoroughly and reading the details of the announced deprecation, the mentioned PR won't fix it. Someone must look into details more.

**Comment by ettiennecoetzee** [comment]
+1

**Comment by litecross91** [comment]
+1

**Comment by kovacsla** [comment]
+1

**Comment by FancyNerd92** [comment]
+1

**Comment by besiktas97** [comment]
Got the same warning from HA

![image](https://github.com/georgezhao2010/midea_ac_lan/assets/76499056/c02e32b7-8573-4191-8478-c4aef7e3a12b)

**Comment by javifly** [comment]
I've come across the same message... we all get it...

**Comment by P1-Ro** [comment]
Guys, please stop spamming "+1" or "same for me". Add reaction to first comment instead, your comments aren't adding anything of value to this issue.

**Comment by Kijan** [comment]
try this fork here:
https://github.com/Necroneco/midea_ac_lan

**Comment by rokam** [comment]
We're maintaining this repo in this fork: https://github.com/wuwentao/midea_ac_lan

**Comment by javifly** [comment]
in the official application there are 2 features that this integration does not have:

1. The option to choose the fan speed from 1% to 1%. That is to say to be able to set the speed to 23% or 31%... here only leaves some preconfigured: Silent 20 - Low 40 - Medium 60 - High 80 - Full 100 - Auto

2. The official application allows you to choose the fixed position of the orientation blades. I.e. you can choose if you want the blades to be fixed in high position or in low position etc... While in this integration you can only choose whether they are moving or stopped. And when you choose stopped they stop in the position in which they are at that moment. It only leaves only the mode of the slider oscillation: Off, Vertical, Horizontal, Both.

do you plan to introduce them in future revisions @rokam y @Kijan ??

**Comment by rokam** [comment]
You need to create an issue in the repo. We're focusing on migrating this to core. But some features can be done.

**Comment by Kijan** [comment]
> in the official application there are 2 features that this integration does not have:
> 
>     1. The option to choose the fan speed from 1% to 1%. That is to say to be able to set the speed to 23% or 31%... here only leaves some preconfigured: Silent 20 - Low 40 - Medium 60 - High 80 - Full 100 - Auto
> 
>     2. The official application allows you to choose the fixed position of the orientation blades. I.e. you can choose if you want the blades to be fixed in high position or in low position etc... While in this integration you can only choose whether they are moving or stopped. And when you choose stopped they stop in the position in which they are at that moment. It only leaves only the mode of the slider oscillation: Off, Vertical, Horizontal, Both.
> 
> 
> do you plan to introduce them in future revisions @rokam y @Kijan ??

it is not my fork. i found it, as i looked for this problem and the solution and because this repo is quiet dead i thought maybe it helps someone xD

**Comment by rokam** [comment]
Necroneco is working in  wuwentao fork
