### ISSUE TITLE
Powering on the AC

### ISSUE THREAD

**Issue by ZoesDev** [georgezhao2010/midea_ac_lan#49]
Is it possible to add the ability to power on the device? I have the midea portable ac and would love to be able to have it turn on and off at a higher temperature then is max on my unit through home assistant. I know the app can do it but wanting to automate this if possible.

**Comment by georgezhao2010** [comment]
> Is it possible to add the ability to power on the device? I have the midea portable ac and would love to be able to have it turn on and off at a higher temperature then is max on my unit through home assistant. I know the app can do it but wanting to automate this if possible.

You mean the service "climate.turn_on"?

Try this[![Service](https://my.home-assistant.io/badges/developer_call_service.svg)](https://my.home-assistant.io/redirect/developer_call_service/?service=climate.turn_on)

**Comment by ZoesDev** [comment]
huh. it showed up on the dashboard after I sent the issue in and I am able to setup automations to turn it on and off. thanks for the awesome integration.

**Comment by georgezhao2010** [comment]
> huh. it showed up on the dashboard after I sent the issue in and I am able to setup automations to turn it on and off. thanks for the awesome integration.

Well, I' ll add a power switch in next version.

**Comment by georgezhao2010** [comment]
Added the power switch in [v0.3.4](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.4)
