### ISSUE TITLE
Device unavailable every few seconds...

### ISSUE THREAD

**Issue by SkinnyT81** [georgezhao2010/midea_ac_lan#50]
I just set this up after coming from your other Midea Integration.  The device did not auto discover, so I added manually.  Everything seems to go through, but the temps are reported incorrectly and then the device is available for about 10 seconds and then becomes unavailable for about 10 more seconds and the cycle completes.   I've tried adding the device with model number unknown as well as the one that auto populates.

**Comment by SkinnyT81** [comment]
I needed to toggle the device on, off and then on and again and it seems to be working now.

**Comment by ihaettypo** [comment]
Same thing here...
