### ISSUE TITLE
“midea_ac_lan”自定义集成使用了已弃用的气候辅助加热器

### ISSUE THREAD

**Issue by warknight1211** [georgezhao2010/midea_ac_lan#514]
### HA版本

2024.5.2

### 集成版本

0.3.22

### 设备类型及型号

Air Conditioner 22012931 (8)

### 使用的App

美的美居

### 问题详细描述

注：（UTC+8）2024.05.10 13:15，无法在HACS内直接下载midea_ac_lan，通过手动下载后，在“配置-设备与服务-集成”中手动安装的。

“midea_ac_lan”自定义集成使用了已弃用的气候辅助加热器
此项在版本 2024.10.0 中无法工作。请在升级之前解决。
自定义集成“midea_ac_lan”实现 is_aux_heat 属性或在 ClimateEntity 的子类中使用辅助加热器方法。

请在 https://github.com/georgezhao2010/midea_ac_lan/issues 创建缺陷报告。

一旦有 midea_ac_lan 的更新版本可用，请安装它并重新启动 Home Assistant 解决此问题。

警告 - 2024/5/10

![1234](https://github.com/georgezhao2010/midea_ac_lan/assets/133470719/187fa86e-a467-4ece-94d8-9db32fded8ca)

**Comment by stkroot** [comment]
我也遇到了这个错误

**Comment by xiaoxiaorolly** [comment]
同遇到此问题+1

**Comment by acbiong** [comment]
同遇到此问题+1

**Comment by ldcz** [comment]
怎么解决

**Comment by rgbyao** [comment]
遇到同样的问题

**Comment by llgxdnn** [comment]
为什么我的错误提示是全英文的，你的是中文的？ @warknight1211

**Comment by mtv890** [comment]
Duplicate: https://github.com/georgezhao2010/midea_ac_lan/issues/483
