### ISSUE TITLE
请问一下有遇到过能成功发现设备 但是在选择设备完设备点击提交就一直没有反应的情况吗

### ISSUE THREAD

**Issue by jhchenchong** [georgezhao2010/midea_ac_lan#52]

**Comment by jhchenchong** [comment]
如果一直等的话 最后会出现这个提示   无法连接美的云获取设备关键信息(Token和Key)

**Comment by jhchenchong** [comment]
不确定是什么问题  修改过源码里的账号跟请求链接之后就可以了

**Comment by georgezhao2010** [comment]
> 

是美的的服务器出问题了一整天，不过你也不用修改请求连接，
改了用户名密码后MIDEA_DEFAULT_SERVER改成"cn"就可以了

**Comment by georgezhao2010** [comment]
> 不确定是什么问题 修改过源码里的账号跟请求链接之后就可以了

是美的的服务器出问题了一整天，不过你也不用修改请求连接，
改了用户名密码后MIDEA_DEFAULT_SERVER改成"cn"就可以了
