### ISSUE TITLE
无法连接美的云获取设备关键信息(Token和Key)

### ISSUE THREAD

**Issue by vipsql** [georgezhao2010/midea_ac_lan#53]
RT:  能搜索到设备，但连接提示无法连接美的云获取设备关键信息(Token和Key)，还需要配置哪些东西

**Comment by georgezhao2010** [comment]
> RT: 能搜索到设备，但连接提示无法连接美的云获取设备关键信息(Token和Key)，还需要配置哪些东西

美的服务器出问题了，你自己编辑一下mideac_ac_lan/const.py文件
改一下下列常量定义,改成这样

MIDEA_DEFAULT_ACCOUNT = "你的用户名"
MIDEA_DEFAULT_PASSWORD = "你的密码"
MIDEA_DEFAULT_SERVER = "cn"

**Comment by vipsql** [comment]
感谢
