### ISSUE TITLE
Home assistant integration warning during install

### ISSUE THREAD

**Issue by rmicheli66** [georgezhao2010/midea_ac_lan#539]
Hello,

this is the warning message I received:

"The custom integration midea_ac_lan implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity."

**Comment by weddle** [comment]
Additionally, I received the warning:

_This stops working in version 2024.10.0. Please address before upgrading._

**Comment by hkusulja** [comment]
Duplicate of 
https://github.com/georgezhao2010/midea_ac_lan/issues/505
Please close this
