### ISSUE TITLE
美的JSQ热水器无法调温

### ISSUE THREAD

**Issue by micturkey** [georgezhao2010/midea_ac_lan#54]
最新版本的Midea ac lan可以接入热水器了，立马下载安装了一下，发现了几个问题：
热水器调温后可以同步至ha，但是ha调温后无法同步至热水器，几秒钟后恢复为热水器之前的温度。
热水器型号为燃气热水器JSQ30-16HC4，可能是set_temperature方法的实现有些问题；
~~然后是Homekit接入的问题，由于本集成的模式选择为 "Shower Mode", "Kitchen Mode", "Bathtub Mode",  "Temperature Mode", "Cloud Mode", "Energy Saving"，并不能严格对应HA默认的模式（参考 https://developers.home-assistant.io/docs/core/entity/water-heater/ ），导致在Homekit中无法选择相应模式，这其实不影响什么，因为模式调节其实也无所谓。但是一个关键问题在于没有提供"STATE_OFF"模式，导致Homekit中会一直显示正在加热，不能显示关闭的状态~~
刚试了试，HA官方接入就没把这个弄明白，不管什么模式都会显示加热，没法关闭😂

**Comment by georgezhao2010** [comment]
> 最新版本的Midea ac lan可以接入热水器了，立马下载安装了一下，发现了几个问题： 热水器调温后可以同步至ha，但是ha调温后无法同步至热水器，几秒钟后恢复为热水器之前的温度。 热水器型号为燃气热水器JSQ30-16HC4，可能是set_temperature方法的实现有些问题； ~然后是Homekit接入的问题，由于本集成的模式选择为 "Shower Mode", "Kitchen Mode", "Bathtub Mode", "Temperature Mode", "Cloud Mode", "Energy Saving"，并不能严格对应HA默认的模式（参考 https://developers.home-assistant.io/docs/core/entity/water-heater/ ），导致在Homekit中无法选择相应模式，这其实不影响什么，因为模式调节其实也无所谓。但是一个关键问题在于没有提供"STATE_OFF"模式，导致Homekit中会一直显示正在加热，不能显示关闭的状态~ 刚试了试，HA官方接入就没把这个弄明白，不管什么模式都会显示加热，没法关闭😂

你要是方便，打开调试模式，然后提供一下调温时的日志看看。

至于States，我倒是没注意，直接按空调的模式写了，以后会改成标准返回。

**Comment by micturkey** [comment]
> > 最新版本的Midea ac lan可以接入热水器了，立马下载安装了一下，发现了几个问题： 热水器调温后可以同步至ha，但是ha调温后无法同步至热水器，几秒钟后恢复为热水器之前的温度。 热水器型号为燃气热水器JSQ30-16HC4，可能是set_temperature方法的实现有些问题； ~然后是Homekit接入的问题，由于本集成的模式选择为 "Shower Mode", "Kitchen Mode", "Bathtub Mode", "Temperature Mode", "Cloud Mode", "Energy Saving"，并不能严格对应HA默认的模式（参考 https://developers.home-assistant.io/docs/core/entity/water-heater/ ），导致在Homekit中无法选择相应模式，这其实不影响什么，因为模式调节其实也无所谓。但是一个关键问题在于没有提供"STATE_OFF"模式，导致Homekit中会一直显示正在加热，不能显示关闭的状态~ 刚试了试，HA官方接入就没把这个弄明白，不管什么模式都会显示加热，没法关闭😂
> 
> 你要是方便，打开调试模式，然后提供一下调温时的日志看看。
> 
> 至于State，我倒是没注意，直接按空调的模式写了，以后会改成标准返回。

我有空的时候试一下发上来

**Comment by georgezhao2010** [comment]
> > > 最新版本的Midea ac lan可以接入热水器了，立马下载安装了一下，发现了几个问题： 热水器调温后可以同步至ha，但是ha调温后无法同步至热水器，几秒钟后恢复为热水器之前的温度。 热水器型号为燃气热水器JSQ30-16HC4，可能是set_temperature方法的实现有些问题； ~然后是Homekit接入的问题，由于本集成的模式选择为 "Shower Mode", "Kitchen Mode", "Bathtub Mode", "Temperature Mode", "Cloud Mode", "Energy Saving"，并不能严格对应HA默认的模式（参考 https://developers.home-assistant.io/docs/core/entity/water-heater/ ），导致在Homekit中无法选择相应模式，这其实不影响什么，因为模式调节其实也无所谓。但是一个关键问题在于没有提供"STATE_OFF"模式，导致Homekit中会一直显示正在加热，不能显示关闭的状态~ 刚试了试，HA官方接入就没把这个弄明白，不管什么模式都会显示加热，没法关闭😂
> > 
> > 
> > 你要是方便，打开调试模式，然后提供一下调温时的日志看看。
> > 至于State，我倒是没注意，直接按空调的模式写了，以后会改成标准返回。
> 
> 我有空的时候试一下发上来

我个人没有美的热水器，但我让别人拍了一下视频，是可以正常调整温度的。

https://user-images.githubusercontent.com/27534713/184384072-69dc7012-9566-4cb2-8bba-06e0dfcff3ae.mp4

**Comment by georgezhao2010** [comment]
> 

我个人没有美的热水器，但我让人拍了一下视频，v0.3.4可以正常调整燃气热水器水温。

https://user-images.githubusercontent.com/27534713/184384351-cfb9208e-fb8b-4f2c-a2a6-570b928ff561.mp4

**Comment by georgezhao2010** [comment]
> ...
> 
> 我有空的时候试一下发上来

我个人没有美的热水器，但我让人拍了一下视频，v0.3.4可以正常调整燃气热水器水温。

https://user-images.githubusercontent.com/27534713/184384922-e835681f-9ea7-44aa-83c8-91b8f0e2cc4b.mp4

**Comment by georgezhao2010** [comment]
另一台LSQ21系列的同报无法调整温度，目前没有找到原因

**Comment by georgezhao2010** [comment]
应该是不同的Subtype的热水器使用的控制协议不同，该子型号热水器使用了更新的协议。

应该可以解决。

**Comment by micturkey** [comment]
> 应该是不同的Subtype的热水器使用的控制协议不同，该子型号热水器使用了更新的协议。
> 
> 应该可以解决。

我又去看了一下log，结果如下：

> 2022-08-28 20:34:52.048 DEBUG (SyncWorker_3) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa0ce3ef000000000002', 'body': '0101', 'message type': '02', 'body type': '01'}
2022-08-28 20:34:52.230 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000002', 'body': '01010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '02', 'body type': '01'}
2022-08-28 20:34:52.230 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
2022-08-28 20:34:57.235 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa0ce3ef000000000003', 'body': '0101', 'message type': '03', 'body type': '01'}
2022-08-28 20:34:57.451 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000003', 'body': '01010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '03', 'body type': '01'}
2022-08-28 20:34:57.451 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
2022-08-28 20:34:58.332 DEBUG (SyncWorker_12) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa1ee3fd000000000002', 'body': '04010200002b0000000000000000000000000000', 'message type': '02', 'body type': '04'}
2022-08-28 20:34:58.545 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000002', 'body': '04010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '02', 'body type': '04'}
2022-08-28 20:34:58.546 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}

**Comment by georgezhao2010** [comment]
> > 应该是不同的Subtype的热水器使用的控制协议不同，该子型号热水器使用了更新的协议。
> > 应该可以解决。
> 
> 我又去看了一下log，结果如下：
> 
> ```
> 2022-08-28 20:34:52.048 DEBUG (SyncWorker_3) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa0ce3ef000000000002', 'body': '0101', 'message type': '02', 'body type': '01'}
> 2022-08-28 20:34:52.230 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000002', 'body': '01010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '02', 'body type': '01'}
> 2022-08-28 20:34:52.230 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
> 2022-08-28 20:34:57.235 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa0ce3ef000000000003', 'body': '0101', 'message type': '03', 'body type': '01'}
> 2022-08-28 20:34:57.451 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000003', 'body': '01010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '03', 'body type': '01'}
> 2022-08-28 20:34:57.451 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
> 2022-08-28 20:34:58.332 DEBUG (SyncWorker_12) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa1ee3fd000000000002', 'body': '04010200002b0000000000000000000000000000', 'message type': '02', 'body type': '04'}
> 2022-08-28 20:34:58.545 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000002', 'body': '04010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '02', 'body type': '04'}
> 2022-08-28 20:34:58.546 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
> ```

Update to [v0.3.10](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.10) and see if the problem is solved.

**Comment by micturkey** [comment]
> > > 应该是不同的Subtype的热水器使用的控制协议不同，该子型号热水器使用了更新的协议。
> > > 应该可以解决。
> > 
> > 
> > 我又去看了一下log，结果如下：
> > ```
> > 2022-08-28 20:34:52.048 DEBUG (SyncWorker_3) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa0ce3ef000000000002', 'body': '0101', 'message type': '02', 'body type': '01'}
> > 2022-08-28 20:34:52.230 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000002', 'body': '01010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '02', 'body type': '01'}
> > 2022-08-28 20:34:52.230 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
> > 2022-08-28 20:34:57.235 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa0ce3ef000000000003', 'body': '0101', 'message type': '03', 'body type': '01'}
> > 2022-08-28 20:34:57.451 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000003', 'body': '01010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '03', 'body type': '01'}
> > 2022-08-28 20:34:57.451 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
> > 2022-08-28 20:34:58.332 DEBUG (SyncWorker_12) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Sending: {'header': 'aa1ee3fd000000000002', 'body': '04010200002b0000000000000000000000000000', 'message type': '02', 'body type': '04'}
> > 2022-08-28 20:34:58.545 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.devices.e3.device] [196812582857183] Received: {'header': 'aa2fe300000000000002', 'body': '04010900081c29000000000000001c14000010000001282a00001c000000000000000000', 'message type': '02', 'body type': '04'}
> > 2022-08-28 20:34:58.546 DEBUG (美的热水器) [custom_components.midea_ac_lan.midea.core.device] [196812582857183] Status update: {'power': True, 'burning_state': False, 'zero_cold_water': False, 'mode': 0, 'protection': False, 'zero_cold_pulse': False, 'smart_volume': False, 'temperature': 28, 'target_temperature': 41}
> > ```
> 
> Update to [v0.3.10](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.10) and see if the problem is solved.

更新过后，开机后数秒内调整温度是可行的，数秒过后或者调整过后，就和之前一样，无法调温。

**Comment by micturkey** [comment]
更新至0.3.12后并使用https://github.com/georgezhao2010/midea_ac_lan/pull/92中的修复方式后温度可以调整了，谢谢！
