### ISSUE TITLE
大佬，中央空调能否通过一个X86控制器，实现其它房间的设备控制。

### ISSUE THREAD

**Issue by love768952693** [georgezhao2010/midea_ac_lan#55]
先谢谢大佬的插件，终于可以在HA中控制86面板了。

我家里是有一个面板是带wifi的，其它3个房间都是不带wifi的，之前抓包好像有看到其它房间的设备，所以想问大佬，能否通过一个设置后控制其它的中央风管机。

**Comment by georgezhao2010** [comment]
> 先谢谢大佬的插件，终于可以在HA中控制86面板了。
> 
> 我家里是有一个面板是带wifi的，其它3个房间都是不带wifi的，之前抓包好像有看到其它房间的设备，所以想问大佬，能否通过一个设置后控制其它的中央风管机。

既然不带wifi，你怎么能看到其它设备的包的？你其它设备美居能控制吗？

你这种情况，要么使用诸如CCM15或者GA104之类的空调网关（CCM15还有GA104都有现成的接入方案），要么换上WIFI面板，我觉得是这样的。

**Comment by love768952693** [comment]
> > 先谢谢大佬的插件，终于可以在HA中控制86面板了。
> > 我家里是有一个面板是带wifi的，其它3个房间都是不带wifi的，之前抓包好像有看到其它房间的设备，所以想问大佬，能否通过一个设置后控制其它的中央风管机。
> 
> 既然不带wifi，你怎么能看到其它设备的包的？你其它设备美居能控制吗？
> 
> 你这种情况，要么使用诸如CCM15或者GA104之类的空调网关（CCM15还有GA104都有现成的接入方案），要么换上WIFI面板，我觉得是这样的。


好像是wifi的这个连接某台内机之后，其它的设备通讯也可以监听到，这块我不是太懂，我也是感觉好像发现新大陆了一样，估计空调可能都是这么设计的，也许是为了方便他们自己家的X86那款集中控制面板吧，或者又是为了互相通信还是啥的。。。。VRF的逻辑好像也是这样的。。。。

要是我说得不对，还望大佬指点哈，还是要谢谢大佬提供的库的。

**Comment by georgezhao2010** [comment]
> 



> > > 先谢谢大佬的插件，终于可以在HA中控制86面板了。
> > > 我家里是有一个面板是带wifi的，其它3个房间都是不带wifi的，之前抓包好像有看到其它房间的设备，所以想问大佬，能否通过一个设置后控制其它的中央风管机。
> > 
> > 
> > 既然不带wifi，你怎么能看到其它设备的包的？你其它设备美居能控制吗？
> > 你这种情况，要么使用诸如CCM15或者GA104之类的空调网关（CCM15还有GA104都有现成的接入方案），要么换上WIFI面板，我觉得是这样的。
> 
> 好像是wifi的这个连接某台内机之后，其它的设备通讯也可以监听到，这块我不是太懂，我也是感觉好像发现新大陆了一样，估计空调可能都是这么设计的，也许是为了方便他们自己家的X86那款集中控制面板吧，或者又是为了互相通信还是啥的。。。。VRF的逻辑好像也是这样的。。。。
> 
> 要是我说得不对，还望大佬指点哈，还是要谢谢大佬提供的库的。

你说的东西我也不了解啊，你看比如使用midea-discovery命令能不能搜到设备呢，能搜到就可以，不能的话，那就不能支持了。
