### ISSUE TITLE
Cannot access on climate entities throght template or python script

### ISSUE THREAD

**Issue by Rihan9** [georgezhao2010/midea_ac_lan#554]
### HA core version

2024.6.4

### Intergration version

v0.3.22

### Device type and model

Air Conditioner 00000Q1B (0)

### Used App

Carrier air conditioner

### The description of problem

Hi,
to prevent an automation to turn on and off the climate continuously, I need to access the last_changed attribute throght this:

`states.climate.153931628036068_climate.last_changed`

but neiter in template nor in python script the command works. I got the following error:
`expected token 'end of print statement', got '_climate'`

I tried the same command with a generic light and works. Can you please help me?

Thanks and Regards

**Comment by rokam** [comment]
https://github.com/wuwentao/midea_ac_lan/
