### ISSUE TITLE
> > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码版本过此

### ISSUE THREAD

**Issue by squallyjy** [georgezhao2010/midea_ac_lan#571]
> > 这个问题我已经解决了，手动修改const配置为“美居”而不是“cn”就能正常登录（不行的话要清理一下ha的缓存），估计源码版本过此
> 
> 正解。const.py 文件中新增 3 行。账号密码对应位置替换下。 MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao' MIDEA_DEFAULT_PASSWORD = 'nidemima' MIDEA_DEFAULT_SERVER = "美居"

更正一下，第三行的“美居”无法正常打开
应该为：
MIDEA_DEFAULT_ACCOUNT = 'nidezhanghao'
MIDEA_DEFAULT_PASSWORD = 'nidemima'
MIDEA_DEFAULT_SERVER = "美的美居"

_Originally posted by @SongYoungLv in https://github.com/georgezhao2010/midea_ac_lan/issues/418#issuecomment-2185322478_
         
在此基础上试了还是不行。
后来进.storage/midea_ac_lan然后删除account.json，再去添加新设备的时候重新输了账号密码然后选择美的美居，登陆成功了。。。

试了一下，在此基础上，

**Comment by GordonYoungCao** [comment]
.storage/midea_ac_lan 它的完整 路径是什么

**Comment by liuyu1483** [comment]
.storage/midea_ac_lan在哪里啊
