### ISSUE TITLE
WAHIN N8HE1 get token and key but could not add integrate

### ISSUE THREAD

**Issue by ericcug** [georgezhao2010/midea_ac_lan#58]
Manual add parameters did not solve this problem.
Here is the log output from HA:

> 2022-08-14 12:17:52.332 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Received broadcast from ('192.168.*.*', 6445): ***
> 2022-08-14 12:17:52.332 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Declassified reply: ***
> 2022-08-14 12:17:52.332 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.discover] Found a supported device: {'device_id': 18361844286****, 'type': 172, 'ip_address': '192.168.*.*', 'port': 6444, 'model': '40023', 'protocol': 3}
> 2022-08-14 12:18:10.707 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.cloud] Endpoint: /v1/user/login/id/get, Response: b'{"code":0,"msg":null,"data":{"loginId":"****"}}'
> 2022-08-14 12:18:11.255 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.cloud] Endpoint: /mj/user/login, Response: b'{"code":0,"msg":"\xe6\x88\x90\xe5\x8a\x9f","data":{"uid":"***","userInfo":{"birthday":null,"mail":null,"signature":null,"homeName":null,"phone2":null,"phone3":null,"uid":"***","homeCode":null,"isWeixin":"0","cardid":null,"isQq":"0","brand":"1","isApple":"1","registerTime":"***","nickName":"****","sex":null,"mobile":"****","userId":"****","headImgUrl":"https://fcmms.midea.com/ccrm-beta/userHeadImg/defaultHeadImg.png","phone":null,"name":null,"mipUser":null,"isUpdateCacheTime":1,"age":null,"account":null},"iotUserId":****,"mdata":{"tokenPwdInfo":{"tokenPwd":"3****","expiredDate":1663071491240,"createDate":1660479491240},"userInfo":{"sourceId":"mj_12345","empId":"488602931024****","address":"","gender":"0","mobile":"****","userDeptInfoList":null,"extras":null,"nameEn":null,"employeeNumber":null,"headPhoto":null,"uid":"****","name":"****","email":null},"doDeviceBind":null,"accessToken":"****","signUnlockEnabled":null},"jwtToken":null,"clusterId":65793,"isOldUse":null,"key":"****"}}'
> 2022-08-14 12:18:11.255 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.cloud] The udpid of deivce [18361844286****] generated with byte order 'little': ****
> 2022-08-14 12:18:11.306 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.cloud] Endpoint: /v1/iot/secure/getToken, Response: b'{"code":0,"msg":null,"data":{"tokenlist":[{"key":"(key)","token":"(token)"}]}}'
> 2022-08-14 12:18:11.307 DEBUG (MainThread) [custom_components.midea_ac_lan.config_flow] Successful to take token and key, token: ****, key: ****, byte_order_big: False
> 2022-08-14 12:18:11.310 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.device] [18361844286****] Connected
> 2022-08-14 12:18:11.310 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.device] [18361844286****] Handshaking
> 2022-08-14 12:18:11.360 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.device] [18361844286****] Authentication failed
> 2022-08-14 12:18:11.360 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.cloud] The udpid of deivce [18361844286****] generated with byte order 'big': ****
> 2022-08-14 12:18:11.426 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.cloud] Endpoint: /v1/iot/secure/getToken, Response: b'{"code":0,"msg":null,"data":{"tokenlist":[{"key":"(key)","token":"(token))","udpId":"(udpid))"}]}}'
> 2022-08-14 12:18:11.427 DEBUG (MainThread) [custom_components.midea_ac_lan.config_flow] Successful to take token and key, token: (token), key: (key), byte_order_big: True
> 2022-08-14 12:18:11.430 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.device] [18361844286****] Connected
> 2022-08-14 12:18:11.430 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.device] [18361844286****] Handshaking
> 2022-08-14 12:18:11.487 DEBUG (MainThread) [custom_components.midea_ac_lan.midea.core.device] [18361844286****] Authentication failed

**Comment by georgezhao2010** [comment]
> ....

I've found a small part of devices cannot get the correct TOKEN and KEY via Midea cloud. may your device is one of them.

If you are in mainland China and your device is already registered via 美居, contact me on QQ(3325350), I'll send you earlier version 美居 app to get the correct TOKEN and KEY.

**Comment by ericcug** [comment]
solved by capture log for correct token and k1 from MeiJu App android earlier version ( provided by @mac-zhao ) multiple times.
