### ISSUE TITLE
添加集成的时候提示 **错误** 无法加载配置向导：undefined

### ISSUE THREAD

**Issue by Chenkb94** [georgezhao2010/midea_ac_lan#60]
大佬救救孩子，在hacs更新集成后空调集成变成未加载状态，删除重新安装，添加集成的时候提示 **错误** 无法加载配置向导：undefined
![微信图片_20220816004237](https://user-images.githubusercontent.com/69777257/184678063-0c3d3c79-2615-4c1d-8c01-29bca6deef4c.png)

**Comment by georgezhao2010** [comment]
> 

应该不用看日志我就知道你这问题大概是什么。

HA还是非常古老的版本吧？

**Comment by Chenkb94** [comment]
> > 
> 
> 应该不用看日志我就知道你这问题大概是什么。
> 
> HA还是比较早的版本吧，升级到最新的HA试试看。

大佬，之前是2022-3月的docker版本，本来可以用的，但是更新了集成就出问题了，我还在另一台主机更了最新的2022-8-4的版本还是一样0.0. 然后删除集成后重新在hacs下载选择以前的版本还是一样的问题。

**Comment by georgezhao2010** [comment]
> > > 
> > 
> > 
> > 应该不用看日志我就知道你这问题大概是什么。
> > HA还是比较早的版本吧，升级到最新的HA试试看。
> 
> 大佬，之前是2022-3月的docker版本，本来可以用的，但是更新了集成就出问题了，我还在另一台主机更了最新的2022-8-4的版本还是一样0.0. 然后删除集成后重新在hacs下载选择以前的版本还是一样的问题。

那这样，你在2022.8的那台，打开调试日志，然后配置一次，然后贴出日志的错误信息。

**Comment by Chenkb94** [comment]
> 
大佬，这个是日志 ，有两个报错日志。

第一个日志
Logger: homeassistant.util.package
Source: util/package.py:98
First occurred: 21:55:22 (3 occurrences)
Last logged: 21:55:48

Unable to install package crypto: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f408d32e350>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f408d32e5f0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f408d32e890>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f408d32ea40>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f408d32ec20>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f408d32ed70>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Unable to install package crypto: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0257db2440>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0257db26e0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0257db2980>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0257db2b30>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0257db2d10>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f0257db2e60>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
Unable to install package crypto: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fba266d60b0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fba266d72b0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fba266d4c10>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fba266d6ce0>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fba266d5f30>: Failed to establish a new connection: [Errno -2] Name does not resolve')': /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/fc/bb/0b812dc02e6357606228edfbf5808f5ca0a675a84273578c3a199e841cd8/crypto-1.4.1-py2.py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fba266d57e0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

第二个日志
Logger: aiohttp.server
Source: requirements.py:267
First occurred: 21:55:48 (1 occurrences)
Last logged: 21:55:48

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 222, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 240, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 791, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 362, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 49, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 236, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 267, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for midea_ac_lan not found: ['crypto'].

**Comment by georgezhao2010** [comment]
> > 
> 
> 大佬，这个是日志 ，有两个报错日志。
> 
> ...

我了解了，你这是安装加解密库失败，我给你升级一个版本好了， 你回头升级v0.3.5

**Comment by Chenkb94** [comment]
> > 大佬，这个是日志 ，有两个报错日志。
> > ...
> 
> 我了解了，你这是安装加解密库失败，我给你升级一个版本好了， 你回头升级[v0.3.5](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.5)

感谢大佬🙏，解决了！
