### ISSUE TITLE
feature request: 允许设置温度步长

### ISSUE THREAD

**Issue by ihaettypo** [georgezhao2010/midea_ac_lan#62]
现在好像温度步长默认是0.5度？但是有的空调步长是1度

**Comment by georgezhao2010** [comment]
我在想这个设置能给你加在哪呢？

**Comment by ihaettypo** [comment]
我看一般都是在集成配置那里，就是这个集成点configure以后选需要哪些sensors 和 switches那里

**Comment by georgezhao2010** [comment]
It has been implemented in v0.3.16
