### ISSUE TITLE
[URGENT]– many deprecations - is this repo still maintained ?

### ISSUE THREAD

**Issue by jmcollin78** [georgezhao2010/midea_ac_lan#624]
### HA core version

2024.12.4

### Intergration version

any

### Device type and model

Any

### Used App

Any

### The description of problem

This still seems abandoned. Some important deprecation will occurs on 2025.1 major release. We need a quick and important update.

So the question is: is this repo still maintained ?

Should we switch to another one ? If yes, can you provide a link to a new repo ?

**Comment by sibest19** [comment]
Hello! See #595

**Comment by jmcollin78** [comment]
Thank you @sibest19. I will switch.

**Comment by jmcollin78** [comment]
It is working fine. Thank you.
