### ISSUE TITLE
Midea AC nightlight switch not working

### ISSUE THREAD

**Issue by rokam** [georgezhao2010/midea_ac_lan#63]
![image](https://user-images.githubusercontent.com/2856518/185230743-78f79a4c-3277-4c58-a545-f08b1a655a8b.png)
Nothing happens when I flick the nightlight switch. When the prompt_tone is on, I flick the nightlight and the appliance beeps, but the switch comes back to off position.

**Comment by georgezhao2010** [comment]
I checked code, it's correct.

Could you try the screen display switch to see if the night light can be turned on and off?

**Comment by rokam** [comment]
I think thats what I've tried.
[Gravação de tela de 18-08-2022 17:24:40.webm](https://user-images.githubusercontent.com/2856518/185488153-bf18b9f6-3c7b-4c7e-ae4a-e1b8a60ee01f.webm)

**Comment by IGaMbLeRI** [comment]
Neither "Night Light" nor "Screen Display" functions work for me to control the front panel LED on my A/C units. I have some information in the now [Closed Issue(s)](https://github.com/georgezhao2010/midea_ac_lan/issues/44).

It would be really nice to have control over this feature, for sleep. If I can provide any information of use to you, please let me know.

**Comment by rokam** [comment]
Yeah, both features doesn't work. It looks like the A/C doesn't aknowledge the command and remains the previous state.

**Comment by rokam** [comment]
@georgezhao2010 is there a way to identify which sensors are available with the AC appliance?

**Comment by georgezhao2010** [comment]
> @georgezhao2010 is there a way to identify which sensors are available with the AC appliance?

There is a command to request features supported by AC. Unfortunately, it itself is not supported by all ACs.

Your can try it on your own deivce

```
class MessageFeatureQuery(MessageACBase):
    def __init__(self):
        super().__init__(
            message_type=MessageType.query,
            body_type=0xb5
        )

    @property
    def _body(self):
        return bytes([
            0x01, 0x11
        ])
```

**Comment by georgezhao2010** [comment]
> @georgezhao2010 is there a way to identify which sensors are available with the AC appliance?

There is a command to request features supported by AC, the funny thing is itself is can't be supported by all ACs.

You can try it on your own AC:

```
class MessageFeatureQuery(MessageACBase):
    def __init__(self):
        super().__init__(
            message_type=MessageType.query,
            body_type=0xb5
        )

    @property
    def _body(self):
        return bytes([
            0x01, 0x11
        ])
```

**Comment by georgezhao2010** [comment]
> ![image](https://user-images.githubusercontent.com/2856518/185230743-78f79a4c-3277-4c58-a545-f08b1a655a8b.png) Nothing happens when I flick the nightlight switch. When the prompt_tone is on, I flick the nightlight and the appliance beeps, but the switch comes back to off position.

I used the new protocol to control the light switch, update to [v0.3.10](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.10) and see if it works.

**Comment by IGaMbLeRI** [comment]
Updated. Reconfigured the integration for the selected unit to include "Night Light" and "Screen Display". Neither worked for me to switch off Inventor O3MVI32's front panel light/display.

**Comment by georgezhao2010** [comment]
> Updated. Reconfigured the integration for the selected unit to include "Night Light" and "Screen Display". Neither worked for me to switch off Inventor O3MVI32's front panel light/display.

OK, I need your SN of appliance.

**Comment by georgezhao2010** [comment]
> Updated. Reconfigured the integration for the selected unit to include "Night Light" and "Screen Display". Neither worked for me to switch off Inventor O3MVI32's front panel light/display.

And, the "Night Light" and "Screen Display" switches can control via MSmartHome app?

**Comment by georgezhao2010** [comment]
> Updated. Reconfigured the integration for the selected unit to include "Night Light" and "Screen Display". Neither worked for me to switch off Inventor O3MVI32's front panel light/display.

BTW, can the "night light" and "screen display" switches be controlled from the MSmarHome app?

**Comment by IGaMbLeRI** [comment]
SN: 3405440100184090831176

No, I do not actually have those switches in MSmartHome app.

**Comment by georgezhao2010** [comment]
> SN: 3405440100184090831176
> 
> No, I do not actually have those switches in MSmartHome app.

Maybe these switches can not be controlled over the network.

**Comment by IGaMbLeRI** [comment]
That was SN from the sticker on the unit, maybe wrong. I just ran midea-discover and saw this:
```
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'name': 'net_ac_4047', 'ssid': 'net_ac_4047', 'ip': '192.168.10.28', 'port': 6444, 'id': 16492674483964, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P0000000Q1F0C9D1BF40470000', 'model': '00Q1F', 'support': True, 'run_test': True} ←[0m
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'name': 'net_ac_1152', 'ssid': 'net_ac_1152', 'ip': '192.168.10.27', 'port': 6444, 'id': 18691697749164, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P0000000Q1F0C9D1C011520000', 'model': '00Q1F', 'support': True, 'run_test': True} ←[0m
INFO:msmart.cli:*** Found a device: ←[94m←[1m{'name': 'net_ac_CC24', 'ssid': 'net_ac_CC24', 'ip': '192.168.10.26', 'port': 6444, 'id': 18691697749179, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P0000000Q1F0C9D1BFCC240000', 'model': '00Q1F', 'support': True, 'run_test': True} ←[0m
```

**Comment by georgezhao2010** [comment]
> That was SN from the sticker on the unit, maybe wrong. I just ran midea-discover and saw this:
> 
> ```
> INFO:msmart.cli:*** Found a device: ←[94m←[1m{'name': 'net_ac_4047', 'ssid': 'net_ac_4047', 'ip': '192.168.10.28', 'port': 6444, 'id': 16492674483964, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P0000000Q1F0C9D1BF40470000', 'model': '00Q1F', 'support': True, 'run_test': True} ←[0m
> INFO:msmart.cli:*** Found a device: ←[94m←[1m{'name': 'net_ac_1152', 'ssid': 'net_ac_1152', 'ip': '192.168.10.27', 'port': 6444, 'id': 18691697749164, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P0000000Q1F0C9D1C011520000', 'model': '00Q1F', 'support': True, 'run_test': True} ←[0m
> INFO:msmart.cli:*** Found a device: ←[94m←[1m{'name': 'net_ac_CC24', 'ssid': 'net_ac_CC24', 'ip': '192.168.10.26', 'port': 6444, 'id': 18691697749179, 'version': 2, 'token': None, 'key': None, 'type': 'ac', 'sn': '000P0000000Q1F0C9D1BFCC240000', 'model': '00Q1F', 'support': True, 'run_test': True} ←[0m
> ```

I'll remove night light switch on next update.
