### ISSUE TITLE
NameError: name 'ClimateEntityFeature' is not defined

### ISSUE THREAD

**Issue by zanderpu** [georgezhao2010/midea_ac_lan#64]
Logger: homeassistant
Source: custom_components/midea_ac_lan/climate.py:56
Integration: Midea AC LAN ([documentation](https://github.com/georgezhao2010/midea_ac_lan), [issues](https://github.com/georgezhao2010/midea_ac_lan/issues))
First occurred: 13:19:04 (22 occurrences)
Last logged: 13:26:01
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 224, in capability_attributes
    supported_features = self.supported_features
  File "/config/custom_components/midea_ac_lan/climate.py", line 56, in supported_features
    return ClimateEntityFeature.TARGET_TEMPERATURE | \
NameError: name 'ClimateEntityFeature' is not defined

**Comment by georgezhao2010** [comment]
> Logger: homeassistant Source: custom_components/midea_ac_lan/climate.py:56 Integration: Midea AC LAN ([documentation](https://github.com/georgezhao2010/midea_ac_lan), [issues](https://github.com/georgezhao2010/midea_ac_lan/issues)) First occurred: 13:19:04 (22 occurrences) Last logged: 13:26:01 Error doing job: Task exception was never retrieved
> 
> Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in async_update_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in _async_write_ha_state attr = self.capability_attributes File "/usr/src/homeassistant/homeassistant/components/climate/**init**.py", line 224, in capability_attributes supported_features = self.supported_features File "/config/custom_components/midea_ac_lan/climate.py", line 56, in supported_features return ClimateEntityFeature.TARGET_TEMPERATURE | NameError: name 'ClimateEntityFeature' is not defined

Update your HA to newest version.
