### ISSUE TITLE
Feature request: Ionization / "FRESH" mode

### ISSUE THREAD

**Issue by IGaMbLeRI** [georgezhao2010/midea_ac_lan#67]
Some models of Midea (and other compatible brands) A/C and (de)humidifier units have option to switch on **Ionization** by pressing a button called "FRESH" on the remote control. For example, if you see [this manual](https://github.com/georgezhao2010/midea_ac_lan/files/9387140/13639883_msfaau-12hrfn8-qrd6gw.pdf) for what seems to be BreezeleSS+, on PDF Page 8, you will see how it indicates that the Ionization mode is working - leaf icon on the LED panel.

I personally have [a different A/C brand and model](https://www.climatecnica.gr/images/pdf/OMNIA_ECO_03MVI32_UM.pdf) but it also has that same "FRESH" feature that is present in many other Midea devices of different classes.

Is it possible to have this feature added for compatible devices with a toggle, just like "ECO Mode", "Prompt Tone", "Swing Vertical" etc?

Kind regards.

**Comment by netmb** [comment]
Any news on this one? I think more and more midea-ACs are delivered with Ionization. On the remote its called "air magic".

**Comment by Jokeru18** [comment]
I'm also interested in this but as I see not even the Midea mobile app has this option. Currently the only option to turn on air magic is the remote control.

**Comment by georgezhao2010** [comment]
I’m sorry, but I believe this feature is unnecessary and I don’t foresee myself investing effort into it.

**Comment by m4rkireland** [comment]
Hi - any chance you could reconsider this please?

**Comment by georgezhao2010** [comment]
> Hi - any chance you could reconsider this please?

What is the feature you want?

**Comment by m4rkireland** [comment]
As the comments from other people above: the ability to control the ionisation feature. On my remote it's called 'Air Magic'.

Thanks

**Comment by georgezhao2010** [comment]
> As the comments from other people above: the ability to control the ionisation feature. On my remote it's called 'Air Magic'.
> 
> Thanks

Well, can this feature be controlled from the app, or can it only be controlled by the remote?

And, please tell me the model of device showing in "Settings -> Devices & Services -> Midea AC LAN -> Devices -> Device Info".

**Comment by m4rkireland** [comment]
I can only find it on the remote, however perhaps we should wireshark this to see if the device puts out anything on the network once the remote button has been pressed?

For me, my device is:
`Air Conditioner 00000Q1B`

Thanks for looking into this.

**Comment by m4rkireland** [comment]
Any chance of considering this again?  Is there anything I can do to help you?

**Comment by m4rkireland** [comment]
Hi @georgezhao2010, any chance of considering this again? Is there anything I can do to help you? Thanks
