### ISSUE TITLE
Is it possible to support MIDEA RO Water Purifiers? 可以增加对美的反渗透净水器的支持么？

### ISSUE THREAD

**Issue by DesmondDu** [georgezhao2010/midea_ac_lan#77]
Is it possible to support MIDEA RO Water Purifiers?  I am glad to provide my MSmartHome account. 
可以增加对美的反渗透净水器的支持么？我很乐意提供我的美的美居的账号。

**Comment by georgezhao2010** [comment]
> Is it possible to support MIDEA RO Water Purifiers? I am glad to provide my MSmartHome account. 可以增加对美的反渗透净水器的支持么？我很乐意提供我的美的美居的账号。

这玩意除了提醒你换滤芯以外，还有其他接入HA的充足理由吗？

设备类型是'ED'，对吗？

**Comment by DesmondDu** [comment]
midea_ed_0410

**Comment by DesmondDu** [comment]
> > Is it possible to support MIDEA RO Water Purifiers? I am glad to provide my MSmartHome account. 可以增加对美的反渗透净水器的支持么？我很乐意提供我的美的美居的账号。
> 
> 这玩意除了提醒你换滤芯以外，还有其他接入HA的充足理由吗？
> 
> 设备类型是'ED'，对吗？

midea_ed_0410

**Comment by georgezhao2010** [comment]
> > > Is it possible to support MIDEA RO Water Purifiers? I am glad to provide my MSmartHome account. 可以增加对美的反渗透净水器的支持么？我很乐意提供我的美的美居的账号。
> > 
> > 
> > 这玩意除了提醒你换滤芯以外，还有其他接入HA的充足理由吗？
> > 设备类型是'ED'，对吗？
> 
> midea_ed_0410

你加我一下QQ3325350回头要做我好找得到人测试

**Comment by ettingshausen** [comment]
> > Is it possible to support MIDEA RO Water Purifiers? I am glad to provide my MSmartHome account. 可以增加对美的反渗透净水器的支持么？我很乐意提供我的美的美居的账号。
> 
> 这玩意除了提醒你换滤芯以外，还有其他接入HA的充足理由吗？
> 
> 设备类型是'ED'，对吗？

还可以统计每天的用水量，:p

**Comment by georgezhao2010** [comment]
Supported in v0.3.14
