### ISSUE TITLE
期待添加美的水机支持，附带lua文件

### ISSUE THREAD

**Issue by tufeikafei** [georgezhao2010/midea_ac_lan#78]
类型CF
感觉这个比较复杂

[T_0000_CF_4.zip](https://github.com/georgezhao2010/midea_ac_lan/files/9435042/T_0000_CF_4.zip)

**Comment by georgezhao2010** [comment]
> 类型CF 感觉这个比较复杂
> 
> [T_0000_CF_4.zip](https://github.com/georgezhao2010/midea_ac_lan/files/9435042/T_0000_CF_4.zip)

给个具体型号，有说明书更好，水机不太熟，我先看看分机控制逻辑。

**Comment by georgezhao2010** [comment]
> 类型CF 感觉这个比较复杂
> 
> [T_0000_CF_4.zip](https://github.com/georgezhao2010/midea_ac_lan/files/9435042/T_0000_CF_4.zip)

初步看了一下，还可以，但有些问题要请教，你加我QQ3325350

**Comment by tufeikafei** [comment]
已申请，多谢大神。

**Comment by georgezhao2010** [comment]
已在v0.3.9添加支持
