### ISSUE TITLE
期待添加美的全直流变频中央空调的支持（附带 msmart.cli 搜索结果）

### ISSUE THREAD

**Issue by helixzz** [georgezhao2010/midea_ac_lan#8]
空调型号（室外机）：MDVH-V120W/N1-620LX
空调型号（室内机）：MDVH-J36T2/BP3N1Y-LX(B) （以及其他几个同系列不同功率型号）

随机配有 86 面板式的美的 Wi-Fi 开关网关一只，该网关自带一路触摸开关功能。
通过“美的美居”App 可以搜索到该网关并通过 Wi-Fi 方式配置网络联网。

连网后，“美的美居”App 可以自动发现多台室内机（网关与空调通信使用三条线，不确定是 RS485 还是美的私有协议），并分别控制每台室内机的运行。

目前，通过 pip 安装的 midea-discover 命令并不能搜到该网关，反而能搜到我同一个网络里的美的洗碗机…

```
helixzz@home-ubuntu:~$ midea-discover
INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP.
ERROR:msmart.security:authentication failed
ERROR:msmart.lan:Authentication failed for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.03 
INFO:msmart.lan:Got TCP key for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.93 tcp_key: ******
INFO:msmart.cli:*** Found a device: {'name': 'midea_e1_1346', 'ssid': 'midea_e1_1346', 'ip': '172.16.29.56', 'port': 6444, 'id': 160528699983452, 'version': 3, 'token': '******', 'key': '******', 'type': 'e1', 'sn': '0E1311760GX600091711013******', 'model': 'GX600', 'support': False, 'run_test': True}
```

**Comment by georgezhao2010** [comment]
> 空调型号（室外机）：MDVH-V120W/N1-620LX 空调型号（室内机）：MDVH-J36T2/BP3N1Y-LX(B) （以及其他几个同系列不同功率型号）
> 
> 随机配有 86 面板式的美的 Wi-Fi 开关网关一只，该网关自带一路触摸开关功能。 通过“美的美居”App 可以搜索到该网关并通过 Wi-Fi 方式配置网络联网。
> 
> 连网后，“美的美居”App 可以自动发现多台室内机（网关与空调通信使用三条线，不确定是 RS485 还是美的私有协议），并分别控制每台室内机的运行。
> 
> 目前，通过 pip 安装的 midea-discover 命令并不能搜到该网关，反而能搜到我同一个网络里的美的洗碗机…
> 
> ```
> helixzz@home-ubuntu:~$ midea-discover
> INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP.
> ERROR:msmart.security:authentication failed
> ERROR:msmart.lan:Authentication failed for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.03 
> INFO:msmart.lan:Got TCP key for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.93 tcp_key: ******
> INFO:msmart.cli:*** Found a device: {'name': 'midea_e1_1346', 'ssid': 'midea_e1_1346', 'ip': '172.16.29.56', 'port': 6444, 'id': 160528699983452, 'version': 3, 'token': '******', 'key': '******', 'type': 'e1', 'sn': '0E1311760GX600091711013******', 'model': 'GX600', 'support': False, 'run_test': True}
> ```

就目前来说，除非您愿意暂时提供一下您的美居账号让我能下载到cc设备的协议包，否则可能性不大，因为我没有设备。

而且就算您愿意提供一下账号，要分析协议也不是一个短时间内能搞定的事情。

**Comment by helixzz** [comment]
> > 空调型号（室外机）：MDVH-V120W/N1-620LX 空调型号（室内机）：MDVH-J36T2/BP3N1Y-LX(B) （以及其他几个同系列不同功率型号）
> > 随机配有 86 面板式的美的 Wi-Fi 开关网关一只，该网关自带一路触摸开关功能。 通过“美的美居”App 可以搜索到该网关并通过 Wi-Fi 方式配置网络联网。
> > 连网后，“美的美居”App 可以自动发现多台室内机（网关与空调通信使用三条线，不确定是 RS485 还是美的私有协议），并分别控制每台室内机的运行。
> > 目前，通过 pip 安装的 midea-discover 命令并不能搜到该网关，反而能搜到我同一个网络里的美的洗碗机…
> > ```
> > helixzz@home-ubuntu:~$ midea-discover
> > INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP.
> > ERROR:msmart.security:authentication failed
> > ERROR:msmart.lan:Authentication failed for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.03 
> > INFO:msmart.lan:Got TCP key for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.93 tcp_key: ******
> > INFO:msmart.cli:*** Found a device: {'name': 'midea_e1_1346', 'ssid': 'midea_e1_1346', 'ip': '172.16.29.56', 'port': 6444, 'id': 160528699983452, 'version': 3, 'token': '******', 'key': '******', 'type': 'e1', 'sn': '0E1311760GX600091711013******', 'model': 'GX600', 'support': False, 'run_test': True}
> > ```
> 
> 就目前来说，除非您愿意暂时提供一下您的美居账号让我能下载到cc设备的协议包，否则可能性不大，因为我没有设备。
> 
> 而且就算您愿意提供一下账号，要分析协议也不是一个短时间内能搞定的事情。

您好！这件事情并不着急，看您的时间安排即可，我可以提供账号，需要时随时私信。

**Comment by georgezhao2010** [comment]
> > > 空调型号（室外机）：MDVH-V120W/N1-620LX 空调型号（室内机）：MDVH-J36T2/BP3N1Y-LX(B) （以及其他几个同系列不同功率型号）
> > > 随机配有 86 面板式的美的 Wi-Fi 开关网关一只，该网关自带一路触摸开关功能。 通过“美的美居”App 可以搜索到该网关并通过 Wi-Fi 方式配置网络联网。
> > > 连网后，“美的美居”App 可以自动发现多台室内机（网关与空调通信使用三条线，不确定是 RS485 还是美的私有协议），并分别控制每台室内机的运行。
> > > 目前，通过 pip 安装的 midea-discover 命令并不能搜到该网关，反而能搜到我同一个网络里的美的洗碗机…
> > > ```
> > > helixzz@home-ubuntu:~$ midea-discover
> > > INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP.
> > > ERROR:msmart.security:authentication failed
> > > ERROR:msmart.lan:Authentication failed for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.03 
> > > INFO:msmart.lan:Got TCP key for 172.16.29.254:44446 -> 172.16.29.56:6444 retries: 0 time: 0.93 tcp_key: ******
> > > INFO:msmart.cli:*** Found a device: {'name': 'midea_e1_1346', 'ssid': 'midea_e1_1346', 'ip': '172.16.29.56', 'port': 6444, 'id': 160528699983452, 'version': 3, 'token': '******', 'key': '******', 'type': 'e1', 'sn': '0E1311760GX600091711013******', 'model': 'GX600', 'support': False, 'run_test': True}
> > > ```
> > 
> > 
> > 就目前来说，除非您愿意暂时提供一下您的美居账号让我能下载到cc设备的协议包，否则可能性不大，因为我没有设备。
> > 而且就算您愿意提供一下账号，要分析协议也不是一个短时间内能搞定的事情。
> 
> 您好！这件事情并不着急，看您的时间安排即可，我可以提供账号，需要时随时私信。

我还会意错了，你这还不是CC面板控制的，目前来说，如果不支持美的这套iot电控协议的设备，支持起来是有难度的，你们家美的电饭锅可能实现起来要容易得多了。

不管怎么说，我先把这个请求重新打开吧，看看以后有没有机会。

**Comment by micturkey** [comment]
如果网关是ga014s的话可以用我这个集成
https://bbs.hassbian.com/thread-17241-1-1.html

如果是那个30多块的暂时无解，可以考虑换cc面板之后再用本repo的集成

**Comment by dwxiayi** [comment]
大佬可以支持下洗衣机和冰箱嘛，都可以通过midea-discover发现，愿意提供账户以便调试，还有公网ssh可以操作。 @georgezhao2010

**Comment by edzhiyi** [comment]
期待大佬支持微波炉

**Comment by firegl99** [comment]
> 如果网关是ga014s的话可以用我这个集成 https://bbs.hassbian.com/thread-17241-1-1.html
> 
> 如果是那个30多块的暂时无解，可以考虑换cc面板之后再用本repo的集成

应该就是开关网关D1ZDK-1B/MSGW-GA017，带一路触控灯控和蓝牙网关（好像专门用来连美的智能门锁），还有一路接中央空调的485接口。
用ac_lan组件，打开debug log，从log看，使用广播的方式没有发现这个网关，大概不支持这种协议。
用ga014组件，log里面提示超时，估计协议不同。不知道能不能抓log分析下看看具体协议是怎么样。。。

**Comment by georgezhao2010** [comment]
对于非MSmart协议的设备，暂时先关闭了
