### ISSUE TITLE
风速和扫风模式没有中文吗

### ISSUE THREAD

**Issue by ihaettypo** [georgezhao2010/midea_ac_lan#81]
好像运行模式和预设模式都有中文， 但风速目前还没有，比如 Low -> 低风。我现在是在card里面翻译的，但是我感觉这个映射翻译也可以在这个集成里面做成配置项吧？

**Comment by georgezhao2010** [comment]
> 

对不起，没有，运行模式是HA的多语言翻译的，但他没有自动翻译风速，我不可能在代码里搞多语言翻译。

**Comment by tty228** [comment]
> 好像运行模式和预设模式都有中文， 但风速目前还没有，比如 Low -> 低风。我现在是在card里面翻译的，但是我感觉这个映射翻译也可以在这个集成里面做成配置项吧？

这个是如何做到的，可以提供一些资料吗？万分感谢
