### ISSUE TITLE
为什么插件多一段时间就丢失？

### ISSUE THREAD

**Issue by benbenwu1** [georgezhao2010/midea_ac_lan#82]
插件更新到最新版本，插件过了大概一个多星期就会不响应，只能重新加载才能用，HA都是更新到最新版的

**Comment by georgezhao2010** [comment]
> 插件更新到最新版本，插件过了大概一个多星期就会不响应，只能重新加载才能用，HA都是更新到最新版的

目前没有发现这个问题，你可以打开调试日志，然后不响应的时候是否有什么日志输出。

你光这么说，我无法判断你的问题出在哪里。

**Comment by moxuec** [comment]
我也遇到了一样的问题。Home Assistant Core版本2023.2.2。多台美的设备静态IP永久租约，日志中显示多台设备先后离线，不同设备之间的离线时间只差几分钟

**Comment by wangrui1573** [comment]
一样的问题，需要手动重新载入

**Comment by ertian** [comment]
一样的问题。两个设备，洗衣机和空调，大概5天左右离线。重启HA后恢复。
