### ISSUE TITLE
Energy consumption metrics are 0

### ISSUE THREAD

**Issue by akanto** [georgezhao2010/midea_ac_lan#83]
Unfortunately, the Energy related entities are 0, and when I have taken a look at the logs it looks like the received message from the device contains zeros in the response. Related code is available here: https://github.com/georgezhao2010/midea_ac_lan/blob/778cd059428ea7ea3dfc18dac6ecdbaf86aa6dcf/custom_components/midea_ac_lan/midea/devices/ac/message.py#L350

Log lines:
```
Received: {'header': 'aa20ac00000000000303', 'body': 'c12101440000000000000000000000000000000001df', 'message type': '03', 'body type': 'c1'}
Status update: {'total_energy_consumption': 0.0, 'current_energy_consumption': 0.0, 'realtime_power': 0.0}
```

The AC unit that I have is Midea MSFAAU-09HRFN8 Breezeless. My question is whether this means that my AC unit does not support energy-related metrics, or is there some switch or flag that needs to be enabled somehow to provide these kinds of metrics?

Many thanks.

**Comment by georgezhao2010** [comment]
> Unfortunately, the Energy related entities are 0, and when I have taken a look at the logs it looks like the received message from the device contains zeros in the response. Related code is available here:
> 
> https://github.com/georgezhao2010/midea_ac_lan/blob/778cd059428ea7ea3dfc18dac6ecdbaf86aa6dcf/custom_components/midea_ac_lan/midea/devices/ac/message.py#L350
> 
> Log lines:
> 
> ```
> Received: {'header': 'aa20ac00000000000303', 'body': 'c12101440000000000000000000000000000000001df', 'message type': '03', 'body type': 'c1'}
> Status update: {'total_energy_consumption': 0.0, 'current_energy_consumption': 0.0, 'realtime_power': 0.0}
> ```
> 
> The AC unit that I have is Midea MSFAAU-09HRFN8 Breezeless. My question is whether this means that my AC unit does not support energy-related metrics, or is there some switch or flag that needs to be enabled somehow to provide these kinds of metrics?
> 
> Many thanks.

Your appliance does not support it, same as mine.

**Comment by akanto** [comment]
Thanks for the quick response.
