### ISSUE TITLE
Exposing external temperature (and others) 

### ISSUE THREAD

**Issue by srleach** [georgezhao2010/midea_ac_lan#84]
Hi There,

Great integration - much nicer than the alternatives. I wonder if it's possible to add the external temperature to be usable in home assistant? (And potentially any other data points, too)

This information appears in the midea app, so the hardware is definitely collecting.

Let me know if there's anything I can provide to help.

**Comment by srleach** [comment]
For anyone who (like me) didn't read far enough down the documentation, this is present in the module. 

Hit configure on the integration after setting up and params can be added. 

Thanks again & sorry for the bad issue creation.

**Comment by georgezhao2010** [comment]
> For anyone who (like me) didn't read far enough down the documentation, this is present in the module.
> 
> Hit configure on the integration after setting up and params can be added.
> 
> Thanks again & sorry for the bad issue creation.

LOL
