### ISSUE TITLE
冰箱是否可以支持开关门的事件

### ISSUE THREAD

**Issue by loveyu** [georgezhao2010/midea_ac_lan#87]
看到DEBUG日志提示：

{"log":"\u001b[36m2022-09-01 07:42:40.533 DEBUG (冰箱) [custom_components.midea_ac_lan.midea.devices.ca.device] [188016489269111] Received: {'header': 'aa13cad900004c000004', 'body': '000100000000000000', 'message type': '04', 'body type': '00'}\u001b[0m\n","stream":"stderr","time":"2022-08-31T23:42:40.534487192Z"}
{"log":"\u001b[36m2022-09-01 07:42:40.533 DEBUG (冰箱) [custom_components.midea_ac_lan.midea.core.device] [188016489269111] Unidentified protocol\u001b[0m\n","stream":"stderr","time":"2022-08-31T23:42:40.534784976Z"}

代码中应该是没有支持04类型，不确定是否为开关门事件的单独定义

**Comment by georgezhao2010** [comment]
> 看到DEBUG日志提示：
> 
> {"log":"\u001b[36m2022-09-01 07:42:40.533 DEBUG (冰箱) [custom_components.midea_ac_lan.midea.devices.ca.device] [188016489269111] Received: {'header': 'aa13cad900004c000004', 'body': '000100000000000000', 'message type': '04', 'body type': '00'}\u001b[0m\n","stream":"stderr","time":"2022-08-31T23:42:40.534487192Z"} {"log":"\u001b[36m2022-09-01 07:42:40.533 DEBUG (冰箱) [custom_components.midea_ac_lan.midea.core.device] [188016489269111] Unidentified protocol\u001b[0m\n","stream":"stderr","time":"2022-08-31T23:42:40.534784976Z"}
> 
> 代码中应该是没有支持04类型，不确定是否为开关门事件的单独定义

你要开关门事件用来做啥，不是已经有了开门超时事件了，开关门状态有何意义？

说来听听

**Comment by loveyu** [comment]
统计用途
