### ISSUE TITLE
想要自动化设置空调风速 ,遇到问题,麻烦指导一下.谢谢

### ISSUE THREAD

**Issue by calvin886886** [georgezhao2010/midea_ac_lan#90]
![图片](https://user-images.githubusercontent.com/109566006/188462379-3ab9042f-d53a-46cb-ad1e-cca4c1d7288c.png)

我在最后动作这里设置.一直保存不了提示错误!

报
Message malformed: required key not provided @ data['to']

请问是书写不规范吗,还是少了什么

**Comment by georgezhao2010** [comment]
> ![图片](https://user-images.githubusercontent.com/109566006/188462379-3ab9042f-d53a-46cb-ad1e-cca4c1d7288c.png)
> 
> 我在最后动作这里设置.一直保存不了提示错误!
> 
> 报 Message malformed: required key not provided @ data['to']
> 
> 请问是书写不规范吗,还是少了什么

你这个device_id是个啥？哪来的？

应该填写的内容是"The Appliance code (Device ID) of appliance"么？是一串数字。

```
device_id: 162727721XXXXX
fan_speed: 80
```

这样的

**Comment by calvin886886** [comment]
![图片](https://user-images.githubusercontent.com/109566006/188608000-0e137627-a921-4be1-baa8-1812ac81a3ae.png)
这个id是ha自己生成的.应该是加过密的
我在图形界面上选了.我要的空调.在转到YAML界面.就可以看到这个id了,
您说的数字ID我也试过.一样是不成功.
