### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by uSlackr** [georgezhao2010/midea_ac_lan#99]
i'm getting this in he log when HArestarts.  Maybe a  typo?  The very last line appears to be missing an "n"
```
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 9:57:32 PM (3 occurrences)
Last logged: 9:57:32 PM

Unable to prepare setup for platform midea_ac_lan.fan: Platform not found (No module named 'custom_components.midea_ac_lan.midea.devices.fa').```

**Comment by bdkacz** [comment]
I have the same error

**Comment by georgezhao2010** [comment]
update to [v0.3.13-Patch1](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.13-Patch1) pls.

**Comment by snug-inglenook** [comment]
> update to [v0.3.13-Patch1](https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.13-Patch1) pls.

While integration went gray/inactive.
